### ISSUE TITLE
UI Freeze when clicking on Preferences > Maven > Installations

### ISSUE THREAD

**Issue by RoiSoleil** [eclipse-m2e/m2e-core#1002]
UI Freeze when clicking on Preferences > Maven > Installations because of MavenEmbededRuntime#toString taking a lot of time to compute on UI thread.

**Comment by HannesWell** [comment]
Duplicat #923

**Comment by HannesWell** [comment]
Please try the latest snapshot and verify that your problem ist fixed:
https://download.eclipse.org/technology/m2e/snapshots/latest/
