### ISSUE TITLE
Location type "Maven": Bundle-SymbolicName is ignored

### ISSUE THREAD

**Issue by JonasArend** [eclipse-m2e/m2e-core#1006]
After upgrading to Eclipse 2022-09 (but the issue seems to be present in 2022-06 also) we wanted to repackage JUnit from Maven using the bundle names previously used by Eclipse (e.g. org.junit.jupiter.api instead of junit-jupiter-api) because we have some dependencies that use require bundle and cannot easily be updated to use the new bundle names.

But for maven dependencies that are newly added to the target platform the Bundle-SymbolicName seems to be ignored. After adding 

```<location includeDependencyDepth="none" includeDependencyScopes="compile" includeSource="true" missingManifest="generate" type="Maven">
            <dependencies>
                <dependency>
                    <groupId>org.junit.jupiter</groupId>
                    <artifactId>junit-jupiter-api</artifactId>
                    <version>5.9.0</version>
                    <type>jar</type>
                </dependency>
            </dependencies>
            <instructions><![CDATA[
Bundle-Name:           Bundle derived from maven artifact ${mvnGroupId}:${mvnArtifactId}:${mvnVersion}
version:               ${version_cleanup;${mvnVersion}}
Bundle-SymbolicName:   org.junit.jupiter.api
Bundle-Version:        ${version}
Import-Package:        *;resolution:=optional
Export-Package:        *;version="${version}";-noimport:=true
DynamicImport-Package: *
]]></instructions>
        </location>
```

to the target platform file the JUnit API in version 5.9.0 is still listed as "junit-jupiter-api" when adding a bundle dependency to a bundle:

![grafik](https://user-images.githubusercontent.com/116799053/198265187-395e335d-1e3a-444d-926f-9fc469ca7cb1.png)

This is not a problem when updating maven artifacts that were previously added to the target platform file (e.g. Mockito-Inline - updated here from 4.6.1 to 4.8.1):

```<location includeDependencyDepth="none" includeDependencyScopes="compile" includeSource="true" missingManifest="generate" type="Maven">
            <dependencies>
                <dependency>
                    <groupId>org.mockito</groupId>
                    <artifactId>mockito-inline</artifactId>
                    <version>4.8.1</version>
                    <type>jar</type>
                </dependency>
            </dependencies>
            <instructions><![CDATA[
Bundle-Name:           Bundle derived from maven artifact ${mvnGroupId}:${mvnArtifactId}:${mvnVersion}
version:               ${version_cleanup;${mvnVersion}}
Bundle-SymbolicName:   org.mockito.mockito-inline
Bundle-Version:        ${version}
Import-Package:        *;resolution:=optional
Export-Package:        *;version="${version}";-noimport:=true
DynamicImport-Package: *
]]></instructions>
        </location>
```

![grafik](https://user-images.githubusercontent.com/116799053/198265415-5e7892f8-aaae-4b92-8f4d-417a52ba897d.png)

**Comment by laeubi** [comment]
https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api/5.9.0 is already a bundle and you canot override provided bundle info in the target for such items. You might create an own bundle taht requires the new one with the "reexport" option enabled, but be aware that tis is still very hacky and might cause issues. Your other dependencies schould really be fixed to use import-package instead of reuire bundle!

**Comment by HannesWell** [comment]
> because we have some dependencies that use require bundle and cannot easily be updated to use the new bundle names.

Can you update those dependencies to use Import-Package instead? For reasons like the ones you encountered, that is actually the recommended OSGi way.
