### ISSUE TITLE
Spurious maven builds

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#1047]
I noticed that sometimes spurious builds are triggered, that is I have an IDE with m2e open but do not work on it still from time to time some (random?) projects are build.

**Comment by HannesWell** [comment]
Does the `Maven Workspace Build` view help in this regard?
It has a `delta` section, but I'm not sure if this is the delta that triggered the build or the delta that was caused by the build.

**Comment by laeubi** [comment]
I close this for now as handling of incremental builds was imrpoved
