### ISSUE TITLE
Eclipse for java 2022-09 : xml line comment not working in m2e pom source editor tab

### ISSUE THREAD

**Issue by deslauriersp** [eclipse-m2e/m2e-core#1093]
I am unable to properly comment a section of pom.xml within the source tab of the pom editor of  m2e.

**1. Download eclipse 2022-09 for java dev: eclipse-java-2022-09-R-win32-x86_64.zip**
certUtil -hashFile D:\Applfich\eclipse-java-2022-09-R-win32-x86_64.zip MD5
_da3da6d57c4f60b1ca0f75bc8988bd4c_

m2e version is 2.0.4.20220904-1703

**2. Extract the eclipse**
D:\Applfich\eclipse-java-2022-09-R-win32-x86_64

**3. Create workspace folder**
D:\Applfich\eclipse-java-2022-09-R-win32-x86_64\eclipse\workspace

**4. Extract demo maven projet in workspace**
[generic-text-editor.zip](https://github.com/eclipse-m2e/m2e-core/files/10105511/generic-text-editor.zip)

**5. Launch eclipse**
D:\Applfich\eclipse-java-2022-09-R-win32-x86_64\eclipse\eclipse.exe -data D:\Applfich\eclipse-java-2022-09-R-win32-x86_64\eclipse\workspace  -clean

**6. Import existing maven project.**

  **7. Open pom.xml and comment**
In source tab, using mouse, select a section in pom.xml and using menu, use line comment. Save (ctrl+s)
![image](https://user-images.githubusercontent.com/10866929/204323871-aedf9155-c5d6-4637-8c2f-573939c949d9.png)

![image](https://user-images.githubusercontent.com/10866929/204324743-cc3a5100-03ae-48b0-93be-d566db2744ef.png)

**8. Open pom.xml source file with you preferred text editor (outside eclipse)**
And see that source in not the same as displayed in editor
![image](https://user-images.githubusercontent.com/10866929/204324891-406062b1-b588-420c-8327-44f95acb0ba3.png)

**Comment by deslauriersp** [comment]
m2e version is 2.0.4.20220904-1703

**Comment by deslauriersp** [comment]
updated m2e components.

![image](https://user-images.githubusercontent.com/10866929/204339494-7245e185-939d-46ca-998d-0a6778d46f71.png)

issue is still there

**Comment by mickaelistria** [comment]
Can you please install latest release of Eclipse TM4E from https://download.eclipse.org/tm4e/releases/latest/ and report whether things get better with it?

**Comment by deslauriersp** [comment]
that seems to solve the issue! 

![image](https://user-images.githubusercontent.com/10866929/204363112-e51ce91c-53bd-4071-93db-d62da98a387b.png)

a) line comments work
b) keyboard shortcut for line comments works (comment / uncomment)
c) block comments work
d) keyboard shortcut for block comment works

**Comment by mickaelistria** [comment]
Thanks for the feedback.

**Comment by deslauriersp** [comment]
Thank you for your support. 

![image](https://user-images.githubusercontent.com/10866929/204363710-2d5f1271-b8b7-4625-b229-600130b79c51.png)
