### ISSUE TITLE
Eclipse for java 2022-09 : xml code completion not working in source tab of pom editor

### ISSUE THREAD

**Issue by filip-java** [eclipse-m2e/m2e-core#1094]
same environment as https://github.com/eclipse-m2e/m2e-core/issues/1093

basic XML code completion based on schema does not work.

schema is set to xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"

![image](https://user-images.githubusercontent.com/10866929/204330946-6ed1919e-cf59-40dc-8b7e-3615541cedff.png)

I would have expected something like that

![image](https://user-images.githubusercontent.com/10866929/204331368-b667b420-f8ab-4b79-ae4d-d4bc6f1c5419.png)

**Comment by howlger** [comment]
I cannot reproduce this in m2e 2.1.0.

Please make sure your environment is up to date to avoid reporting already fixed bugs.

**Comment by deslauriersp** [comment]
Thank you for your reply, 
I upgraded to latest version. 

But for me, the lastest version from Nov 22nd, it 2.0.6

![image](https://user-images.githubusercontent.com/10866929/204355569-5fa07f20-f778-4974-8ea1-e178fadb2227.png)

Clearly new version is trying to download XSD, but I get a weird network error

Error while downloading 'https://maven.apache.org/xsd/maven-4.0.0.xsd' to 'C:\Users\[hidden]\.lemminx\cache\https\maven.apache.org\xsd\maven-4.0.0.xsd' : '[java.net.SocketException] Permission denied: connect'.

The network works, as marketplace, software updates and other features works within eclipse.
I don't need a proxy to access Internet based resources. 

With my browser, I validated the URL, it works

I am running eclipse itself in debug mode, and remote debugging it from another eclipse install. I am unable to catch any java.net.SocketException (caught or uncaught). I have also added breakpoints to "SocketException" constructors. Nothing seems to hit these breakpoints.

I cannot see any stack/meaningfull logs in  eclipse/workspace/.metadata/.log 
I cannot see any stack/meaningfull logs in eclipse/.metadata/.log

any ideas?

**Comment by howlger** [comment]
m2e consists of different features, each with its own version. So, yes, 2.0.6 from November 22nd is the right one.

Could you please check with the [release candidate 1 build of Eclipse 2022-12](https://www.eclipse.org/downloads/packages/release/2022-12/rc1) and a fresh workspace if you still see issues?

**Comment by deslauriersp** [comment]
Same problem with RC1. The network thing is probably something on my side... don't know what exactly. I'll dig into it.

FYI : https://github.com/eclipse-m2e/m2e-core/issues/1093 is also present in RC1. I guess it is missing TextMate update.

**Comment by HannesWell** [comment]
From my experience it happens (too) often that the language server gets stuck computing its response (see for example https://github.com/eclipse-m2e/m2e-core/issues/909).
I have the impression this happens more often on Windows than on Linux (at work I use Linux, at home Windows).
I used visual VM once and there it looked like the LS is waiting for a project update that never happened.

**Comment by filip-java** [comment]
works with this config
network issue was on my side

![image](https://user-images.githubusercontent.com/10866929/204621931-f33c22db-9195-43de-9293-e1e7cef5106c.png)
