### ISSUE TITLE
The 2.1.1 release repository contains unsigned source features

### ISSUE THREAD

**Issue by merks** [eclipse-m2e/m2e-core#1097]
The 2.1.1 release repository:

https://download.eclipse.org/technology/m2e/releases/2.1.1

contains unsigned source features:

https://download.eclipse.org/oomph/archive/reports-extra/m2e-releases-2.1.1/download.eclipse.org/technology/m2e/releases/2.1.1/index.html

**Comment by HannesWell** [comment]
Sigh. :/ Looks like I have to run the third release within five days.
Nevertheless thanks for making us aware of this problem.
Just created #1102 to address the issue.

Is it sufficient to have a fix today (Wednesday) evening (UTC+1)?

**Comment by merks** [comment]
@HannesWell Yes, that will be just fine.

**Comment by HannesWell** [comment]
The latest report does not list m2e under unsigned artifacts, so I think this is resolved successfully:

https://download.eclipse.org/staging/2022-12/buildInfo/archive/download.eclipse.org/staging/2022-12/

**Comment by merks** [comment]
Thanks!
