### ISSUE TITLE
Legacy POM Editor: Maybe update / check dependency version ranges to allow updating to 2022-09 release

### ISSUE THREAD

**Issue by rhoehener** [eclipse-m2e/m2e-core#1109]
Not sure if this is the correct place to report.

Only if there are no actual incompatibilities. But maybe the limitation to "M2E Maven Integration for Eclipse Core" version 1.x is accidental and could be increased to include 2.x.

Details: https://stackoverflow.com/questions/74639229/is-it-possible-to-get-the-pom-editor-legacy-using-webtools-sourceediting-ui

**Comment by mickaelistria** [comment]
The code of the legacy editor was fully removed as it was not maintained. If you're willing to invest a sufficient effort to revive it, update it to latest m2e and commit to some mid-term maintenance, then it can be re-introduced in the project.

**Comment by rhoehener** [comment]
Too bad, we are not against migrating to the new editor per se, we just wanted to wait until it is possible to [share XML formatting settings](https://stackoverflow.com/questions/69298530/eclipse-wild-web-developer-generic-editor-how-to-share-the-language-server-xml) to avoid commit wars within the team.

**Comment by rhoehener** [comment]
Can't it be released from the 2022-06 codebase just with the dependency ranges adjusted?

**Comment by mickaelistria** [comment]
> Can't it be released from the 2022-06 codebase just with the dependency ranges adjusted? We could add the update site manually.

No, it's too much effort and unless someone really commits in maintaining it, then it gives a false impression of it being maintained.
The 2 only viable choices are either use the new editor; or really invest continuous manpower to revive and maintain the legacy editor in m2e.

About your issue with document formatting, I think there can be multple possible alternatives: try the Eclipse integation with editorconfig (on marketplace), set up commit hooks to auto-format files before commits, plug an external formatter as a save action in the Eclipse IDE...

**Comment by rhoehener** [comment]
We considered commit hooks. Will look into editorconfig. Didn't know about the possibility to plug an external formatter to a save action, sounds promising. Thanks for the suggestions.

**Comment by mickaelistria** [comment]
You can plug any execution on a save action. It's one of the many hidden gems.
Note that Wild Web Developer XML editor now has more edition options; you may want to review those in case they fit your need. Note that not having the WTP pom editor doesn't mean that you cannot use the WTP XML formatter. You could still open files with the WTP XML Editor (if you have it installed) and run the formatting in it. If it seems interesting, you can implement an Eclipse plugins that would simply allow to run the WTP XML formatter via a context-menu, even when using the newer POM editor.

**Comment by rhoehener** [comment]
Yes thank you. I just mentioned that option to a colleague an hour ago (editing with WWD and formatting with WTP). Perfect solution would be a save action, and the formatting settings under version control on per project basis.

**Comment by rhoehener** [comment]
Could you point me to some resources about custom save actions? I don't see any options in the preferences UI.

**Comment by mickaelistria** [comment]
What I have in mind is Right-Click on project > Properties > Builders; and add a builder that runs a random command and use the other options to enable its automated execution on various event (if you have auto build enabled, then saving triggers build, so a save event triggers the action).

**Comment by rhoehener** [comment]
Got it, thanks.

**Comment by HannesWell** [comment]
Can this issue then be closed?
