### ISSUE TITLE
Eclipse debugging problem due to MavenSourceContainerResolver NullPointerException (org.eclipse.m2e.sourcelookup)

### ISSUE THREAD

**Issue by teDDyGH** [eclipse-m2e/m2e-core#1112]
Investigating on Eclipse 2022-09 debugging problem that prevent me to debug my own source file with the warning 
![immagine](https://user-images.githubusercontent.com/14575173/205320158-37fd835f-ebb9-4353-a01f-58aba4b8dd13.png)

I discovered in Eclipse verbose mode (eclipse -verbose -consoleLog) this exception:

`!MESSAGE Problems occurred when invoking code from plug-in: "org.eclipse.debug.core".
!STACK 0
java.lang.NullPointerException: Cannot invoke "java.util.Collection.isEmpty()" because "classesArtifacts" is null
        at org.eclipse.m2e.sourcelookup.internal.launch.MavenSourceContainerResolver.resolveSourceContainers(MavenSourceContainerResolver.java:40)`
        
In 2.1.2 release, the commit [64fa175394b4017573d695831fbd9c6ebe83e3de](https://github.com/eclipse-m2e/m2e-core/commit/64fa175394b4017573d695831fbd9c6ebe83e3de) removed the null-check on `MavenSourceContainerResolver.java`  but `MavenArtifactIdentifier.identifyCentralSearch` still return null on some conditions.

I temporary solved deleting the file MavenSourceContainerResolver.class from 
C:\Devel\eclipse\plugins\org.eclipse.m2e.sourcelookup_2.0.1.20221118-1906\org\eclipse\m2e\sourcelookup\internal\launch

**Comment by HannesWell** [comment]
Please verify with the snapshot that will be available in about 15min at the following p2-repo that this is fixed:
https://download.eclipse.org/technology/m2e/snapshots/2.1.3/

**Comment by teDDyGH** [comment]
I tested the snapshot, bug fixed, thank you!

**Comment by HannesWell** [comment]
> I tested the snapshot, bug fixed, thank you!

Great. Thanks for the feedback.

We will probably perform another release before Christmas addressing regressions and catching up with dependency updates from the Eclipse 2022-12 release.
