### ISSUE TITLE
MavenProjectChangedListener does not define..

### ISSUE THREAD

**Issue by nimo23** [eclipse-m2e/m2e-core#1129]
After upgrading eclipse to 2022-12, I get the following error when updating my Eclipse Project (right clicking pom.xml -> "Maven->Update Project"):

```
An internal error occurred during: "Updating Maven Dependencies".
Receiver class com.baselet.plugin.MavenProjectChangedListener does not define or
inherit an implementation of the resolved method 'abstract void 
mavenProjectChanged(java.util.List, org.eclipse.core.runtime.IProgressMonitor)' of 
interface org.eclipse.m2e.core.project.IMavenProjectChangedListener.
```

When closing the error box, it constantly appears again and again forcing me to kill eclipse and restart again.

- Eclipse IDE for Enterprise Java and Web Developers: Version: 2022-12 (4.26.0)
- M2E - Maven Integration for Eclipse version 2.1.3.20221206-1805

**Comment by fbricon** [comment]
Based on the error message, looks like the Umlet eclipse plugin is not compatible with m2e 2.x. https://github.com/umlet/umlet/blob/0da4d7d175fd52283ed3a5e8fe38d4723e7ac51f/umlet-eclipse-plugin/src/main/java/com/baselet/plugin/MavenProjectChangedListener.java#L15. 

If you can live without it, uninstall it, else you'll need to use an older version of Eclipse.

**Comment by HannesWell** [comment]
Can you have a look in the `Error Log` and check if there is a Stack-trace associated with this error?
If yes that usually helps to identify the issue.

**Comment by fbricon** [comment]
JBoss' m2e-apt has been included in m2e 2.x, so you can uninstall it
