### ISSUE TITLE
Bug 571653 - Format action in pom.xml editor sets bad indentation level and moves selection 

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-m2e/m2e-core#113]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=571653

**Comment by laeubi** [comment]
Probably now obsolete or an issue of lemminx?

**Comment by mickaelistria** [comment]
Yes, overall it's one of this issue behind the hood: https://github.com/eclipse/wildwebdeveloper/issues?q=is%3Aissue+is%3Aopen+format . No particular fix is needed in m2e.
