### ISSUE TITLE
After update macOS to 13, when edit pom.xml use Maven POM Editor, then eclipse crash

### ISSUE THREAD

**Issue by zhanming** [eclipse-m2e/m2e-core#1136]
**Environment**
macOS: Ventura, version: 13.0.1
JRE: 19.0.1 (Installed by Eclipse-Installer)
Eclipse:  2022-12 (4.26.0)
M2E: 2.1.2.20221130

**Describe the process**
1. I use Eclipse Installer to install Eclipse.
2. Install a fresh new Eclipse on macOS.
3. When open a pom.xml (Open With -> Maven POM Editor) and enter a character "<" on a right place (I want to add an xml element) , and the Maven POM Editor give the hints, then eclipse crash.

I compared in another way to open the pom.xml, when I open pom.xml using Open With -> XML Editor, and  enter the character "<",  eclipse won't crash and everything is fine.

I tested both JRE 17.0.5 and JRE 19.0.1 from Eclipse Install (Eclipse 2022-12), the same result.

**By the way**
I don't get any logs in workspace/.metadata/.log file.
Before I update macOS to 13, the Maven POM Editor is also fine.

**Comment by fbricon** [comment]
This is a known upstream issue with Ventura, caused by the embedded browser. Workaround is to start eclipse from command line, as per https://github.com/eclipse-platform/eclipse.platform.swt/issues/452#issuecomment-1295806955

**Comment by zhanming** [comment]
Got it, thank you for the quick reply.
