### ISSUE TITLE
Bug 571572 - UI for setting the location of the toolchain.xml files

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-m2e/m2e-core#114]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=571572

> The location of the toolchain.xml files (user and global scopes) should be able to be set from the UI. The current "User Settings" preferences page could be the right place for it.
> 
> Then, the -gt and/or -t options would be used when invoking Maven so that the values set in the UI were passed to Maven.

**Comment by laeubi** [comment]
@mickaelistria as you recently worked in that area, do you think you can add support for configuring toolchains?

**Comment by mickaelistria** [comment]
Sorry, I don't plan to work on it at this moment. Should I close as I reprorted it and it got inactive for nore than 2 years?

**Comment by laeubi** [comment]
We should just keep it I think it would be useful to have this as a reminder.
