### ISSUE TITLE
Updated versions available for the target platform

### ISSUE THREAD

**Issue by merks** [eclipse-m2e/m2e-core#1145]
The following minor version updates are available for the target platform:

 - [ch.qos.logback](https://repo1.maven.org/maven2/ch/qos/logback/)
    - [logback-classic](https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/) **[1.2.11](https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.2.11)** < [1.4.5](https://repo1.maven.org/maven2/ch/qos/logback/logback-classic/1.4.5/)
 - [com.google.code.gson](https://repo1.maven.org/maven2/com/google/code/gson/)
    - [gson](https://repo1.maven.org/maven2/com/google/code/gson/gson/) **[2.9.1](https://repo1.maven.org/maven2/com/google/code/gson/gson/2.9.1)** < [2.10](https://repo1.maven.org/maven2/com/google/code/gson/gson/2.10/)
 - [io.takari.m2e.workspace](https://repo1.maven.org/maven2/io/takari/m2e/workspace/)
    - [org.eclipse.m2e.workspace.cli](https://repo1.maven.org/maven2/io/takari/m2e/workspace/org.eclipse.m2e.workspace.cli/) **[0.3.1](https://repo1.maven.org/maven2/io/takari/m2e/workspace/org.eclipse.m2e.workspace.cli/0.3.1)** < [0.4.0](https://repo1.maven.org/maven2/io/takari/m2e/workspace/org.eclipse.m2e.workspace.cli/0.4.0/)

**Comment by merks** [comment]
There seem to be missing dependencies for this newer logback version.

**Comment by HannesWell** [comment]
Since logback-1.3 SLF4J-2 ist required.

**Comment by merks** [comment]
Yes, I noticed that this resolved okay in my larger target platform, so I assume this will be handled when the migration to slf4j version 2.x is finished.
