### ISSUE TITLE
pom editor / <ctrl> / cannot navigate to dependency (2022-12)

### ISSUE THREAD

**Issue by eliasbalasis** [eclipse-m2e/m2e-core#1184]
Historically, in m2e POM editor when hovering with <ctrl> over a dependency, I could jump to the dependency itself or the place where it is managed.

In Eclipse 2022-12, I can only jump to the dependency's POM but not to the place where the dependency is managed.

Also, contrary to historical behavior, if a dependency is present in the Eclipse workspace the POM editor jumps to the workspace file but not anymore.

**Comment by mickaelistria** [comment]
Can you please request this to lemminx-maven project which would be the proper host for such addition?
