### ISSUE TITLE
Bug 465483 - Support polyglot maven

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-m2e/m2e-core#119]
See https://bugs.eclipse.org/bugs/show_bug.cgi?id=465483

**Comment by laeubi** [comment]
This relates to #118 as polyglot is integrated as a maven extension.

**Comment by laeubi** [comment]
Requires
- https://github.com/eclipse-m2e/m2e-core/issues/546

**Comment by laeubi** [comment]
It is now possible to import polyglot projects.

**Comment by mickaelistria** [comment]
Awesome!
