### ISSUE TITLE
Bug 478647 - Provide an alternative Artifact search mechanism

### ISSUE THREAD

**Issue by foal** [eclipse-m2e/m2e-core#122]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=478647

**Comment by laeubi** [comment]
@foal is this related to https://github.com/eclipse-m2e/m2e-core/pull/10 ?

**Comment by foal** [comment]
Yes. Did not check the PR only issues.

**Comment by laeubi** [comment]
@mickaelistria as far as i remember this is now obsolete as search is handled by lemminx?

**Comment by foal** [comment]
I see the warning `Index downloads are disabled, search results may be incomplete.` in the select dependency dialog. If it is not relevant any more maybe remove this warning? 
 
![image](https://user-images.githubusercontent.com/458209/168659964-9e907af8-c8df-440a-a473-b8bb3a09d668.png)

**Comment by HannesWell** [comment]
You can now search directly in the pom-editor (Mickael correct me if I'm wrong).
Just type in what you are interested in and the content assist will make proposals based on the search results.
If you use the content assist for specific fields, proposals for that field should be shown.

**Comment by foal** [comment]
Not sure that is convenient replacement.
![image](https://user-images.githubusercontent.com/458209/168733776-a8c12ad5-0133-461f-8ac7-0f05209845e8.png)

To see some results, I must (?) know the group name of the artifact, but it is not usually the case
![image](https://user-images.githubusercontent.com/458209/168734154-44dcce9a-30a2-4e52-a5a3-ae48ccf91af8.png)

Or did I use it in the wrong way?

**Comment by laeubi** [comment]
> Or did I use it in the wrong way?

@foal you can report any issues to https://github.com/eclipse/lemminx-maven/ that's where it is implemented now, so m2e is "just" a consumer of that functionality but do not provide the editor.

**Comment by laeubi** [comment]
> I see the warning `Index downloads are disabled, search results may be incomplete.` in the select dependency dialog. If it is not relevant any more maybe remove this warning?

Could you open a dedicated issue for this so it can be addressed?
