### ISSUE TITLE
Resources no longer copied when .mvn directory exists

### ISSUE THREAD

**Issue by Frettman** [eclipse-m2e/m2e-core#1225]
I'm having the wierd issue that as soon as a project contains the `.mvn` directory, resources from `src/main/resources` are no longer copied to `target\classes`. An empty `.mvn` folder is enough. I can reproduce this with a fresh 2022-12 [Eclipse IDE for Java Developers](https://www.eclipse.org/downloads/packages/release/2022-12/r/eclipse-ide-java-developers) by creating a new Maven project. Create a  resource file and it ends up in `target\classes`. Create the `.mvn` directory, do a clean and the resource file is gone and won't reappear.
2022-03 doesn't have the issue yet.

**Comment by laeubi** [comment]
Please try out the latest snapshot build, you can use this p2 repository:

https://download.eclipse.org/technology/m2e/snapshots/latest/

**Comment by Frettman** [comment]
Yes, thank you, that fixes it. I also just found #1150 so it's been reported and fixed already, just not released yet. So I'm closing this.
