### ISSUE TITLE
Unmappable characters in filename break project import

### ISSUE THREAD

**Issue by jdneo** [eclipse-m2e/m2e-core#1246]
Original issue: https://github.com/microsoft/vscode-java-dependency/issues/712.

Reproduced steps: https://github.com/microsoft/vscode-java-dependency/issues/712#issuecomment-1415714628

Looks like when the project has utf8 characters (like `ä`) and the system encoding is not utf8, the import will be broken totally.

**Comment by laeubi** [comment]
@jdneo I don't think this is an issue with m2e but with the resource framework of eclipse: 
https://github.com/eclipse-platform/eclipse.platform

**Comment by jdneo** [comment]
Filed at: https://github.com/eclipse-platform/eclipse.platform/issues/335
