### ISSUE TITLE
Allow Test to be skipped when pom specifies maven.test.skip=true

### ISSUE THREAD

**Issue by RoiSoleil** [eclipse-m2e/m2e-core#1262]
Allow Test to be skipped when pom specifies maven.test.skip=true in M2E

**Comment by rnesselrath** [comment]
We have a very specific configuration where we call the maven-compiler-plugin two times. First in the normale compile phase and second in . Reason is that we generate additional source code in between that requires the already compiled test classes from the first plugin call. Additionally we haven the option to skip the second plugin call. To sum up we have the following compiler plugin definition in our pom:

`
  <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.8.1</version>
        <executions>
          <execution>
            <id>default-testCompile</id>
            <phase>test-compile</phase>
            <goals>
              <goal>testCompile</goal>
            </goals>
          </execution>
          <execution>
            <id>compile-generated-specs</id>
            <phase>process-test-classes</phase>
            <goals>
              <goal>testCompile</goal>
            </goals>
            <configuration>
              <skip>true</skip>
            </configuration>
          </execution>
        </executions>
`
The skip in the second execution block leads to the problem that test sources are not added to the classpath anymore.
I think changing one line would fix this issue.

 isTestCompilationSkipped = isTestCompilationSkipped ||  Boolean.TRUE
                .equals(maven.getMojoParameterValue(mavenProject, compile, "skip", Boolean.class, monitor));
