### ISSUE TITLE
No more content assist nor syntaxic coloration with latest snapshot

### ISSUE THREAD

**Issue by Kiiv** [eclipse-m2e/m2e-core#1265]
Hi,

Trying the latest snapshot, I don't have content assist (popup on mouse over for example) or syntaxic coloration of xml in the pom editor anymore.
I still have the tabulation with dependencies, Overview, effective pom so Eclipse seems to open Pom editor correctly.

![pom_editor](https://user-images.githubusercontent.com/695160/220312653-8d7f9aa8-a02f-4d60-a752-2594dc797974.png)

[log.txt](https://github.com/eclipse-m2e/m2e-core/files/10792732/log.txt)

As you can see in the log file, there is also some maven configuration error on the project.

Installation details :
  AspectJ Compiler	1.9.6.202202111622	org.aspectj.feature.group	Eclipse AspectJ Development Tools
  AspectJ Development Tools	2.2.4.202202111622	org.eclipse.ajdt.feature.group	Eclipse AspectJ Development Tools
  Buildship: Eclipse Plug-ins for Gradle	3.1.6.v20220511-1359	org.eclipse.buildship.feature.group	Eclipse Buildship
  Code Recommenders for Java Developers	2.5.4.v20180909-1132	org.eclipse.recommenders.rcp.feature.feature.group	Eclipse Code Recommenders
  Code Recommenders Snipmatch	2.5.4.v20180909-1132	org.eclipse.recommenders.snipmatch.rcp.feature.feature.group	Eclipse Code Recommenders
  Cross References tool (XRef)	2.2.4.202202111622	org.eclipse.contribution.xref.feature.group	Eclipse AspectJ Development Tools
  Data Tools Platform Enablement Extender SDK	1.14.102.201911250848	org.eclipse.datatools.enablement.sdk.feature.feature.group	Eclipse Data Tools Platform
  Data Tools Platform Extender SDK	1.14.102.201911250848	org.eclipse.datatools.sdk.feature.feature.group	Eclipse Data Tools Platform
  Data Tools Platform SQL Development Tools	1.14.201.202107090755	org.eclipse.datatools.sqldevtools.feature.feature.group	Eclipse Data Tools Platform
  Docker Tooling	5.9.0.202211291906	org.eclipse.linuxtools.docker.feature.feature.group	Eclipse Linux Tools
  Docker Tooling Editor	5.9.0.202211291906	org.eclipse.linuxtools.docker.editor.ls.feature.feature.group	Eclipse Linux Tools
  EclEmma Java Code Coverage	3.1.6.202206011447	org.eclipse.eclemma.feature.feature.group	Eclipse EclEmma
  Eclipse IDE for Java Developers	4.26.0.20221201-1200	epp.package.java	Eclipse Packaging Project
  Eclipse Java Development Tools	3.18.1400.v20221123-1800	org.eclipse.jdt.feature.group	Eclipse.org
  Eclipse Weaving Service Feature	2.2.4.202202111622	org.eclipse.contribution.weaving.feature.group	Eclipse AspectJ Development Tools
  Eclipse XML Editors and Tools	3.28.0.v202211200019	org.eclipse.wst.xml_ui.feature.feature.group	Eclipse Web Tools Platform
  Equinox Weaving SDK	1.2.0.202202111622	org.eclipse.equinox.weaving.sdk.feature.group	Eclipse AspectJ Development Tools
  Git integration for Eclipse	6.4.0.202211300538-r	org.eclipse.egit.feature.group	Eclipse EGit
  GWT Eclipse Plugin	3.0.0.201710131939	com.gwtplugins.eclipse.suite.v3.feature.feature.group	GWT Eclipse Plugin
  Java implementation of Git	6.4.0.202211300538-r	org.eclipse.jgit.feature.group	Eclipse JGit
  JavaScript Debugger with Source Mapping Support	1.0.10.202009231620	com.github.sdbg.feature.feature.group	sdbg.github.org
  JNA Library	4.1.0.v06022015_1911	net.java.dev.jna.feature.group	null
  LiClipseText Feature	2.4.0.202211050736	org.brainwy.liclipsetext.feature.feature.group	Brainwy Software Ltda
  Logback Classic Module	1.2.11	ch.qos.logback.classic	QOS.ch
  Logback Core Module	1.2.11	ch.qos.logback.core	QOS.ch
  M2E - Maven Integration for Eclipse	2.2.0.20230217-1439	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e
  M2E - POM Editor using LemMinX language server (includes Incubating components)	2.0.3.20230202-1631	org.eclipse.m2e.lemminx.feature.feature.group	Eclipse.org - m2e
  M2E - SLF4J over Logback Logging	2.1.1.20230106-1511	org.eclipse.m2e.logback.feature.feature.group	Eclipse.org - m2e
  m2e connector for the Maven Dependency Plugin	0.0.4.201409291703	com.ianbrandt.tools.m2e.mdp.feature.feature.group	null
  Maven SCM handler for Subclipse	1.0.0.201609101315	org.sonatype.m2e.subclipse.feature.feature.group	Subclipse
  Mylyn Builds Connector: Hudson/Jenkins	1.17.0.v20200730-1155	org.eclipse.mylyn.hudson.feature.group	Eclipse Mylyn
  Mylyn Context Connector: Eclipse IDE	3.25.2.v20200828-1617	org.eclipse.mylyn.ide_feature.feature.group	Eclipse Mylyn
  Mylyn Context Connector: Java Development	3.25.2.v20200828-1617	org.eclipse.mylyn.java_feature.feature.group	Eclipse Mylyn
  Mylyn Versions Connector: Git	1.17.0.v20191002-0716	org.eclipse.mylyn.git.feature.group	Eclipse Mylyn
  Mylyn WikiText	3.0.42.202201072301	org.eclipse.mylyn.wikitext_feature.feature.group	Eclipse Mylyn
  PyDev for Eclipse	10.0.1.202211050736	org.python.pydev.feature.feature.group	Fabio Zadrozny
  SonarLint for Eclipse	7.6.0.58887	org.sonarlint.eclipse.feature.feature.group	SonarSource
  Subclipse	4.3.3.202012181204	org.tigris.subversion.subclipse.feature.group	Subclipse
  Subclipse Integration for Mylyn (Optional)	4.2.0.1	org.tigris.subversion.subclipse.mylyn.feature.feature.group	Subclipse
  Subversion 1.14 JavaHL	1.14.0.202005311413	org.tigris.subversion.clientadapter.javahl.feature.feature.group	Subclipse
  Subversion Revision Graph	4.2.0.1	org.tigris.subversion.subclipse.graph.feature.feature.group	Subclipse
  SVNKit Client Adapter	1.8.12.3	org.tigris.subversion.clientadapter.svnkit.feature.feature.group	Subclipse
  SVNKit Library	1.10.2.r10793	org.tmatesoft.svnkit.feature.group	TMate Software
  Tip of the Day UI Feature	0.3.0.v20221111-1229	org.eclipse.tips.feature.feature.group	Eclipse.org
  TM Terminal	11.0.0.202210031642	org.eclipse.tm.terminal.feature.feature.group	Eclipse CDT

**Comment by mickaelistria** [comment]
I suspect that some plugins diidn't load properly for some reasons. The log you shared says it's a continuation of a previous log file. Can you please check the first part of the log pointed in the message for hints regarding m2e plugins?

**Comment by Kiiv** [comment]
Thanks for your support. For now I've totally f*cked up my Eclipse installation trying to unsinstall/reinstall de m2e plugins ><
Everything seems to be installed but Maven options in Eclipse doesn't show up anymore (not even in preference or drop down menu on a project)...

I'll come back when I got something working again ! ^^

**Comment by laeubi** [comment]
Just in case you upgraded from a previous installation, make sure **Java 17** is used as the JVM to **run** Eclipse (you should see this in the system details).

Also sometimes it might be good to download a Eclipse-Package fresh from the download site (E.g. Eclipse for RCP/RAP developers).

**Comment by Kiiv** [comment]
Ok here is a fresh log file.

Do you think it could be related to org.eclipse.lsp4e error ?
[log.txt](https://github.com/eclipse-m2e/m2e-core/files/10793875/log.txt)


@laeubi : thanks. I'm currently running Eclipse with a Java 17 JRE.
Even if a clean install is sometime better it's time consuming to configure all over again ;)

**Comment by mickaelistria** [comment]
Yes, it is definitely related to the LSP4E error: this error prevents the Maven  text editor extension plugin from loading entirely.
As you're already into snapshots, you may try to install latest snapshots of Eclipse LSP4E which should have it fixed (since a few hours ago only).

**Comment by Kiiv** [comment]
Just reinstalling gson dependency from http://download.eclipse.org/lsp4e/snapshots/ did the trick ! Thank you :)
