### ISSUE TITLE
m2e build is triggered by chnage in target folder

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#1275]
I have a multi-module project where random builds are triggered, and even can result in endless build cycles.

According to the Maven Workspace Build View, this is triggered by a change in the target folder:

![grafik](https://user-images.githubusercontent.com/1331477/221766070-7b9c27d9-2a17-4442-bf79-64caf32662c1.png)

One observation is that, weather or not this should trigger a change, even the parent project build is triggered by its child change.

I then open a terminal and touch a random file in the target folder a build is triggered.

**Comment by laeubi** [comment]
To narrow this down I tried to remove the parent project from the workspace but still any change in the `target` folder triggers a build. The build previously has had some source folders that point to a folder inside target, but configuring these to a different location still triggers the build.

**Comment by laeubi** [comment]
I now have checked this with a simple project with only one class and no items configured.
When I compile the project once and then touch the resulting jar in the target folder, each touch results in a workspace build.

**Comment by mickaelistria** [comment]
Is the target folder marked as derived in project metadata? I think it used to be the criterion in order to decide whether a rebuild is necessary or not.

**Comment by laeubi** [comment]
Yes, but actually this does not make any difference. Also it is possible that resources are derived (eg. generated) but still relevant for build input ... as far as I can see currently there is no filtering at all, even if one changes a property of a folder a build is triggered, but I'm currently working on a patch.

**Comment by laeubi** [comment]
@mickaelistria I'm playing around a bit and found that m2e is not getting the change in the .java file but a change in the .class file! That's a bit surprising but maybe the reason why the target folder can't be excluded actually as otherwise m2e won't get a trigger at all ... I'll try to debug this a bit more in detail.

**Comment by HannesWell** [comment]
I encountered that problem as well which resulted sometimes in endless builds for me, because the change in the target-folder done by a executed mojo triggered a new build.
But believed one reason was that the Eclipse-resources/builder did not know that the executed mojo did that change (e.g. because it didn't use the build-context). So maybe a refresh of the project after the m2e-builder had completed (wherever the build-context is read) could help here as well?

**Comment by laeubi** [comment]
I think both should be combined, because even if someone else outside eclipse modifies a file in the target this should normally not trigger a build, I'll try to provide a PR for this and then we can check how it works out, there are just too many (legal) ways a mojo can write some stuff into the target folder that do not require a build, the target holds the result of the build so if the result triggers a build again, something is definitely wrong ...

I have one case that is the (e.g. `maven-compiler-plugin` ) that plugins put generated resource in the target folder, I can cover this case, but actually think that even in this case one should ignore it, because it is a direct consequence of the build-execution and any change here will be overwritten by the triggered build...

**Comment by laeubi** [comment]
The fix for this issue was gently sponsored by [ivv GmbH](https://www.ivv.de/).
