### ISSUE TITLE
Add ability to customize "Run as" menu

### ISSUE THREAD

**Issue by Kiiv** [eclipse-m2e/m2e-core#1283]
Hi,

do you think it could be possible to add the ability to customize the "Run as..." menu ? I have some customized "Maven build" configuration and it is not so easy to launch them in few click.

I have to use right click on my project, I have to go to "Run as..." then "Run configuration..." then select the configuration then launch it.
I also can add the launch configuration as a favorite in the "Run" menu of Eclipse but a click on it launches the same menu as right click "Run as" instead of launching the last executed configuration. So I still have two clicks to open the launch configurations list and select the one I wanted.

As the opposite, the External tool configuration button launches the last executed configuration as expected

**Comment by mickaelistria** [comment]
We could try to have the m2e run shortcuts smarter to show other related launch configs by default.
If you're willing to contribute it to m2e, that would be welcome: see how org.eclipse.m2e.launching/plugin.xml define launchShortcuts, add 1 shortcut that provides an implementation of org.eclipse.debug.ui.ILaunchShortcut2 which would lookup all m2e launch configuration and show all those that take the current pom or project as base directory.

**Comment by Kiiv** [comment]
Hi,

I've take a look the last WE but I did not figure it out for now :)
I'll try later but I think I will have to read documentation about plugin development and menu customization ! If you have some resources to point me out, it is welcome ;)

Regards.
