### ISSUE TITLE
Fail to upgrade from java 19 to 20 using "update maven project" dialog

### ISSUE THREAD

**Issue by eitan-rosenberg** [eclipse-m2e/m2e-core#1326]
Hello all,

My installation:

- "Eclipse IDE for Java Developers" (eclipse-java-2023-03-R-win32-x86_64.zip).

- openjdk-20_windows-x64_bin.zip.

I installed Java 20 Support  for Eclipse (https://marketplace.eclipse.org/content/java-20-support-eclipse-2023-03-427)

I am using Maven 3.9.1
 
Now it's time to upgrade some projects.

My usual procedure (from 2019) is to change the relevant POM properties and then alt-f5 to update the project.

Now the project is NOT change and the only option is to change the execution environment to JavaSE-20 manually.

**POM properties**
![2023-03-23_09-24-31](https://user-images.githubusercontent.com/48506054/227154844-946cb259-a3e2-4cf8-93d2-62a7130b58c7.png)

**alt-f5** 
![2023-03-23_11-08-05](https://user-images.githubusercontent.com/48506054/227155287-112e0f9f-215d-4c59-b8e6-462cb8d02740.png)

**Need to change the execution environment to JavaSE-20 manually.**
![2023-03-23_11-09-57](https://user-images.githubusercontent.com/48506054/227155801-4de50ace-a2a2-4c81-b98c-5046063c2cb2.png)

### I also noticed that if I run "update maven project" dialog the project goes back to java 19

**Comment by fbricon** [comment]
That one's on me 🤦: https://github.com/eclipse-m2e/m2e-core/blob/master/org.eclipse.m2e.jdt/src/org/eclipse/m2e/jdt/internal/AbstractJavaProjectConfigurator.java#L119 

I'll fix it

**Comment by laeubi** [comment]
@fbricon why not calling `org.eclipse.jdt.launching.environments.IExecutionEnvironmentsManager.getExecutionEnvironments()` instead of using that loop?

**Comment by eitan-rosenberg** [comment]
Hi,
How to get the fixed version ?

**Comment by fbricon** [comment]
Once https://ci.eclipse.org/m2e/job/m2e/job/master/569/ completes successfully, you can try the next snapshot build from https://download.eclipse.org/technology/m2e/snapshots/latest/ (check the update site contains today's bits)

**Comment by fbricon** [comment]
Java 20 support now available from https://download.eclipse.org/technology/m2e/snapshots/latest/ (

**Comment by eitan-rosenberg** [comment]
### **I think we have a liftoff !!!** 
Thank you for your efforts.
Have a nice weekend.
