### ISSUE TITLE
welcome view not auto small back when click show progress view

### ISSUE THREAD

**Issue by Yang09701194** [eclipse-m2e/m2e-core#1336]
eclipse 2023-03 (4.27.0) , start with a welcome view, when create new project > run archetype generation interactively,
stuck in 33%
https://stackoverflow.com/questions/74045604/can-not-create-a-maven-archetype-project-the-progress-bar-get-stuck-in-33

In addition, I click show progress view button in bottom right, or Window > Show View,  it doesn't appear,

![img](https://i.imgur.com/rios1ls.gif)

after a long time I find that click restore button in the upper right corner, the welcome view become half screen to right,
and project explorer, outline, progress view show in left,

I propose let welcome view auto dock to right or embed in Project Explorer title bar when do show view action. 

https://github.com/eclipse-platform/eclipse.platform/issues/379

**Comment by laeubi** [comment]
Why not simply **close** the WelcoemView?
Also why do you request interactive mode if you don't want to run it interactively?

**Comment by Yang09701194** [comment]
interactive mode is a new feature for me, I would like to experience interaction with eclipse.

In some popular ide use recent, start with welcome view keep open, when do show view action, then the view show, 

welcome view usually have some helpful link, new version update log, tutorial, news, etc,

I would keep it open and read some helpful information later

netbean
![img](https://i.imgur.com/bA8DGXv.gif)

intellij
![img](https://i.imgur.com/Kw96Md8.gif)

vscode
![img](https://i.imgur.com/9sMprTt.gif)

I support donate eclipse today
![img](https://i.imgur.com/hWvHS2t.png)

**Comment by laeubi** [comment]
> @laeubi I don't get why this was assigned to me. 

Because you suggested to move this to m2e, but I don't see any immediate action m2e can take here, so I assumed you have some kind of a plan :-)

**Comment by laeubi** [comment]
I reopened the initial report now, there is nothing m2e can do here without binding to very specific deployment setup, e.g. search for the Welcome view and minimize it or something.
