### ISSUE TITLE
Test sources folders are not always correctly added to the classpath

### ISSUE THREAD

**Issue by rnesselrath** [eclipse-m2e/m2e-core#1338]
We have a very specific configuration where we call the maven-compiler-plugin two times. First in the test-compile phase and second in the process-test-classes phase . Reason is that we generate additional source code in between that requires the already compiled test classes from the first plugin call. Additionally we have the option to skip the second plugin call. To sum up we have the following compiler plugin definition in our pom:

```
<plugin>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.8.1</version>
  <executions>
    <execution>
      <id>default-testCompile</id>
      <phase>test-compile</phase>
       <goals>
         <goal>testCompile</goal>
       </goals>
     </execution>
   <execution>
      <id>compile-generated-specs</id>
      <phase>process-test-classes</phase>
        <goals>
          <goal>testCompile</goal>
        </goals>
      <configuration>
        <skip>true</skip>
      </configuration>
 </execution>
</executions>
```

The problem is a regression introduced by ticket #1262 by @RoiSoleil.
The skip in the second execution block leads to the problem that test sources are not added to the classpath anymore.
I think changing one line in [org.eclipse.m2e.jdt/src/org/eclipse/m2e/jdt/internal/AbstractJavaProjectConfigurator.java](https://github.com/eclipse-m2e/m2e-core/pull/1263/commits/eb7084d3d0943a2b772b8af5b0081c2025751fd8#diff-d508f90e90eb0690e45ca9862654e04141c34013525229cf1fa13162347909d5) would fix this issue.

The variable isTestCompilationSkipped should only be true if all plugin calls for test compilation are skipped.

**Comment by HannesWell** [comment]
> The variable isTestCompilationSkipped should only be true if all plugin calls for test compilation are skipped.

Sounds reasonable. Can you provide a PR with your suggested fix?

**Comment by rnesselrath** [comment]
I am not familiar with eclipse plugin development and actually have now correcly configured development environment for the m2e project. The fix itself is quite trivial, I can provide a PR for it but without compile and testing it.

**Comment by HannesWell** [comment]
The [contribution guide](https://github.com/eclipse-m2e/m2e-core#%EF%B8%8F-contributing) should help to set up a development environment. We provide a Oomph setup that can automate most of the setup. Please let us know if there is anything unclear.

But even if you don't compile and test it locally the CI will do that if you create a PR, so there is no need to worry about that. :)

**Comment by GissilyWork** [comment]
I have same issue just with property maven.test.skip=true in pom.xml on version 2.2.1. 
For my case, I would like to skip some modules testing with this property in pipeline for multi-module projects, and manual testing in IDE.
