### ISSUE TITLE
Eclipse IDE crash with "JVM terminated. Exit code=1" error when incorrectly using the exec-maven-plugin

### ISSUE THREAD

**Issue by 414n** [eclipse-m2e/m2e-core#1340]
Greetings,

I stumbled upon this by accident, but I think it highlights an underlying issue in the build system when using m2e.

In one of my projects I tried to use the `exec-maven-plugin` to bind the [CreateInterface](https://dbus.freedesktop.org/doc/dbus-java/dbus-java/dbus-javase10.html) tool from the dbus-java library to the `generate-sources` build phase, in order to generate sources from a dbus XML introspection file.

While I was fiddling with it, I changed the relevant portions of the project POM to this state:

```xml
	<!-- ... --> 
	<dependencies>
		<dependency>
			<groupId>com.github.hypfvieh</groupId>
			<artifactId>dbus-java</artifactId>
			<version>2.7.5</version>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>1.6.0</version>
				<executions>
					<execution>
						<id>generate_dbus_interface</id>
						<phase>generate-sources</phase>
						<goals>
							<goal>java</goal>
						</goals>
						<configuration>
							<mainClass>org.freedesktop.dbus.bin.CreateInterface</mainClass>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
```

Obviously, this is missing the input file parameter but, before I was able to figure out how to add it in the plugin configuration, the IDE crashed with a `JVM terminated. Exit code=1` error.

Every time I tried to open the workspace containing the project, I would encounter the crash after little time.

When I finally launched the `eclipse` executable from a terminal with the additional `-debug` flag in the `eclipse.ini` file, I was able to notice that the crash occurred because the `CreateInterface` program was called (by the automatic build system in Eclipse, I assume) without arguments and it errored out, **causing the entire IDE to crash**.

This happens on Eclipse JEE 2023-03 with `m2e-2.2.1.20230307-1553` installed on a Slackware64-15.0 Linux system.

**Comment by HannesWell** [comment]
Is the snippet sufficient as a minimal reproducer?

In general the mojos are executed within the JVM of the running Eclipse instance, so if that mojo calls System.exit() this of course terminates the entire Eclipse VM.

**Comment by laeubi** [comment]
Can you please report this to the `exec-maven-plugin` then? If a maven plugin kills the JVM m2e can not really do anything.

**Comment by 414n** [comment]
> Is the snippet sufficient as a minimal reproducer?

I think so, however I prepared a self-contained project that crashes Eclipse in the same way: <https://github.com/414n/m2ecrash-example>.

> In general the mojos are executed within the JVM of the running Eclipse instance, so if that mojo calls System.exit() this of course terminates the entire Eclipse VM.

This explains why it happens only when invoking the `java` goal and not the `exec` one with an equivalent `executable` parameter that errors out.
While this is not a huge deal when running maven from the CLI, it becomes one when tearing down the whole IDE.
Is there a spec or anything that guarantees that mojos cannot do that, meaning that the `exec-maven-plugin` is a clear violator of this spec/rule?
Regarding m2e: is it possible to run maven build commands on a separate JVM, so to avoid altogether this kind of issues?

> Can you please report this to the `exec-maven-plugin` then? If a maven plugin kills the JVM m2e can not really do anything.

Yes, I will try to contact them too for the issue at hand.

BTW, it seems like it is possible to "block" a `System.exit` call by [customizing the `SecurityManager` in use](https://stackoverflow.com/a/5549778), even though this will probably stop working with Java 17+...

**Comment by laeubi** [comment]
> While this is not a huge deal when running maven from the CLI, it becomes one when tearing down the whole IDE.

Calling System.exit() except from your own application code is simply a no-go for any library and should be considered a bug.

**Comment by laeubi** [comment]
As security manager is already marked for removal and it is the exec plugin behaving wrong here I'll close this for now.
