### ISSUE TITLE
Download Artifact Sources should be forced

### ISSUE THREAD

**Issue by to-fr** [eclipse-m2e/m2e-core#1356]
In Eclipse 2023-03 eclipse.buildId=4.27.0.20230309-1200 with
M2E - Maven Integration for Eclipse        2.2.1.20230307-1553
the download of java sources doesn't always work.

Maven -> Download Artifact Sources is activated.

If I try to jump to a source with F3 from which he should actually be able to download the sources, I only get the Class File Editor with "Source Not Found".

The .m2 repository contains different ".lastUpdated" files e.g.
<artifactName>.jar
<artifactName>.pom.lastUpdated
<artifactName>-sources.jar.lastUpdated
m2e.lastUpdated.properties

The file
<artifactName>-sources.jar
is missing.

If I delete *.lastUpdated from the .m2 repository and jump into the source with F3 Eclipse can load the sources.jar.

I would like m2e to do a force-update when downloading artifact sources or javadoc.

**Comment by laeubi** [comment]
@eclipse-m2e/technology-m2e-committers anyone has concerns?
I think its reasonable to simply force the download again if javadoc/source are requested, I always find this default maven behavior annoying because I almost never wanted to wait (maybe while the build is running but not if I restart it).

**Comment by akurtakov** [comment]
Sounds good to me.

**Comment by mickaelistria** [comment]
+1

**Comment by HannesWell** [comment]
Sounds good, we just should take care that the sources are not downloaded in an infinite loop if really not accessible.
But this can probably be achived if performing one force download each time the sources are accessed but not available locally.
But I wonder if the editor is significantly slowed down if the sources are really not available?

**Comment by laeubi** [comment]
While working on this I noticed that there is a flag in m2e that controls that by default we **never** update:

![grafik](https://github.com/eclipse-m2e/m2e-core/assets/1331477/c8460c75-be5b-4139-b7be-38f31a609619)

so it might help to disable that option already.

Beside that, I think it would then be much more suitable to have something similar to "Global Checksum Policy", with "Default", "Always", "Never", Daily" ... (or whatever Aether defines here) so the user has the choice.

**Comment by olkornii** [comment]
Hello @laeubi,
just want to ask about https://github.com/eclipse-m2e/m2e-core/commit/859f94fc283f14217d082d884d786f912ec3596c and Global Update Policy.

As far as I understand, "Never" means the same as old CHECKED checkbox "Do not automatically update...", "Default" means UNCHECKED "Do not automatically update...". The others ("Always", "Daily"...) are new options, right?

**Comment by olkornii** [comment]
@laeubi I also created a discussion: https://github.com/eclipse-m2e/m2e-core/discussions/1542
Sorry for the duplication, but I'm very limited on time.
