### ISSUE TITLE
maven-targets have missing missing version ranges in some cases

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#1367]
As reported here:
https://www.eclipse.org/lists/cross-project-issues-dev/msg19659.html

in some cases package-imports are missing version ranges, a first guess would be that we:

1. need to always supply transitive dependencies to the bnd-wrapping step
2. need to wrap dependencies first

**Comment by merks** [comment]
It seems to me that one can't know in general if something actually works with an older version of something else, so a generated package import's lower bound likely has to be pessimistic, i.e., to assume it only works with the package version exported by the resolved maven dependency's exported packages.   If the maven dependency specifies a range, those might be helpful for a less pessimistic lower bound.  In any case, a pessimistic lower bound is better than no lower bound!

**Comment by laeubi** [comment]
The lower bound is always (beside some carefully manually crafted cases) the version of the package used at compile time, while the upper bound depends on if its a consumer or provider type.

**Comment by merks** [comment]
When you say "the lower bound **is**..." I guess you mean the "lower bound **will be**", i.e., future tense versus current tense, given this is not yet implemented and the lower bound is always absent.  Or maybe there are cases already where it's not absent when not in the recipe?

Also, I don't think you are suggesting that BND can know the version of the package against which an existing .class file in an existing .jar was compiled against just looking at the contents of the jar.  So I think you are saying yes, it will pessimistically assume the lower bound to be based on the version of the exported package of resolved version of the dependencies.

That's very interesting if it can know consumer versus provider type.  I didn't think of that!

**Comment by laeubi** [comment]
BND can't know from the _class-file_, but the analyzer has an additional _classpath_ it looks for that information, but this is currently not filled correctly, so BND can't know and assumes there is no version range available at all.

So to get better results, m2e must feed the analyzer with more information (that it knows from the maven model), e.g. maven dependencies declare their compiled-time dependencies, what is actually used already if you choose the include scope `compile` then you get (probably) more bundles.

> That's very interesting if it can know consumer versus provider type. I didn't think of that!

You can read about it here:

- https://docs.osgi.org/javadoc/r6/annotation/org/osgi/annotation/versioning/package-summary.html
- https://docs.osgi.org/whitepaper/semantic-versioning/060-importer-policy.html
- https://bnd.bndtools.org/chapters/170-versioning.html

These are similar to what is tried to be archived by API Tools and `@noimplement` just in a more standard way, if you like PDE supports adding such annotations already.

**Comment by merks** [comment]
Will there be documentation to describe what this does, how it does it, and how this interacts with the bnd recipe.  For example, what happens if you have three different versions of some artifact in the same target?  Does grouping in a location versus separate locations have an impact?

**Comment by laeubi** [comment]
> Will there be documentation to describe what this does, how it does it, and how this interacts with the bnd recipe. 

m2e has no recipes. A target carry some instructions for BND and these are passed as is to the Analyzer to generate a manifest, but this has not changed in any way, there is some (not full up-to-date) documentation here:

https://läubisoft.gmbh/en/articles/using-maven-artifacts-in-pde-rcp-and-tycho-builds/

I plan to move that to a help page, but haven't had time to do so, beside that we now have some nice test-cases added ba @HannesWell that demonstrate different scenarios.

> For example, what happens if you have three different versions of some artifact in the same target?

The you get three different bundles, as if you add different versions from update-sites (e.g. Orbit).

>  Does grouping in a location versus separate locations have an impact?

All items in a group share the same basic settings (e.g. if wrapping is enabled, or the dependencies to include), beside that there is no difference.

**Comment by HannesWell** [comment]
When trying this out 
https://github.com/eclipse-m2e/m2e-core/pull/1387 I noticed that besides version ranges for `Import-Packges` we now also get versions for exported packages and they have uses constraints, just with the default instructions.
Great job!

**Comment by laeubi** [comment]
There should previously also be version exports (always using the artifact version), but for sure this can produce also better meta-data on other places as well.
