### ISSUE TITLE
POM editor "Format" command is not available

### ISSUE THREAD

**Issue by JoMWal** [eclipse-m2e/m2e-core#1373]
IDE: "Eclipse for RCP and RAP Developers" **2023-06** 
    Newly installed by eclipse installer 2023-05-11) with clean workspace

Project: New (simple) Maven Project, type: pom

The pom.xml of the project is opened by default with the Maven POM editor.

But it is not possible to **format** the pom.xml.
- neither using keys CTRL-SHIFT-F
- nor using context menu 
- or using the eclipse menu bar:

![m2eScreenshot1](https://github.com/eclipse-m2e/m2e-core/assets/25712906/b57d026d-09a8-40e3-935e-a8a1993f6780)

Opening the same pom.xml file in default XML editor it **_is_** possible to format file:

![m2eScreenshot2](https://github.com/eclipse-m2e/m2e-core/assets/25712906/c5ef4c6f-a704-4f07-8e14-efc453c74b15)o

I do not know if it's related but in the second screenshot there are **_two_** "source" entries in the eclipse menu bar.

--

Additional infos - Installed feature versions:

- Wild Web Developer project	XML support using Language Server
-- 1.0.4.202304211433		org.eclipse.wildwebdeveloper.xml
- Language Server Protocol client for Eclipse IDE (Incubation)
-- 0.16.0.202303141217		org.eclipse.lsp4e
- M2E Maven POM File Editor
-- 2.0.300.20230130-0743		org.eclipse.m2e.editor
- M2E Maven POM File Editor using Wild Web Developer, LemMinX and Maven LS extension (requires Incubating components)
-- 2.0.2.20230202-1631		org.eclipse.m2e.editor.lemminx

**Comment by laeubi** [comment]
@mickaelistria can you take a look here?

**Comment by mickaelistria** [comment]
I cannot reproduce it with latest snapshots:
* Language Server Protocol client for Eclipse IDE (Incubation)	0.17.0.202308160724	org.eclipse.lsp4e	Eclipse.org
* Wild Web Developer XML tools	1.3.0.202308101707	org.eclipse.wildwebdeveloper.xml.feature.feature.group	Eclipse Wild Web Developer project
* M2E - POM Editor using LemMinX language server (includes Incubating components)	2.0.5.20230815-1219	org.eclipse.m2e.lemminx.feature.feature.group	Eclipse.org - m2e

@JoMWal please try those snapshots from the various sources (it can be a bit of a maze to get them all at once, so feel free to ask if you feel stuck).

**Comment by mickaelistria** [comment]
Thank you for testing!

**Comment by gerib** [comment]
Exactly this happens here (still or again?) with:

Linux 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux

---
Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.0-28-amd64 (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-6700 CPU @ 3.40GHz
Memory: 15,6 GiB of RAM
Graphics Processor: NV124
Manufacturer: XMG
Product Name: P7xxDM(-G)
System Version: Not Applicable

---
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)

Version: 2024-12 (4.34.0)
Build id: 20241128-0757

---
Plug-in:
03/10/2024, 18:53	Eclipse.org - m2e	M2E Maven POM File Editor using Wild Web Developer, LemMinX and Maven LS extension (requires Incubating components)	2.0.700.20240928-0605	org.eclipse.m2e.editor.lemminx

**Comment by gerib** [comment]
Same issue [pom editor: format source not working](https://github.com/eclipse-m2e/m2e-core/issues/493#issue-1101331760).
