### ISSUE TITLE
A project is losing its "enable the preview features" when using "Update Maven Project" dialog

### ISSUE THREAD

**Issue by eitan-rosenberg** [eclipse-m2e/m2e-core#1383]
Hello all,

I have a new project that use Java 20 preview feature.

I set the project option and wrote the code.

![image](https://github.com/eclipse-m2e/m2e-core/assets/48506054/f22907fa-ed55-4fe1-a3ca-f71a518f3742)

Sometimes there is a need to use "Update Maven Project" dialog.

![image](https://github.com/eclipse-m2e/m2e-core/assets/48506054/8de12d66-577c-4453-b293-2ddaf0386033)

When I do that in this project, the project is losing its "enable the preview features"

![image](https://github.com/eclipse-m2e/m2e-core/assets/48506054/25a686fb-aeaf-4657-8df2-69b4b741a12a)

Is there something **I need to add to the POM**, or is it a bug ?

I am using Maven just to get the dependencies, I am not using any plugins.

Here is the POM:

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

	<modelVersion>4.0.0</modelVersion>

	<groupId>MyKaleidoScope</groupId>
	<artifactId>MyKaleidoScope</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.target>20</maven.compiler.target>
		<maven.compiler.source>20</maven.compiler.source>
	</properties>

	<dependencies>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.12.0</version>
		</dependency>

		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-web</artifactId>
			<version>20</version>
		</dependency>

		<dependency>
			<groupId>org.jsoup</groupId>
			<artifactId>jsoup</artifactId>
			<version>1.16.1</version>
		</dependency>

		<dependency>
			<groupId>MyJava_FX_Tools.jar</groupId>
			<artifactId>MyJava_FX_Tools.jar</artifactId>
			<version>1.0</version>
			<scope>system</scope>
			<systemPath>${env.JAVA_JARS}/myJava_FX_Tools/MyJava_FX_Tools.jar</systemPath>
		</dependency>

		<dependency>
			<groupId>MyLogger.jar</groupId>
			<artifactId>MyLogger.jar</artifactId>
			<version>1.0</version>
			<scope>system</scope>
			<systemPath>${env.JAVA_JARS}/myLogger/MyLogger.jar</systemPath>
		</dependency>
		
		<dependency>
			<groupId>io.reactivex.rxjava3</groupId>
			<artifactId>rxjava</artifactId>
			<version>3.1.6</version>
		</dependency>
		
	</dependencies>
	
</project>

Thanks for any response.

**Comment by fbricon** [comment]
Maven projects need to have the `--enable-preview` flag added to the maven-compiler-plugin configuration, in their pom.xml:
```xml
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.11.0</version>
        <configuration>
          <release>20</release>
          <compilerArgs>--enable-preview</compilerArgs>
        </configuration>
      </plugin>
    </plugins>
  </build>
```

**Comment by eitan-rosenberg** [comment]
Many Thanks.
That solve the pesky problem 
The "Update Maven Project" dialog woks as expected.
Closing issue.
