### ISSUE TITLE
An internal error occured. Eclipse is broken.

### ISSUE THREAD

**Issue by wimjongman** [eclipse-m2e/m2e-core#1384]
I was updated to the 23-06 release. After restarting, I get the message you see below. This pops up on many actions like open type. It breaks Eclipse.

I did an investigation and found that the package **org.apache.maven.artifact** is exported by **org.eclipse.m2e.maven.runtime**

I have multiple versions of this plugin (see below). When investigating this runtime bundle I found that it exports the package without a version number.

I have installed M2E which seem to require the m2e.maven.runime 3.8.7 version and I have tycho.project.configurators 0.9.0.20181126 installed which pulls in m2e.mave.runtime 1.18.4 

After uninstalling m2e Eclipse works again but I think you need to version the exported packages.

### Mulitple versions of m2e mave runtime
```
g! ss maven
"Framework is launched."

id	State       Bundle
310	RESOLVED    org.eclipse.m2e.maven.runtime_3.8.701.20230209-1606
311	RESOLVED    org.eclipse.m2e.maven.runtime_1.18.3.20220227-1319
```

### Message
An internal error occurred during: "Initializing plug-in models".
loader constraint violation: loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @236f6929 wants to load interface org.apache.maven.artifact.Artifact. A different interface with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @7608474e. (org.apache.maven.artifact.Artifact is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @7608474e, parent loader 'platform')

![image](https://github.com/eclipse-m2e/m2e-core/assets/180969/1b23cb53-860c-4512-81f9-d999fed49980)

**Comment by laeubi** [comment]
> and I have tycho.project.cofigurators 0.9.0.20181126 installed which pulls in m2e.mave.runtime 1.18.4

`tycho.project.cofigurators` is outdated and its functionality is provided by m2e itself so the best is to uninstall the connector completely.

**Comment by wimjongman** [comment]
Yes, I did that. Nevertheless, the packages that er exported by m2e must be versioned.

**Comment by laeubi** [comment]
Having multiple m2e version is not really supported or will give a good state, so don't expect much things from having package versions.

**Comment by wimjongman** [comment]
Hopefully, it will stop a bundle from consuming a version of a class that it was not built to use. It is quite important, especially when we export a package we do not own (like m2e.runtime is doing).

I agree that even then, the importing plugin must specify a version constraint (I assume that is why you said, "don't expect too much"). But then, at least, we have upheld our part of the agreement.

If we are not supposed to have two m2e.runtime bundles in the target, maybe it should be a singleton bundle?

Cheers

**Comment by HannesWell** [comment]
> If we are not supposed to have two m2e.runtime bundles in the target, maybe it should be a singleton bundle?

I thought about this as well already and I don't find strong reasons not to make it a singleton.
This would also have the advantage that we could register Extensions for Extension-Points there, which move related code closer to each other.

> Yes, I did that. Nevertheless, the packages that er exported by m2e must be versioned.

I can only second Christoph's assessment, that it probably won't help much, but to be good OSGi-citizens we should actually do it and it would not be too difficult. But accidentally importing those exported-packages is difficult because they specify a mandatory attribute `provider` on imports required to them.
Nevertheless looking at the exported packages, I wonder if we should really export `com.google.inject.*`?

**Comment by laeubi** [comment]
I think singleton should only be used for UI bundles and probably for bundles providing native code that otherwise conflicts.

I'm also not sure if package-import would help here, as the error is shown as "Initializing plug-in models" what is somewhat strange so maybe you can check if there is a stack-trace in the error log?

**Comment by wimjongman** [comment]
> I can only second Christoph's assessment, that it probably won't help much, 

I need some clarification on the statements that it does not help much: If the Tycho tooling was to depend on version 1.18.3 of package org.apache.maven.artifact, then Tycho tooling would never consume the newer package exported from 3.8.701 so this error would not have happened.

Or do you mean something else?

> I think singleton should only be used for UI bundles and probably for bundles providing native code that otherwise conflicts.

Yes, but you said earlier that multiple m2 versions are not supported. 

> 
> I'm also not sure if package-import would help here, as the error is shown as "Initializing plug-in models" what is somewhat strange 

Ah, so there is no package import on the Tycho tooling? Then it binds to a bundle with no version constraints? Maybe that is what you mean when you say that adding versions to the package will not help.

> so maybe you can check if there is a stack trace in the error log?

Sorry, I have nothing relevant anymore in the error log. Do you want me to try to rebuild back to the faulty situation?


Cheers

**Comment by laeubi** [comment]
m2e is more than packages, it provides for example UI, reading configuration files, executing build inside the IDE and so on, so having two competing toolings is likely not what one wants (I think you will get similar issues if two JDT versions are installed and both try to handle your project source compiles).

So if we now assume everything is perfectly versioned and you get into the situation that two different versions of m2e are running in your IDE, you will most probably see other issues, so in the end the result is that you want to only have one maven tolling per IDE :-)

> Do you want me to try to rebuild back to the faulty situation?

If you think it is worth the effort we can try to further analyze this, but the bottom line is that having m2e 1.x + m2e 2.x is likely not a useful configuration at all, so the question is if we can really improve/fix anything here compared to suggesting to uninstall old versions pulled in by old connectors...

**Comment by wimjongman** [comment]
Ok, sure. I agree. There is nothing we can do about the current situation anyway. 

The thing that prompted me to report it is that a normal user will be in a bad shape. It happened to me just by upgrading to 23-06.

When you get around to it, I would highly recommend versioning the packages that you export. I speak from experience.

**Comment by wimjongman** [comment]
I need clarification on what you mean by it does not help to version the export. 

You are building the maven.runtime bundle that is including your dependencies as jars and exporting this from your bundle. For example you export _**org.apache.maven.artifact;provider=m2e;mandatory:=provider**_

If you do not include a version how can you avoid that I do not import your package when I actually want a lower API level?


![image](https://github.com/eclipse-m2e/m2e-core/assets/180969/b80888c2-9ea6-4002-a40b-9e59bde92b8c)

**Comment by laeubi** [comment]
If we just add an export then still the consumer needs to be adjusted to use that version.
Currently plugins usually use a requirement on the m2e itself (e.g. m2e.core) and then you get wired the correct imports already so without known where the error originates its a bit hard to guess (unless you want to use m2e.maven.runtime alone what is quite unlikely).

So the usual chain is that I have `Connector` > Imports `m2e.core` (e.g. 1.x or 2.x) > Imports  `m2e.runtime` but here something else seem to interfere (PDE State).

**Comment by wimjongman** [comment]
Ok, I see. 

You should also consider that people could be importing any of the jars you carry without them knowing about m2e. Given someone importing a package, OSGi can possibly wire your bundle in. Or is this handled by the _**provider=m2e;mandatory:=provider**_ attributes?
