### ISSUE TITLE
Maven Update to Java 20 not possible

### ISSUE THREAD

**Issue by RalfNaujokat** [eclipse-m2e/m2e-core#1389]
Hi,

i have opened an eclipse bug, but was told this issue belongs to here.
Can someone please have a look?

https://bugs.eclipse.org/bugs/show_bug.cgi?id=581962

greetings
Ralf

**Comment by akurtakov** [comment]
I don't think anything prevents this from happening right now. Release m2e and submit it to simrel.

**Comment by fbricon** [comment]
Deadline for contributing m2e to simrel is tomorrow (M3+2: Tue 23/05) as per https://wiki.eclipse.org/Category:SimRel-2023-06

**Comment by laeubi** [comment]
As far as I know @HannesWell has planned to do a release, but contribution to simrel is not really mandatory for m2e, anyone can install the latest version from the update-site ... just in case.

**Comment by laeubi** [comment]
There is also one reported installation problem we should address:
- https://github.com/eclipse-m2e/m2e-core/issues/1390

And i think the following PR should be merged:
- https://github.com/eclipse-m2e/m2e-core/pull/1358

**Comment by HannesWell** [comment]
> As far as I know @HannesWell has planned to do a release

Yes I will perform a release soon, actually I intended it for the middle of the week. But if the shedule requires, I will do it tomorrow evening.
Then I will postpone new features to the next release and will focus on bug fixes and pending PRs until tomorrow.

**Comment by HannesWell** [comment]
Duplicate of #1326

**Comment by HannesWell** [comment]
M2E 2.3.0 is released and available at https://download.eclipse.org/technology/m2e/releases/2.3.0/ which also contains the fix for this issue.

**Comment by RalfNaujokat** [comment]
Just installed the update into Eclipse 2023-06-M2,
works as expected now. Good job, thank you!

greetings
Ralf
