### ISSUE TITLE
Error in log Circular reference detected trying to get service {org.eclipse.m2e.core.project.IMavenProjectChangedListener

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#1405]
I see the following error in my log

bundle org.apache.felix.scr:2.2.6 (555) Circular reference detected trying to get service {org.eclipse.m2e.core.project.IMavenProjectChangedListener}={service.id=223, service.bundleid=691, service.scope=bundle, osgi.ds.satisfying.condition.target=(osgi.condition.id=true), component.name=org.eclipse.m2e.core.internal.project.WorkspaceStateWriter, component.id=44}
 stack of references: ServiceReference: {org.eclipse.m2e.core.project.IMavenProjectChangedListener}={service.id=223, service.bundleid=691, service.scope=bundle, osgi.ds.satisfying.condition.target=(osgi.condition.id=true), component.name=org.eclipse.m2e.core.internal.project.WorkspaceStateWriter, component.id=44}
ServiceReference: {org.eclipse.m2e.core.project.IMavenProjectRegistry}={service.id=216, service.bundleid=691, service.scope=bundle, osgi.ds.satisfying.condition.target=(osgi.condition.id=true), component.name=org.eclipse.m2e.core.internal.project.registry.MavenProjectManager, component.id=47}
    Dependency: DependencyManager: Component [Component: org.eclipse.m2e.core.embedder.MavenModelManager (33)] reference [projectManager]

**Comment by laeubi** [comment]
> I see the following error in my log

Please provide what functional error you see (e.g. what is not working, missing or not behave as expected)

**Comment by vogella** [comment]
> > I see the following error in my log
> 
> Please provide what **functional** error you see (e.g. what is not working, missing or not behave as expected)

I only see this logged as error during startup, I did not even use M2E.

**Comment by vogella** [comment]
I still this at a client also in the error log with   M2E - Maven Integration for Eclipse	2.4.100.20230827-1557	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e

```
bundle org.apache.felix.scr:2.2.6 (45) Circular reference detected trying to get service {org.eclipse.m2e.core.project.IMavenProjectChangedListener}={service.id=222, service.bundleid=368, service.scope=bundle, osgi.ds.satisfying.condition.target=(osgi.condition.id=true), component.name=org.eclipse.m2e.core.internal.project.WorkspaceStateWriter, component.id=34}
 stack of references: ServiceReference: {org.eclipse.m2e.core.project.IMavenProjectChangedListener}={service.id=222, service.bundleid=368, service.scope=bundle, osgi.ds.satisfying.condition.target=(osgi.condition.id=true), component.name=org.eclipse.m2e.core.internal.project.WorkspaceStateWriter, component.id=34}
    Dependency: DependencyManager: Component [Component: org.eclipse.m2e.core.internal.project.registry.MavenProjectManager (37)] reference [MavenProjectChangedListener]
ServiceReference: {org.eclipse.m2e.core.project.IMavenProjectRegistry}={service.id=215, service.bundleid=368, service.scope=bundle, osgi.ds.satisfying.condition.target=(osgi.condition.id=true), component.name=org.eclipse.m2e.core.internal.project.registry.MavenProjectManager, component.id=37}
    Dependency: DependencyManager: Component [Component: org.eclipse.m2e.core.embedder.MavenModelManager (22)] reference [projectManager]
    Dependency: DependencyManager: Component [Component: org.eclipse.m2e.core.embedder.MavenModelManager (22)] reference [projectManager]
ServiceReference: {org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager}={service.id=213, service.bundleid=368, service.scope=bundle, osgi.ds.satisfying.condition.target=(osgi.condition.id=true), component.name=org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager, component.id=39}

```

**Comment by vogella** [comment]
It does not seem to make a functional impact but the exception is re-created twice during restart.

**Comment by jonahgraham** [comment]
I got this error too when doing upgrade tests on the Eclipse IDE for RCP and RAP developers from 2023-09 to 2023-12 M1. On some simple experiments I cannot see this error when running 2022-12 M1 or 2023-09 on its own, it was only after upgrading that the problem happens. Doing a second try with the upgrade showed the same error.

Running Eclipse with `-clean` resolves the error.

**Comment by vogella** [comment]
Thanks for the tip @jonahgraham. I now see The -clean (osgi.clean) option was not successful. Unable to clean the storage area: C:\dev\Eclipse\eclipse-2023-12-M1\eclipse\configuration\org.eclipse.osgi but the error described here is gone. ;-)

**Comment by jukzi** [comment]
> It does not seem to make a functional impact but the exception is re-created twice during restart.

happend to me too.

**Comment by jantje** [comment]
Happens for me with each test run (Sloeber) and clean does not fix it.

**Comment by jukzi** [comment]
happens again eclipse.buildId=4.35.0.I20241218-0320
```
bundle org.apache.felix.scr:2.2.12 (72) Circular reference detected trying to get service {org.eclipse.m2e.core.project.IMavenProjectChangedListener}={service.id=271, service.bundleid=697, service.scope=bundle, osgi.ds.satisfying.condition.target=(osgi.condition.id=true), component.name=org.eclipse.m2e.core.internal.project.WorkspaceStateWriter, component.id=48}
 stack of references: ServiceReference: {org.eclipse.m2e.core.project.IMavenProjectChangedListener}={service.id=271, service.bundleid=697, service.scope=bundle, osgi.ds.satisfying.condition.target=(osgi.condition.id=true), component.name=org.eclipse.m2e.core.internal.project.WorkspaceStateWriter, component.id=48}
    Dependency: DependencyManager: Component [Component: org.eclipse.m2e.core.internal.project.registry.MavenProjectManager (51)] reference [MavenProjectChangedListener]
ServiceReference: {org.eclipse.m2e.core.project.IMavenProjectRegistry}={service.id=264, service.bundleid=697, service.scope=bundle, osgi.ds.satisfying.condition.target=(osgi.condition.id=true), component.name=org.eclipse.m2e.core.internal.project.registry.MavenProjectManager, component.id=51}
    Dependency: DependencyManager: Component [Component: org.eclipse.m2e.core.embedder.MavenModelManager (36)] reference [projectManager]
    Dependency: DependencyManager: Component [Component: org.eclipse.m2e.core.embedder.MavenModelManager (36)] reference [projectManager]
ServiceReference: {org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager}={service.id=262, service.bundleid=697, service.scope=bundle, osgi.ds.satisfying.condition.target=(osgi.condition.id=true), component.name=org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager, component.id=53}

```
