### ISSUE TITLE
The latest SNAPSHOT site is inconsistent/incomplete

### ISSUE THREAD

**Issue by merks** [eclipse-m2e/m2e-core#1420]
The current snapshot update site https://download.eclipse.org/technology/m2e/snapshots/latest is incomplete. 

Resolution fails:

>   ERROR: org.eclipse.equinox.p2.director code=0 Software being installed: artificial_root 1.0.0.v1686632537215
>   ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: M2E Maven Archetype Common 3.3.0.20230605-1716 (org.eclipse.m2e.archetype.common 3.3.0.20230605-1716) requires 'osgi.bundle; org.eclipse.m2e.archetype.jdom2 0.0.0' but it could not be found
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: artificial_root 1.0.0.v1686632537215
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.m2e.pde.feature.feature.group 0.0.0
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: M2E Maven Integration for Eclipse UI 2.0.6.20230612-1724 (org.eclipse.m2e.core.ui 2.0.6.20230612-1724)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: osgi.bundle; org.eclipse.m2e.archetype.common [3.2.1,4.0.0)
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: M2E - PDE Integration 2.2.100.20230523-1752 (org.eclipse.m2e.pde.feature.feature.group 2.2.100.20230523-1752)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: org.eclipse.equinox.p2.iu; org.eclipse.m2e.pde.ui [2.0.300.20230522-0006,2.0.300.20230522-0006]
>   ERROR: org.eclipse.equinox.p2.director code=1 Cannot satisfy dependency:
>     ERROR: org.eclipse.equinox.p2.director code=0 From: M2E PDE Integration UI 2.0.300.20230522-0006 (org.eclipse.m2e.pde.ui 2.0.300.20230522-0006)
>     ERROR: org.eclipse.equinox.p2.director code=0 To: osgi.bundle; org.eclipse.m2e.core.ui 2.0.3

Looking at the metadata (content.jar) indeed org.eclipse.m2e.archetype.common requires org.eclipse.m2e.archetype.jdom2

>     <unit id='org.eclipse.m2e.archetype.common' version='3.3.0.20230605-1716' singleton='false'>
>       <update id='org.eclipse.m2e.archetype.common' range='[0.0.0,3.3.0.20230605-1716)' severity='0'/>
>       <properties size='7'>
>         <property name='org.eclipse.equinox.p2.name' value='M2E Maven Archetype Common'/>
>         <property name='org.eclipse.equinox.p2.description' value='Maven Integration for Eclipse provides tight integration for Maven into the IDE'/>
>         <property name='org.eclipse.equinox.p2.provider' value='Eclipse.org - m2e'/>
>         <property name='maven-groupId' value='org.eclipse.m2e'/>
>         <property name='maven-artifactId' value='org.eclipse.m2e.archetype.common'/>
>         <property name='maven-version' value='3.3.0.20230605-1716'/>
>         <property name='maven-type' value='eclipse-plugin'/>
>       </properties>
>       <provides size='5'>
>         <provided namespace='org.eclipse.equinox.p2.iu' name='org.eclipse.m2e.archetype.common' version='3.3.0.20230605-1716'/>
>         <provided namespace='osgi.bundle' name='org.eclipse.m2e.archetype.common' version='3.3.0.20230605-1716'/>
>         <provided namespace='java.package' name='META-INF.plexus' version='0.0.0'/>
>         <provided namespace='osgi.identity' name='org.eclipse.m2e.archetype.common' version='3.3.0.20230605-1716'>
>           <properties size='1'>
>             <property name='type' value='osgi.bundle'/>
>           </properties>
>         </provided>
>         <provided namespace='org.eclipse.equinox.p2.eclipse.type' name='bundle' version='1.0.0'/>
>       </provides>
>       <requires size='8'>
>         <required namespace='osgi.bundle' name='org.eclipse.m2e.archetype.jdom2' range='0.0.0'/>   <--------------------------------
>         <required namespace='osgi.bundle' name='org.eclipse.m2e.maven.runtime' range='[3.0.0,4.0.0)'/>
>         <required namespace='osgi.bundle' name='org.eclipse.m2e.archetype.maven-artifact-transfer' range='0.0.0'/>
>         <required namespace='java.package' name='org.slf4j' range='[1.7.0,3.0.0)' optional='true' greedy='false'/>
>         <required namespace='osgi.bundle' name='org.eclipse.m2e.archetype.archetype-common' range='0.0.0'/>
>         <required namespace='osgi.bundle' name='com.ibm.icu' range='0.0.0'/>
>         <required namespace='osgi.bundle' name='org.eclipse.m2e.archetype.archetype-descriptor' range='0.0.0'/>
>         <required namespace='osgi.bundle' name='org.eclipse.m2e.archetype.archetype-catalog' range='0.0.0'/>
>       </requires>

but there is no such IU defined by the site.

**Comment by laeubi** [comment]
> Looking at the metadata (content.jar) indeed org.eclipse.m2e.archetype.common requires org.eclipse.m2e.archetype.jdom2

Thats strange as I would assume that in this case dependencies are pulled in when building the site, I have to check why this is not considered :-\

**Comment by HannesWell** [comment]
> > Looking at the metadata (content.jar) indeed org.eclipse.m2e.archetype.common requires org.eclipse.m2e.archetype.jdom2
> 
> Thats strange as I would assume that in this case dependencies are pulled in when building the site, I have to check why this is not considered :-\

They are not, I started it while ago but have not completed that work (I would like to avoid just mirroring many deps.

I suggest to generate a Feature for the archetype bundles and include that feature in the m2e feature, which will include them.

**Comment by laeubi** [comment]
I really like to avoid a feature here, this is not a "feature" it is a direct requirement of the bundle and therefore should be included.

**Comment by laeubi** [comment]
I now created 
- https://github.com/eclipse-m2e/m2e-core/pull/1423
to explicitly include the missing items
