### ISSUE TITLE
Please don't delete old releases

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-m2e/m2e-core#1444]
I was just going to modify an Oomph setup of an older maintenance version of a product in an attempt of including a 1.x release of m2e, just to find there are no such releases anymore on the m2e update site. While it is still possible to find them in the eclipse release update sites via the Oomph repository explorer, that's quite cumbersome (and the average user doesn't know how to do that).
So please don't delete old releases from the update site. There are people who may need them.

**Comment by mickaelistria** [comment]
Eclipse Foundation infra requests that we clean the download area from time to time, moving outdated stuff to archive.eclipse.org , so they're at https://archive.eclipse.org/technology/m2e/releases/ .
Feel free to submit a PR in the README mentioning that older releases can be found there.

**Comment by HannesWell** [comment]
> Eclipse Foundation infra requests that we clean the download area from time to time, moving outdated stuff to archive.eclipse.org , so they're at https://archive.eclipse.org/technology/m2e/releases/ .

I want to add that all download.eclipse.org URL pointing to now archived p2-preos are redirected to the archive location.
So for example https://download.eclipse.org/technology/m2e/releases/1.20.0/ still can be used in a Target-Platform although the 1.20.0 release is archived.
And personally I would just continue using the original URL and would not worry about the archive.

**Comment by Bananeweizen** [comment]
Thanks to both of you. I was not aware of that redirection, because I had only used /releases up to now, not a specific version. Works like a charm.
Thanks again.
