### ISSUE TITLE
Multipage POM editor: select enclosing element not working

### ISSUE THREAD

**Issue by vrubezhny** [eclipse-m2e/m2e-core#1502]
The original issue: https://github.com/eclipse-m2e/m2e-core/issues/1315

Not sure if this is the right place to report it -- if not please advise me to a more appropriate github project.

The regular XML-Editor has the handy feature of "select enclosing element":

Alt-Shift-Up: expands the current selection, e.g. (| representing the cursor, [ ] a range selection):
`<maven.compiler.source>1|.8</maven.compiler.source> --> <maven.compiler.source>[1.8]</maven.compiler.source>` --> `[<maven.compiler.source>1.8</maven.compiler.source>]`
Alt-Shift-Down: does the opposite (restore last selection):
`[<maven.compiler.source>1.8</maven.compiler.source>]` --> `<maven.compiler.source>[1.8]</maven.compiler.source>` --> `<maven.compiler.source>1|.8</maven.compiler.source>`

This does not work in the [MULTIPAGE] pom editor.

Note: The issue was fixed quite a long ago on LSP4E side and works when a POM file is opened with Generic Text editor (That is M2E-Core Editor Lemminx), but still doesn't work when using Maven POM Editor (multipage)

**Comment by HannesWell** [comment]
I belive that you and @mickaelistria are best familiar with the Editors.
If the error is not in m2e, LemMinX would probably the only place left.

**Comment by dstango** [comment]
> I belive that you and @mickaelistria are best familiar with the Editors.
> If the error is not in m2e, LemMinX would probably the only place left.

As I was the original reporter of the issue I just want to point out we might be running in circles: https://github.com/eclipse-m2e/m2e-core/issues/1315#issuecomment-1473678960 ...
But I hope we can break the circle! :-)

**Comment by vrubezhny** [comment]
@HannesWell The is reproducible only in Multipage Maven POM Editor.
It's definitely not reproducible in WWD, nor in M2E-Core Editor Lemminx (uses Generic Text Editor).

Probably some LSP4E functionality doesn't support Multipage editors so, it can be that an upstream issue is to be reported to LSP4E.

**Comment by HannesWell** [comment]
> Probably some LSP4E functionality doesn't support Multipage editors so, it can be that an upstream issue is to be reported to LSP4E.

Could be possible, but unfortunately I cannot help you here since I'm Not really familiar with the editors and language-servers.
