### ISSUE TITLE
PKI Implementations

### ISSUE THREAD

**Issue by JavaJoeS** [eclipse-m2e/m2e-core#1539]
### Discussed in https://github.com/eclipse-m2e/m2e-core/discussions/1538

<div type='discussions-op-text'>

<sup>Originally posted by **JavaJoeS** August 31, 2023</sup>
Why are there no hooks or supporting packages for any PKI, PKCS12, and more specifically PKCS11?
Can I do anything to assist in developing hooks or service implementations to support PKI?</div>

**Comment by JavaJoeS** [comment]
What code would I modify if I were implementing? To start 4 packages
need impl.

    org.eclipse.m2e.maven.runtime
    org.eclipse.m2e.launching
    org.eclipse.m2e.core
    org.eclipse.m2e.core.ui

**Comment by laeubi** [comment]
Please don't open redundant issues here. It is completely unclear what "PKI" should be implemented and what problem it should solve, please provide at laest one example that shows missing features.
