### ISSUE TITLE
Run Configuration do not work after update to 4.19.0 version

### ISSUE THREAD

**Issue by lucapreziati** [eclipse-m2e/m2e-core#154]
After the upgrade to version 4.19.0
Version: 2021-03 (4.19.0)
Build id: 20210312-0638 the Run Configuration List for Java Application is empty and it is impossible set Environment variable for starting microservice as Java Application using button Run Configuration as showed in screenshot.

If i try to add manually any Configuration do not work: nothing happen and no error in eclipse console appear. 
![eclipsebug](https://user-images.githubusercontent.com/3452569/113435130-8056db80-93e2-11eb-910a-6836fbb39add.png)

**Comment by mickaelistria** [comment]
Are you talking about the Maven run configurations or other ones.
If you could provide more details about how to reproduce this issue, it would be welcome.

**Comment by lucapreziati** [comment]
I don't know how reproduce. I had a simple SpringBoot project that i start as java application, after the upgrade under java application the element of the list, for example the project 1,2,5 and 6 are not available in Run configuration menu under Java Application. So any java application are anymore configurable with environment variable.

**Comment by mickaelistria** [comment]
As far as I understand from your comment, you're talking about the "Java Application" Run Configuraitions. Those aren't provided by m2e. Please open a bug to https://bugs.eclipse.org/bugs/enter_bug.cgi?product=JDT&component=Debug with minimal steps to reproduce the issue.
