### ISSUE TITLE
"Update Project" fails in Eclipse due to removed methods in ProjectConfigurationRequest

### ISSUE THREAD

**Issue by dnapoletanoexp** [eclipse-m2e/m2e-core#1556]
This commit:

_Convert 'plain data carrier' classes to records (Jun 29, 2022)_

on _ProjectConfigurationRequest_ class has removed a method (_getProject_)  which is still needed for at least two libraries using it, as reported here:

https://bugs.eclipse.org/bugs/show_bug.cgi?id=582182

This modification makes Eclipse "Maven - Update Project" command to fail if libraries like those ones are installed.

Possible solutions are re-adding the missing methods in the class, or reverting it to the previous commit.

**Comment by laeubi** [comment]
You need to update jbostools to support the latest m2e version.

**Comment by HannesWell** [comment]
That https://github.com/eclipse-m2e/m2e-core/pull/760 was a breaking change as part of m2e 2 was also discussed in https://github.com/eclipse-m2e/m2e-core/issues/918 already.
