### ISSUE TITLE
"Extract all values..." uses wrong key on identical values

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-m2e/m2e-core#1559]
This is part of the improvements video: https://www.youtube.com/watch?v=bUnx9_jF-ig

Note the identical version numbers before the refactoring:
![grafik](https://github.com/eclipse-m2e/m2e-core/assets/406876/d1f88e67-4e4a-47fe-9a20-8e92bc474761)
After the refactoring both version numbers wrongly use the same key "...failsafe...", even on the surefire plugin:
![grafik](https://github.com/eclipse-m2e/m2e-core/assets/406876/a104badf-21fa-4fd7-96eb-58ef9195c02f)

**Comment by laeubi** [comment]
@Bananeweizen this is a feature of [lemminx-maven](https://github.com/eclipse/lemminx-maven/) I'm not sure if it is intentional but you might get better feeedback there.

**Comment by mickaelistria** [comment]
I think it's fine to see such behavior for "Extract all values..." (as opposed to "Extract property" which would only take the current selection). Some typical cases for this feature are JUnit, Spring, Maven itself which often comes with various dependencies to explicit, all using the same version. This feature is meant to cover such case and to introduce 1 property to rule them all.

**Comment by Bananeweizen** [comment]
Okay, and thanks @laeubi for the clarification. I was already wondering when I created the issue if I'm in the right project, but I didn't remember lemminx that moment.
