### ISSUE TITLE
Maven Preferences are overwritten on startup.

### ISSUE THREAD

**Issue by brett-smith** [eclipse-m2e/m2e-core#1572]
Any changes that are made in Preferences -> Maven are persisted to `[workspace]/.metadata/.plugins/org.eclipse.core.runtime/.settings/org.eclipse.m2e.core.prefs`, but after a restart, this file is totally wiped out and replaced with the defaults.

I was surprised to find that even making the file read-only did nothing. Eclipse simply deletes the file anyway and replaces it with the defaults again. I can't find any other work around other that changing settings every time you start up.

It always defaults to this ...

![image](https://github.com/eclipse-m2e/m2e-core/assets/10938912/cac4ea51-21ce-467f-86c5-4c703b9308d8)

with this content in the prefs file. 

```
eclipse.m2.WorkspacelifecycleMappingsLocation=/home/me/Workspaces/HS/.metadata/.plugins/org.eclipse.m2e.core/lifecycle-mapping-metadata.xml
eclipse.m2.debugOutput=true
eclipse.m2.defaultRuntime=maven
eclipse.m2.downloadJavadoc=true
eclipse.m2.hideFoldersOfNestedProjects=false
eclipse.m2.runtimes=maven
eclipse.m2.runtimesNodes/maven/location=/usr/share/maven
eclipse.m2.runtimesNodes/maven/type=EXTERNAL
eclipse.m2.unkownMojoExecutionAction=execute
eclipse.m2.warn_incomplete_mapping=true
eclipse.preferences.version=1
```

This is on Linux Mint 21.2 Cinnamon 64 Bit. 

Eclipse versions ..

```
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)

Version: 2023-09 (4.29.0)
Build id: 20230907-1323

Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	2.4.100.20230827-1557	org.eclipse.m2e.feature
Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	2.2.200.20230820-0922	org.eclipse.m2e.pde.feature
```

I don't think the version numbers are going to make much difference. I've been seeing this happen for years, but the "Debug Output" option being effectively stuck permanently on, and "Hide folders of physically nested modules" being stuck effectively permanently off have finally  driven me crazy.

Whether a fresh install or an upgrade, a new workspace or an existing one, the same problem exists. This is nothing in  `.log` either.

**Comment by mickaelistria** [comment]
I don't think the issue comes from m2e, I suspect it involves Oomph preference recorder.
To verify it: please install the Eclipse SDK (so it doesn't contain Oomph), then install m2e in it; and try reproducing. If you can't then it means the culprit is elsewhere.

**Comment by brett-smith** [comment]
Thanks for the fast response, that does indeed appear to be it. I downloaded "Eclipse IDE for Java Developers" and that works fine.

I have never intentionally used this Preferences Recorder and all the settings for that appear to be at default. The only action that is not disabled is "Iniitialize". 

Anyway, thanks again, it's obviously nothing to do with m2e itself.

**Comment by HannesWell** [comment]
Glad you found a solution.
Therefore closing this.
