### ISSUE TITLE
clarification of current lifecyle mapping warnings and Antrun plugin

### ISSUE THREAD

**Issue by garretwilson** [eclipse-m2e/m2e-core#1577]
I have a clarification question. For who knows how long, my "root" parent POM has been using the `org.eclipse.m2e:lifecycle-mapping` workaround to prevent a warning in the IDE about the Maven Antrun Plugin `org.apache.maven.plugins:maven-antrun-plugin` not being recognized.

I went in to switch to the "new" (~2017) approach for [specifying lifecycle mapping metadata using XML declarations](https://eclipse.dev/m2e/documentation/release-notes-17.html#new-syntax-for-specifying-lifecycle-mapping-metadata), which I just now discovered. But when I removed the `org.apache.maven.plugins:maven-antrun-plugin`, Eclipse EE 2023-09 gave me no warnings whatsoever. I checked and I have no IDE-level mappings related to the Maven Antrun Plugins. I have several executions of Antrun in profiles, but one is not in a profile, mapped to `<phase>generate-resources</phase>`.

Does m2e now support the Maven Antrun Plugin? Or did m2e abandon warnings for unrecognized plugins? I'm trying to figure out why I went into my POM to improve a workaround, only to find a workaround is no longer needed.

**Comment by laeubi** [comment]
> Does m2e now support the Maven Antrun Plugin?

not specifically.

> Or did m2e abandon warnings for unrecognized plugins? 

m2e default is to execute every mojo if it is unknown by default because users most likely added them for a purpose.

> I'm trying to figure out why I went into my POM to improve a workaround, only to find a workaround is no longer needed.

You should still see a little info icon where you can disable the mojo if you don't like it to be executed.

**Comment by garretwilson** [comment]
Thanks for the quick reply.

I actually found the "Plugin execution not covered by lifecycle configuration" under "Infos" (not "warnings") in the "Problems" tab. There are no warnings or any indication when editing the `pom.xml` itself.

I thought sure that years ago there would be a warning in the file, with some option for me to add the workaround, but maybe I'm mistaken. At least I thought that there was something that jumped out in my face, not hidden under "Infos". (This is not a complaint; I'm just trying to ascertain if m2e behavior has changed or if I'm not remembering correctly what happened.)

**Comment by garretwilson** [comment]
I just checked, and in **Window > Preferences > Maven > Errors/Warnings**, "Plugin execution not covered by lifecycle configuration" is still set to "Warning". But I see no warning anywhere—just the note under "Infos" (which seems to be a separate section than "Warnings") in the "Problems" tab.

**Comment by laeubi** [comment]
It depends on how you define "workaround", previously there was even an `ERROR`, we then degraded it to `WARNING` but still it was only possible to **disable the executions**, what is very inconvenient.
So now it is only an `INFO` (mainly to allow quickfixes) where by default we execute the Mojo and there is the option to disable it if its undesired (e.g. especially `ant-run` could be executing lengthy tasks).

**Comment by garretwilson** [comment]
> It depends on how you define "workaround"

I was just referring to the way to disable the warning when I said "workaround" I wasn't trying to quibble about whether it should be called a "workaround".

> … previously there was even an `ERROR`, we then degraded it to `WARNING` …So now it is only an `INFO`

Ah, so if I understand you correctly, my memory was correct in remembering that Eclipse gave some sort of more explicit error/warning, but now this has been moved to a note under "Infos"—so the current behavior is somewhat different than it used to be.

That's fine. I was just wanting to make sure I wasn't missing something when improving the way I disable the error/warning/info/whatever.

I'll note that if it is now just an "info", then that seems to be in conflict with the **Window > Preferences > Maven > Errors/Warnings** setting indicating that it is a "warning". That doesn't bother me so much, but it does sound like a bug of sorts.

**Comment by garretwilson** [comment]
Lastly since we're discussing this (and thank you for the discussion), I read at [OSSRH-56004](https://issues.sonatype.org/browse/OSSRH-56004) that using the new-style XML processing instruction such as `<?m2e ignore?>` will break publishing to Maven Central. Have you heard of this. and do you know if it has been fixed? If so, it would be show-stopper for use of the XML processing instructions.

**Comment by laeubi** [comment]
I'm not aware of this, if it does, its really a pitty but nothing much m2e can solve, maybe using [flatten-maven-plugin](https://www.mojohaus.org/flatten-maven-plugin/plugin-info.html) can help to remove these before publishing to central or enough people complain so it is fixed at sonatype...

**Comment by garretwilson** [comment]
> I'm not aware of this, if it does, its really a pitty …

I agree completely!

Sonatype is working on a new publishing workflow. They have turned off access to [NEXUS-18196](https://issues.sonatype.org/browse/NEXUS-18196), which was apparently the ticket tracking that bug, so it's not possible to see whether the issue was fixed. I have reached out to Sonatype for clarification. I'll be happy to report back when I find out something.

In the meantime I'll close this ticket. The gist of the ticket was whether Eclipse changed its reporting of unrecognized plugins, and you answered that it has—thanks for the clarification.

I'll raise the "Window > Preferences > Maven > Errors/Warnings" bug as a separate ticket.

**Comment by laeubi** [comment]
> that seems to be in conflict with the **Window > Preferences > Maven > Errors/Warnings** setting indicating that it is a "warning"

Actually its a bit more complex (because the way how m2 works internally), you can configure here what should happen for the "default" case what is set to execute:

![grafik](https://github.com/eclipse-m2e/m2e-core/assets/1331477/a19eda77-f9d5-4ff0-81cb-6bf0bc4842f8)

In that case *technically* everything **is covered** so the mentioned setting do not apply. if you choose "warning" or "error" these are effectively generate a "uncovered execution" what the can be controlled by the above setting.

**Comment by garretwilson** [comment]
It might best to move this discussion to #1578, which I just opened. I'll move the response I was about to make over there.
