### ISSUE TITLE
master build issue with signatures

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-m2e/m2e-core#1590]
Latest builds from https://ci.eclipse.org/m2e/job/m2e/job/master are failing with 
```
22:54:31  [INFO] --- tycho-p2-repository:4.0.3:verify-repository (verify-repository-consistency) @ org.eclipse.m2e.repository ---
22:54:31  [WARNING] Parameter 'qualifier' (user property 'buildQualifier') is read-only, must not be used in configuration
22:54:31  [INFO] Verifying p2 repositories in /home/jenkins/agent/workspace/m2e_master/org.eclipse.m2e.repository/target/repository
22:54:32  [ERROR] Problems downloading artifact: osgi.bundle,org.eclipse.m2e.workspace.cli.source,0.3.1.
22:54:32  [ERROR]   File has invalid content:/tmp/signatureFile3178499355654009440.jar
22:54:32  [ERROR]     Invalid content:META-INF/ECLIPSE_.RSA: META-INF/ECLIPSE_.RSA
22:54:32  org.eclipse.osgi.signedcontent.InvalidContentException: META-INF/ECLIPSE_.RSA
22:54:32      at org.eclipse.osgi.internal.signedcontent.SignedContentFromBundleFile.getSignedEntries (SignedContentFromBundleFile.java:244)
22:54:32      at org.eclipse.osgi.internal.signedcontent.SignedContentFromBundleFile.<init> (SignedContentFromBundleFile.java:193)
22:54:32      at org.eclipse.osgi.internal.signedcontent.SignedBundleHook.getSignedContent (SignedBundleHook.java:169)
22:54:32      at org.eclipse.equinox.internal.p2.artifact.repository.SignatureVerifier.verifyContent (SignatureVerifier.java:84)
22:54:32      at org.eclipse.equinox.internal.p2.artifact.repository.SignatureVerifier.verify (SignatureVerifier.java:66)
22:54:32      at org.eclipse.equinox.internal.p2.artifact.repository.SignatureVerifier.close (SignatureVerifier.java:115)
```
preventing m2e-core snapshots from being published, and tested.

**Comment by mickaelistria** [comment]
Locally I see
```
$ jarsigner -verify ~/apps/eclipse-SDK/plugins/org.eclipse.m2e.workspace.cli_0.3.1.jar 

jar verified.

Warning: 
This jar contains entries whose TSA certificate chain is invalid. Reason: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
The timestamp has expired.
The SHA1withRSA signature algorithm is considered a security risk. This algorithm will be disabled in a future update.
The SHA-1 timestamp digest algorithm is considered a security risk. This algorithm will be disabled in a future update.
The RSA signing key has a keysize of 1024 which is considered a security risk. This key size will be disabled in a future update.

Re-run with the -verbose and -certs options for more details.
```
Maybe this warning is enough to cause the check failure.

**Comment by HannesWell** [comment]
> Maybe this warning is enough to cause the check failure.

@laeubi are you aware of any change in Tycho in this regard?

**Comment by laeubi** [comment]
As you can see from the stack there is nothing Tycho involved by the verification.

What can happen is:

- JVM does not support an algorithm anymore by default because it is invalid
- The TSA is not reachable 
- ...

**Comment by mickaelistria** [comment]
This happens during execution of a Tycho mojo. It might still be a Tycho issue, because I tried installing m2e in Eclipse SDK, and org.eclipse.m2e.workspace.cli got installed without signature error.
The screenshot also shows this bundle is interpreted as signed in the IDE
![Screenshot from 2023-10-31 08-42-19](https://github.com/eclipse-m2e/m2e-core/assets/469058/23285377-3b47-4c7d-abd2-f0d7fd8fe088)
Maybe Tycho does treat warnings as error; or maybe Tycho alters the file in some way before packaging it....

**Comment by laeubi** [comment]
> This happens during execution of a Tycho mojo.

Well it is `tycho-p2-repository:4.0.3:verify-repository` so what would be expected if not telling any problems :-)
Nevertheless  tycho delegates to p2 what delegates to eclipse, also please note it complains **about the source bundle** what probably previously was never included... at least it is not installed in the IDE.

> Problems downloading artifact: osgi.bundle,**org.eclipse.m2e.workspace.cli.source,0.3.1.**

**Comment by akurtakov** [comment]
It could be related to JVM updates in Jenkins as per https://www.eclipse.org/lists/cross-project-issues-dev/msg19767.html

**Comment by laeubi** [comment]
> Because my local installation, using latest JustJ is fine; jarsigner using Fedora's Java 21 is fine too.

With the **source** artifact?

**Comment by mickaelistria** [comment]
Ah my bad, I was indeed not looking at the source artifact.
And your comment led to a good clue: the source artifact was *not* included in the repo for last successful build https://download.eclipse.org/technology/m2e/snapshots/latest/plugins/ . Could it be that the source artifact is now wrongly generated and aggregated by Tycho while it used to be ignored?

**Comment by fbricon** [comment]
Anything that forces us to use tycho 4.0.3? Can we roll back to a previous version to unstuck the build while this issue is being addressed?

**Comment by HannesWell** [comment]
Good point Christoph!

> Anything that forces us to use tycho 4.0.3?

Yes Tycho 4.0.3 is required for
https://github.com/eclipse-m2e/m2e-core/pull/1222

Therefore I'm in favour of Mickael's approach to exclude the offending source.

**Comment by mickaelistria** [comment]
Fixed with https://github.com/eclipse-m2e/m2e-core/commits/master

**Comment by laeubi** [comment]
What I'm wondering: Should `org.eclipse.m2e.workspace.cli` not be part of m2e build and therefore signed by a more "modern" certificates? do we maybe missing to sign source artifacts? Should source artifacts be signed at all?

**Comment by HannesWell** [comment]
> What I'm wondering: Should `org.eclipse.m2e.workspace.cli` not be part of m2e build and therefore signed by a more "modern" certificates? do we maybe missing to sign source artifacts?

Isn't that in another Repo of this orga?
There probably just was no build done for a while.

> Should source artifacts be signed at all?

Why Not?
