### ISSUE TITLE
PDE target platform integration - Use local Maven cache

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#1627]
It seems not possible to use the local Maven repository as source for the M2E PDE target platform.

To test: 

1.) Run a Tycho Maven build for one plugin with "mvn clean install" -> this copies the plugin into the .m2/repository cache

Output: 

![image](https://github.com/eclipse-m2e/m2e-core/assets/139910/3a9bcf24-0dfa-41b7-81c6-cd2f7e31f803)

2.) Now add the GAV for your plugin to the target platform, e.g. 

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="target.platform">
	<locations>
		<location includeDependencyDepth="none" includeDependencyScopes="compile" includeSource="true" missingManifest="generate" type="Maven">
			<dependencies>
					<dependency>
					<groupId>com.vogella.tycho</groupId>
					<artifactId>plugin1</artifactId>
					<version>1.0.0</version>
					<type>jar</type>
				</dependency>
			</dependencies>
			<repositories>
				<repository>
					<id>localRepository</id>
					<url>file://home/vogella/.m2/repository/</url>
				</repository>
			</repositories>
		</location>
	</locations>
</target>

```
Also adding the local repo as Maven central entry via the /home/.m2/settings.xml does not work:

```
<settings>
  <!-- Other configurations -->

  <profiles>
    <profile>
      <id>disable-central</id>
      <repositories>
        <repository>
          <id>central</id>
          <url>none</url>
        </repository>
      </repositories>
    </profile>
    <profile>
      <id>local</id>
      <repositories>
        <repository>
          <id>central</id>
          <url>file://home/vogella/.m2/repository/</url>
        </repository>
      </repositories>
    </profile>

  </profiles>
  <activeProfiles>
    <activeProfile>local</activeProfile>
  </activeProfiles>
<!-- 
-->
  <!-- Other configurations -->
</settings>

```

Tycho seems to have the same problem. Both tools work for Maven libraries from Maven central. I their something wrong with my setup?

**Comment by vogella** [comment]
If I create a dedicated local Maven repository the output looks different: 
```
mvn deploy -DaltDeploymentRepository=snapshot-repo::default::file:/tmp/test-repo
```

![image](https://github.com/eclipse-m2e/m2e-core/assets/139910/b12fa1dc-d5a5-4814-882d-496dd93cdd75)

But the target platform still fails in resolving to this Maven artifact:

![image](https://github.com/eclipse-m2e/m2e-core/assets/139910/bfea6852-4f9b-4038-84ad-95a852396145)

![image](https://github.com/eclipse-m2e/m2e-core/assets/139910/821a3579-d3f2-4ba1-8646-cbf3e412993d)

**Comment by laeubi** [comment]
> It seems not possible to use the local Maven repository as source for the M2E PDE target platform.

I don't understand that, m2e (and maven)  uses maven resolver to resolve artifacts that are (if they are remove) cached in the local repository so in the end every file is located there but it is merely a "source", the source is always the metadata and a set of remote repositories (where central is the default).

> Run a Tycho Maven build for one plugin with "mvn clean install" -> this copies the plugin into the .m2/repository cache

well it installs it into the local repository but your screenshot is not showing anything is actually installed, so have you checked the output that it really deploys it there where you expect it to be located?

> Now add the GAV for your plugin to the target platform, e.g.

Why you have a reference to your local repository in that example this does not make sense as the local repository is not a remote repository.

> Also adding the local repo as Maven central entry via the /home/.m2/settings.xml does not work:

Same as above this does not make much sense here...

> If I create a dedicated local Maven repository the output looks different:

This is something completely different, you create a maven repository that is locally stored on your harddisk, the maven local repository is something different.
