### ISSUE TITLE
Missing project-files and inconsistent .classpath configurations

### ISSUE THREAD

**Issue by HannesWell** [eclipse-m2e/m2e-core#163]
The plugin `org.eclipse.m2e.binaryproject` has no `.project` file and is therefore not imported when importing all projects from the m2e-core repo into a clean workspace, which results in compile errors.

For all feature projects the `.project` file is missing too. No feature project is therefore imported.

All these statements are based on the assumption that all projects from this m2e-core repo should be imported, so please correct me if I'm wrong.

Furthermore the `.classpath` files are configured differently. Some plugin-projects have the entry `<classpathentry kind="output" path="target/classes"/>` is used, but for plugin-projects the output folder `bin` is more common (and also used by some projects). Second some classpath-files in plugin-projects use `<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER"/>` while I assume it should be `<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11"/>`

To me, it looks like the clean-up in PR #69 respectively commit 569b246d3a34f1bf43fad704a676d4a40d9d733e was too aggressive respectively it was forgotten to convert the former Maven-projects into pure PDE plugin/feature-projects. I assume it just worked at other peoples workspace because they imported the projects before the mentioned clean-up so the .project and .classpath files were generated at that import.
I found that some `.project` files are already added in #150 but the additions seem to be incomplete.

If you agree with the suggestions I can provide a PR to fix those issues.

**Comment by HannesWell** [comment]
I just found that the entire project `org.eclipse.m2e.binaryproject` is included in the root `.gitignore` which makes me wonder if the project is to be ignored. But from were should the `org.eclipse.m2e.binaryproject.*` packages come from?

**Comment by HannesWell** [comment]
It looks like the "src" paths are also not set up correctly for some projects and there exist general inconsistencies regarding the out-path between the .classpath and the build.properties file.

**Comment by mickaelistria** [comment]
The main issue is that the .project and .classpath were part of .gitignore when pom-less was adopted, so their addition did fall under the radar. And the further addition was quick and dirty.
Anyway, sure, fixes to .project and .classpath are really welcome!

**Comment by HannesWell** [comment]
Alright, I'm about to prepare a fix.

**Comment by HannesWell** [comment]
Do you also want the `module=true` attribute set for the JRE container in all .classpath files?
The JRE_CONTAINER would look like this:
```
<classpathentry kind="con" path="org.eclipse.jdt.launching.JRE_CONTAINER/org.eclipse.jdt.internal.debug.ui.launcher.StandardVMType/JavaSE-11">
	<attributes>
		<attribute name="module" value="true"/>
	</attributes>
</classpathentry>
```
As far I understand it correctly the JRE_CONTAINER is on the module-path by default anyways so this probably makes no real difference. But when one opens the Configure build path... wizard the module attribute is added without any change.
I tested it locally for all projects and it worked (no compile errors). So if you want it I can submit another PR for this.

**Comment by mickaelistria** [comment]
I have no strong opinion about that. Whatever works ;) I trust your judgement on that topic, so if you want to contribute this, feel free.

**Comment by HannesWell** [comment]
When I upgraded a plugin in eclipse.platform.debug to Java-11, I was asked to add the module attribute to the JRE_CONTAINER in the `.classpath`. I hope they have a good reason for this (a very weak argument, I know).
I looks like the module-attribute puts the annotated `classpathentry` on the modulepath. But from what I know about modules (but I don't have a deep knowledge) the java standard library/modules are always on the module-path.
From that I conclude that the module-attribute is redundant, but reflects the actual situation.

When you open the `Configure build path...` wizard for a project with Java-11 JRE-container in the classpath that has no module-attribute and just hit `Apply and close` (without any changes) that attribute is added. So the motivation of the platform-debug team to have the attribute could be to avoid changes every time somebody opens the `Configure build path...` wizard.
So I think this would also be suitable for m2e. Over the time it would probably sneak in step by step anyway.

I've tested it locally and everything works fine (IDE and build). So I will submit a PR.

**Comment by HannesWell** [comment]
The last point in this topic I want to suggest is to rename the source folders of the following projects from `src/main/java` to `src` in order to be consistent to all other projects and comply with Eclipse's plug-in project convention:
- org.eclipse.m2e.editor.xml
- org.eclipse.m2e.logback.appender
- org.eclipse.m2e.model.edit

If you agree I can submit another PR.

**Comment by mickaelistria** [comment]
No objection.

**Comment by laeubi** [comment]
I try to sync with the latest changes but now Eclipse complains:

```
Description	Resource	Path	Location	Type
The package javax.xml.parsers is accessible from more than one module: <unnamed>, java.xml	ArchetypeCatalogsWriter.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/archetype	line 24	Java Problem
```

did I miss anything?

**Comment by mickaelistria** [comment]
Are you using a recent version of the Eclipse SDK? I think this is an instance of https://bugs.eclipse.org/bugs/show_bug.cgi?id=571363 (which has been revealed by the addition of modular=true in .classpath files)

**Comment by HannesWell** [comment]
I had the same errors and the problem seemed to be that some of the .classpath files derived from the pom.xml are not updated properly. My solution was to just deleted all projects from the workspace, cleaned the repo (files and directories, **including ignored ones**) and re-import the relevant projects. Of course you can do it more fine grained.

**Comment by laeubi** [comment]
I'm using

Version: 2021-03 (4.19.0)
Build id: 20210312-0638

I have unloaded all projects, deleted all unversioned files and did a reimport... my eclipse was still confused, but after a restart it seems to work now.

One thing I noticed: It seems it is required to run a maven build in advance to get "generated-sources", would be nice if m2e would be able to do this without manual invocation from the  commandline.

**Comment by laeubi** [comment]
Seems I was to optimistic :-\ 

After a rebuild I get these error (+92.000+ that I don't copy here), maybe because I'm using a native J11 JDK?

```
Description	Resource	Path	Location	Type
'<>' cannot be used with anonymous classes	MavenArtifactIdentifier.java	/org.eclipse.m2e.sourcelookup/src/org/eclipse/m2e/sourcelookup/internal/launch	line 51	Java Problem
```

**Comment by HannesWell** [comment]
> 
> 
> Seems I was to optimistic :-\
> 
> After a rebuild I get these error (+92.000+ that I don't copy here), maybe because I'm using a native J11 JDK?
> 
> ```
> Description	Resource	Path	Location	Type
> '<>' cannot be used with anonymous classes	MavenArtifactIdentifier.java	/org.eclipse.m2e.sourcelookup/src/org/eclipse/m2e/sourcelookup/internal/launch	line 51	Java Problem
> ```
A restart could indeed be necessary, too.

I'm also using a Java-11 JDK (GraalVM 21.0.0) on Windows10 in a Eclipse for Eclipse Commiters (Version: 2021-03 (4.19.0)
Build id: 20210312-0638) and for me everything works fine.

The only thing I can suggest is to repeat deleating all projects and cleaning the repo, then do the restart before importing the projects and then import them again.

One more thing, do you have the test projects from the sub-module `tesla/m2e-core-tests` imported?
When I import them I get 13 additional errors (their configuration probably needs to be updated too).

**Comment by laeubi** [comment]
I deleted my local clone an checked out a fresh copy to be sure. If I goto `Git > m2ecore > Import Projects` I still see some maven projects to be suggested:

![grafik](https://user-images.githubusercontent.com/1331477/114543890-1f3ccc80-9c5a-11eb-9b47-3358dca5e657.png)

**Comment by HannesWell** [comment]
> I deleted my local clone an checked out a fresh copy to be sure. If I goto `Git > m2ecore > Import Projects` I still see some maven projects to be suggested:

For me this is as expected. The projects within m2e-maven-runtime were not converted into Eclipse projects.

**Comment by laeubi** [comment]
Still no luck :-(

```
Description	Resource	Path	Location	Type
'<>' cannot be used with anonymous classes	MavenArtifactIdentifier.java	/org.eclipse.m2e.sourcelookup/src/org/eclipse/m2e/sourcelookup/internal/launch	line 51	Java Problem
Attr cannot be resolved to a type	MavenModelManager.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/embedder	line 141	Java Problem
Attr cannot be resolved to a type	MavenModelManager.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/embedder	line 147	Java Problem
Attr cannot be resolved to a type	MavenModelManager.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/embedder	line 153	Java Problem
Attributes cannot be resolved to a type	ArchetypeCatalogsWriter.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/archetype	line 166	Java Problem
Attributes cannot be resolved to a type	PomHandler.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/content	line 140	Java Problem
AttributesImpl cannot be resolved to a type	ArchetypeCatalogsWriter.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/archetype	line 126	Java Problem
AttributesImpl cannot be resolved to a type	ArchetypeCatalogsWriter.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/archetype	line 129	Java Problem
AttributesImpl cannot be resolved to a type	ArchetypeCatalogsWriter.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/archetype	line 129	Java Problem
Comment cannot be resolved to a type	LifecycleMappingOperation.java	/org.eclipse.m2e.core.ui/src/org/eclipse/m2e/core/ui/internal/editing	line 120	Java Problem
Comment cannot be resolved to a type	MarkerLocationService.java	/org.eclipse.m2e.core.ui/src/org/eclipse/m2e/core/ui/internal/markers	line 653	Java Problem
Comment cannot be resolved to a type	MarkerLocationService.java	/org.eclipse.m2e.core.ui/src/org/eclipse/m2e/core/ui/internal/markers	line 654	Java Problem
Comment cannot be resolved to a type	MarkerLocationService.java	/org.eclipse.m2e.core.ui/src/org/eclipse/m2e/core/ui/internal/markers	line 654	Java Problem
ContentHandler cannot be resolved to a type	ArchetypeCatalogsWriter.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/archetype	line 124	Java Problem
DefaultHandler cannot be resolved to a type	ArchetypeCatalogsWriter.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/archetype	line 154	Java Problem
DefaultHandler cannot be resolved to a type	PomHandler.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/content	line 40	Java Problem
DefaultHandler cannot be resolved to a type	PomHandler.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/internal/content	line 156	Java Problem
DocumentBuilder cannot be resolved to a type	MavenModelManager.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/embedder	line 133	Java Problem
DocumentBuilderFactory cannot be resolved	MavenModelManager.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/embedder	line 131	Java Problem
DocumentBuilderFactory cannot be resolved to a type	MavenModelManager.java	/org.eclipse.m2e.core/src/org/eclipse/m2e/core/embedder	line 131	Java Problem
... and more
```

mvn compile indeed works without a problem.

**Comment by laeubi** [comment]
> Are you using a recent version of the Eclipse SDK?

So I need to use an I-Build..? I'm confused about the state of the bug as it has worked before I updated to the new layout, has it something to do with the "modular" property in classpath?

**Comment by mickaelistria** [comment]
> So I need to use an I-Build..?

Seems so. But I-Builds are really the best builds to work with for contributors such as yourself, they will eventually make you more productive by allowing a quick profit loop.

> I'm confused about the state of the bug as it has worked before I updated to the new layout, has it something to do with the "modular" property in classpath?

Yes, I think so.

**Comment by laeubi** [comment]
> they will eventually make you more productive by allowing a quick profit loop

currently the ROI is actually very low :-\

Anyways its seems I should try to give the ibuild a try.

**Comment by laeubi** [comment]
To the best of my knowledge I have upgraded to the I-Build (Eclipse says: No Updates available), still no luck
![grafik](https://user-images.githubusercontent.com/1331477/114652983-52796d00-9ce7-11eb-80b4-0a38a429c172.png)

java version "11.0.8" 2020-07-14 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.8+10-LTS)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode)

Eclipse.ini
```
-startup
plugins/org.eclipse.equinox.launcher_1.6.100.v20201223-0822.jar
--launcher.library
plugins/org.eclipse.equinox.launcher.gtk.linux.x86_64_1.2.200.v20210409-2137
--launcher.defaultAction
openFile
--launcher.appendVmargs
-vmargs
-Dosgi.requiredJavaVersion=11
-Dosgi.dataAreaRequiresExplicitInit=true
-Dorg.eclipse.swt.graphics.Resource.reportNonDisposed=true
-Xms256m
-Xmx2048m
--add-modules=ALL-SYSTEM
```

**Comment by HannesWell** [comment]
It just came into my mind, that before I cleaned the entire repo the errors vanished when I closed or deleted the projects nested in the `m2e-maven-runtime` folder. IIRC it was even enough to closed/delete `m2e.maven.indexer`.
Does this make any difference for you?

Otherwise I can test it with the latest I-Build and latest m2e snapshot at my computer.
And I'm sorry for the inconvenience.

**Comment by HannesWell** [comment]
> Really strange... this seems to make the difference!

Great. If you need to work with the projects nested in `m2e-maven-runtime` you could again try to delete, clean and re-import them.

> I only have one error but I think I can ignore that for now:
> 
> ```
> Description	Resource	Path	Location	Type
> Variable resource not allowed here for source level below 9	WTPEditorTest.java	/org.eclipse.m2e.editor.xml.sse.tests/src/org/eclipse/m2e/editor/xml/sse/tests	line 99	Java Problem
> ```
At this location the `AutoClosable` variable is only referenced as resource of the try-with-resource, which is allowed only since Java-9.
This makes me wonder if your Java Compiler compliance level in the preferences is still on Java-8 (it should be Java-11) or if in any other Java-version related preference is Java-8 instead of Java-11? All projects (except those in `m2e-core-tests`) should require Java-11 for now.
When I set the Java Compiler compliance level to `8` in the preferences it get the error you mentioned plus one in the 'MavenArtifactIdentifier.java` that states that the diamond operator is not allowed for anonymous classes in Java-8.

> BTW having a setup file would really help if you are interested to contribute one: #120

I've already seen the mentioned issue and agree that a setup file would be helpful, but I thought that Mickael is already working on it. But I will offer my help there.

**Comment by laeubi** [comment]
It must something like that and must have changed recently. For me it seems as if in the global preferences the compliance is 1.8 but in the project settings it is 11 then JDT gts confused. I started another workspace and got a similar problem today, thats really annoying.

**Comment by HannesWell** [comment]
> It must something like that and must have changed recently. For me it seems as if in the global preferences the compliance is 1.8 but in the project settings it is 11 then JDT gts confused. I started another workspace and got a similar problem today, thats really annoying.

I feel your pain. But for me this is just +1 for an Oomph setup.
I've just opened PR #176 which adds a basic inital setup. Testing is welcome, if you want.

**Comment by HannesWell** [comment]
The last PR for this issue is merged, so this is issue is completed.
