### ISSUE TITLE
Take the version for an annotation processor from project `dependencyManagement` just like `maven-compiler-plugin` 3.12+ does

### ISSUE THREAD

**Issue by famod** [eclipse-m2e/m2e-core#1644]
`maven-compiler-plugin` 3.12.0 (latest currently is 3.12.1) learned a new trick: https://issues.apache.org/jira/browse/MCOMPILER-391
This means that e.g. `hibernate-jpamodelgen` annotation processor in a Quarkus project (that imports the Quarkus BOM) can be defined without an explicit version (and you don't need to align the version on each Quarkus update):
Before:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.12.1</version>
    <configuration>
        <annotationProcessorPaths>
            <path>
                <groupId>org.hibernate.orm</groupId>
                <artifactId>hibernate-jpamodelgen</artifactId>
                <version>6.1.2.Final</version>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>
```
After:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.12.1</version>
    <configuration>
        <annotationProcessorPaths>
            <path>
                <groupId>org.hibernate.orm</groupId>
                <artifactId>hibernate-jpamodelgen</artifactId>
            </path>
        </annotationProcessorPaths>
    </configuration>
</plugin>
```

When I try to import/update such a project in Eclipse (2023-12), I'm getting a config error saying that the artifact was not found, with the version part of the coordinates being empty.

This is how it's done in the compiler-plugin: https://github.com/apache/maven-compiler-plugin/pull/180/files#diff-d4bac42d8f4c68d397ddbaa05c1cbbed7984ef6dc0bb9ea60739df78997e99ee

**Comment by laeubi** [comment]
@famod do you want t try providing a PR for this new behavior?

**Comment by famod** [comment]
@laeubi I've gotten ill and I'm still not fully done with it. So please don't wait for me.
