### ISSUE TITLE
PDE / Maven integration not available for PDE MANIFEST 

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#171]
Adding the following library does not make it available for the MANIFES.MF PDE dependencies selection or for the feature selection.

<dependency>
  <groupId>com.oracle.database.jdbc</groupId>
  <artifactId>ojdbc10</artifactId>
  <version>19.10.0.0</version>
</dependency>

To reproduced:

1.) Create base target definition file:
----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="target-platform">
	<locations>
		<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
			<repository location="https://download.eclipse.org/releases/latest"/>
			<unit id="org.eclipse.e4.rcp.feature.group" version="0.0.0"/>
		</location>
	</locations>
</target>
----

2.) Add the dependency

3.) Reload target and check that it is available in the target

4.) Try to use it in MANIFEST.MF or Feature -> not available

Demo:

![dependency](https://user-images.githubusercontent.com/139910/114524798-cf540a80-9c45-11eb-8c5b-d752f2f13e65.gif)

**Comment by laeubi** [comment]
Can you share how your target looks like in text-form, its a bit hard in the screen cast to follwow.

**Comment by laeubi** [comment]
One problem might be that Oracle prohibits any modifications in the license terms of the jar:

> Oracle grants to You,[..], subject to the conditions stated herein, (a) internally **_use the unmodified Programs_** for [...]

**Comment by vogella** [comment]
Here is the target file after I added the Maven central entry:

----
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="target-platform">
	<locations>
		<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="planner" includeSource="true" type="InstallableUnit">
			<repository location="https://download.eclipse.org/releases/latest"/>
			<unit id="org.eclipse.e4.rcp.feature.group" version="0.0.0"/>
		</location>
		<location includeSource="true" missingManifest="generate" type="Maven">
			<groupId>com.oracle.database.jdbc</groupId>
			<artifactId>ojdbc10</artifactId>
			<version>19.10.0.0</version>
			<type>jar</type>
		</location>
	</locations>
</target>
----

**Comment by laeubi** [comment]
thanks, sadly my me2 dev is currently broken so I can not take a look at it right now, are you using the 2021-03 release or an I-Build/Snapshot version of m2e?

have you tried closing the Manifest editor before you have set the target (just in case PDE is plaing tricks here...)

**Comment by vogella** [comment]
I tried the 2021-03 release and an I-Build. Closing the MANIFEST.MF editor does not help.

If I restart the whole IDE the lib become available.

**Comment by laeubi** [comment]
strange, but I fear this might then be a bug in PDE so best is to open a bug there, and if it reveals m2e does anything wrong we can fix it. Sorry for not being able to give better advice for now ... good luck!

**Comment by laeubi** [comment]
I did the following:

1. create an empty target
2. copied your content into it
3. wait for resolve
4. verified with 'show location content' that everything is there
![grafik](https://user-images.githubusercontent.com/1331477/114728713-9ef09700-9d3f-11eb-848a-5ceb9ab7e77d.png)
5. open a feature and go to add-plugin, search for 'jd' 
![grafik](https://user-images.githubusercontent.com/1331477/114728898-ccd5db80-9d3f-11eb-9453-bcf2af10bdbd.png)

Maybe the target update was not complete (yet) as you tried to add the lib? If the problem persists, can you open the 'Target Platform state' view and check if it is available there? If you choose '...' > Change Target, is your target marked as the active on there?
![grafik](https://user-images.githubusercontent.com/1331477/114729567-64d3c500-9d40-11eb-843b-573e61e2f0b0.png)

**Comment by vogella** [comment]
Thanks @laeubi for the test. In recent releases this seems to work better for me. I'm still now in the habit to restart the IDE, if a new library cannot be found before looking for other reasons but at least it works for me in most cases and as you cannot replicate I close this issue.
