### ISSUE TITLE
overider OSGi manifest for maven artifacts

### ISSUE THREAD

**Issue by hieplq** [eclipse-m2e/m2e-core#1711]
With support [maven as repository](https://läubisoft.gmbh/en/articles/using-maven-artifacts-in-pde-rcp-and-tycho-builds/) I can automatically generate OSGi manifests for artifacts that don't already have them

but sometime i need to modify manifests a bit (example add version to import-package).
moment i have to do as bellow:
1. use [reficio:p2-maven-plugin](https://github.com/reficio/p2-maven-plugin) to override manifest
2. create p2 or maven repository for artifacts at (1)
3. add repository (2) to target platform

so add "override" flag is helpful on my case

**Comment by hieplq** [comment]
> if you change the manifest of a bundle that is already installed, P2 will not use your artifact but the existing one so you can get all kinds of confusing errors

Does this condition also hold true for artifacts that lack OSGi manifests?

example: 
I have two projects using Spring Core with the same version on their target platforms. 
Both projects need to generate OSGi manifests for Spring Core. 
However, one project specifies `Import-Package: org.apache.commons.logging;version="[1.2,2)" `
while the other uses `Import-Package: org.apache.commons.logging;version="[2,3)"` for the org.apache.commons.logging package

So both target platforms will utilize the same Spring Core wrapper(first one installed)?

```
<location includeSource="true" missingManifest="generate" type="Maven">
      <groupId>org.springframework</groupId>
      <artifactId>spring-core</artifactId>
      <version>5.3.27</version>
      <type>jar</type>
      <instructions><![CDATA[Bundle-Name:           Bundle derived from maven artifact ${mvnGroupId}:${mvnArtifactId}:${mvnVersion}
version:               ${version_cleanup;${mvnVersion}}
Bundle-SymbolicName:   wrapped.${mvnGroupId}.${mvnArtifactId}
Bundle-Version:        ${version}
Import-Package:        org.apache.commons.logging;version="[1.2,2)";resolution:=optional,org.apache.commons.logging.impl;version="[1.1.1,2)";resolution:=optional,*;resolution:=optional
Export-Package:        *;version="${version}";-noimport:=true
]]></instructions>
</location>
```

**Comment by laeubi** [comment]
> Does this condition also hold true for artifacts that lack OSGi manifests?

Sure keep in mind that the generate option is more a mitigation than a permanent solution, you should always ask the project to add OSGi metadata as this is the only way to permanently get correct results. Using bnd-process goal this is also  not any work for the projects.

> So both target platforms will utilize the same Spring Core wrapper(first one installed)?

Basically yes. you can't have the same version installed twice.

**Comment by hieplq** [comment]
That's really helpful, thanks!
