### ISSUE TITLE
Missing tag 2.4.1 in this repo

### ISSUE THREAD

**Issue by alexsuter** [eclipse-m2e/m2e-core#1732]
Eclipse 2023-12 is shipped with m2e 2.4.1. But I can not find a tag 2.4.1 in this repo. Can you add this tag? Or point be to the correct commit?

**Comment by HannesWell** [comment]
Please not that the name of a release is more like a branding name. The name of individual bundles does not necessarily have to match that version especially if there where no changes for some time.

There is no m2e 2.4.1 release: https://download.eclipse.org/technology/m2e/releases/
Therefore there is also no corresponding tag.

> Or point be to the correct commit?

You can have a look into the bundles Manifest and check the `Eclipse-SourceReferences` header. It contains the URL of the repository and the commit from which that build has been build in that release.

**Comment by alexsuter** [comment]
@HannesWell Thanks for taking the time to explain that to me.

Found it:
```
Eclipse-SourceReferences: scm:git:https://github.com/eclipse-m2e/m2e-cor
 e.git;path="org.eclipse.m2e.core";commitId=91e0130577d8931e3bd3057cc86c
 1abb7ded76be
```
