### ISSUE TITLE
Support for version 22

### ISSUE THREAD

**Issue by eitan-rosenberg** [eclipse-m2e/m2e-core#1756]
I am using:
openjdk-22.0.1_windows
Eclipse eclipse-SDK-4.31
M2E 2.6.0
apache-maven-3.9.6

My project is:
<maven.compiler.target>22</maven.compiler.target>
<maven.compiler.source>22</maven.compiler.source>

For compile and dependency download, every thing works fine.
When I try to use "Apache Maven Dependency Plugin" there is no support for version 22.
I am aware that this plugin is not part of M2E.

The only way I manage to make it work is to change the project manually to version 21.
Is there another way to do it ?
Any idea when there will be support for version 22 ?

Thanks for any response.

**Comment by akurtakov** [comment]
Does maven-dependency-plugin work with version 22 on the console/pure maven build?

**Comment by eitan-rosenberg** [comment]
> Does maven-dependency-plugin work with version 22 on the console/pure maven build?

Both method fail with:
org.apache.maven.plugins:maven-dependency-plugin:3.6.1:analyze failed: Unsupported class file major version 66

Seems like It's a version problem.

Me2 is not the blame.

**The only way I manage to make it work is to change the project manually to version 21**

**Comment by eitan-rosenberg** [comment]
Do we have to wait for the next release of maven ?

**Comment by eitan-rosenberg** [comment]
.

**Comment by HannesWell** [comment]
> Do we have to wait for the next release of maven ?

I haven't analyzed that, but the next release of maven is about to happen soon and m2e will then include it with https://github.com/eclipse-m2e/m2e-core/pull/1763.
But it could also be that a new release of the `maven-dependency-plugin` is required?

**Comment by eitan-rosenberg** [comment]
Thanks,
But it could also be that a new release of the maven-dependency-plugin is required?
Since the problem occurs when using pure maven build, I think that this is the problem (I will be happy if you prove me wrong...)

**Comment by laeubi** [comment]
This has nothing to do with m2e if it does not work in a plain maven build either.

**Comment by HannesWell** [comment]
> Thanks, But it could also be that a new release of the maven-dependency-plugin is required? Since the problem occurs when using pure maven build, I think that this is the problem (I will be happy if you prove me wrong...)

I'll be happy if the issue is resolved. So whatever solves it is good. :)
I suggest you monitor #1763 and try out the latest snapshot build ones it has been merged:
https://download.eclipse.org/technology/m2e/snapshots/2.6.1/

Feel free to report back if that is a solution, others might face the same problem.
