### ISSUE TITLE
Multi-Release JAR is not recognized as such

### ISSUE THREAD

**Issue by eitan-rosenberg** [eclipse-m2e/m2e-core#1764]
Recently, I update com.google.code.gson:gson to version 2.11.0 from version 2.10.1.

The project use module-info.java and use "requires com.google.gson;"

gson-2.11.0.jar is a Multi-Release JAR and the module declaration is at META-INF/versions/9/module-info.class

I open [an issue ](https://github.com/google/gson/issues/2679) and it got the full details.
Also included in that issue a small project to demonstrate the problem.(https://github.com/google/gson/files/15412480/ModuleTest.zip)

**When using pure maven build "mvn clean test" it is compiled successfully.
Also I can run it using  "mvn compile exec:java -Dexec.mainClass="main.Main"" .**

I use: 
M2E Maven Integration for Eclipse Core 2.6.0.20240220-1109
Eclipse 2024-03 (4.31)
Java openjdk version "22.0.1" 2024-04-16

Thanks in advance for any response.

**Comment by laeubi** [comment]
m2e is not handling the jar, JDT does https://github.com/eclipse-jdt/eclipse.jdt.core

**Comment by eitan-rosenberg** [comment]
> m2e is not handling the jar, JDT does https://github.com/eclipse-jdt/eclipse.jdt.core

OK, thanks.

**Comment by eitan-rosenberg** [comment]
.

**Comment by eitan-rosenberg** [comment]
.

**Comment by eitan-rosenberg** [comment]
.

**Comment by eitan-rosenberg** [comment]
close

**Comment by eitan-rosenberg** [comment]
Try to transfer issue

**Comment by eitan-rosenberg** [comment]
.

**Comment by eitan-rosenberg** [comment]
.

**Comment by mickaelistria** [comment]
FWIW, issues cannot be transferred between different Github organizations (and yes, it's a shame).
