### ISSUE TITLE
M2E version 2.6.1 fail to process <classifier> tag 

### ISSUE THREAD

**Issue by eitan-rosenberg** [eclipse-m2e/m2e-core#1778]
My pom.xml contain:

	<dependency>
		<groupId>org.openjfx</groupId>
		<artifactId>javafx-web</artifactId>
		<version>22</version>
	</dependency>

javafx-web-22.pom contain:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.openjfx</groupId>
	<artifactId>javafx-web</artifactId>
	<version>22</version>
	<parent>
		<groupId>org.openjfx</groupId>
		<artifactId>javafx</artifactId>
		<version>22</version>
	</parent>
	<dependencies>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-web</artifactId>
			<version>22</version>
			<classifier>${javafx.platform}</classifier>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>22</version>
		</dependency>
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-media</artifactId>
			<version>22</version>
		</dependency>
	</dependencies>
</project>

```

M2E before 2.6.1 use to download the platform dependent jar (e.g. [javafx-web-22-win.jar](https://repo1.maven.org/maven2/org/openjfx/javafx-web/22/javafx-web-22-win.jar))

After upgrade to 2.6.1 M2E fail to process the dependency classifier <classifier> tag and the result is wrong:

![2024-06-05_07-00-57](https://github.com/eclipse-m2e/m2e-core/assets/48506054/a4b1b6b2-1144-47c9-95a4-0f26d19feb36)

And in eclipse:

![2024-06-05_06-59-13](https://github.com/eclipse-m2e/m2e-core/assets/48506054/558ffda8-e9e6-4f4a-92b9-d58f7cefe02f)

When using M2E 2.6.0 the result is OK:

![2024-06-05_07-10-37](https://github.com/eclipse-m2e/m2e-core/assets/48506054/66b95fc3-87a2-4c2b-8199-c0b301eed343)

I have:
openjdk-22.0.1_windows-x64_bin.zip
Eclipse eclipse-SDK-4.31-win32-x86_64.zip
apache-maven-3.9.7-bin.zip
Windows 10

**Comment by taranion** [comment]
I can confirm that. I am having the same issue.

**Comment by eitan-rosenberg** [comment]
Using:

mvn clean compile -Djavafx.platform=win works.
mvn compile exec:java -Dexec.mainClass="main.MyApplication" -Djavafx.platform=win

Works !!!

**Comment by syluna** [comment]
I have the same issue and downgrade to 2.6.0 works fine too

**Comment by eitan-rosenberg** [comment]
> I have the same issue and downgrade to 2.6.0 works fine too

The problem is that eclipse 2024-06 (4.32) come by default with M2E version 2.6.1, and you have to uninstall it and use https://download.eclipse.org/releases/2024-03 repository.

**And the biggest problem is that it seems that M2E team is not aware of the problem.**

**Comment by laeubi** [comment]
> And the biggest problem is that it seems that M2E team is not aware of the problem.

There is no M2E "team" only some persons maintain this in their free time... so if you want to analyze it or provide a fix any help is welcome. Also please keep in mind that maven "universe" is extremely large there are million of variants, so just because you got hit by a problem doesn't mean everyone else is affected.

From what you provided here:
```
mvn clean compile -Djavafx.platform=win works.
mvn compile exec:java -Dexec.mainClass="main.MyApplication" -Djavafx.platform=win
```

it does not "work" out of the box, you are specify a system property manually, so have you done the same for m2e? Either through configuration or e.g using `.mvn/maven.config`?

**Comment by eitan-rosenberg** [comment]
Thank you very much for this response !!!
I definitely will look into .mvn/maven.config.
I have to admit that this is new for me. As you can see, there are at least two others that were hit by this problem.
I never had .mvn/maven.config, so I guess that m2e was doing something behind the scene to support javafx.platform=win

**Comment by eitan-rosenberg** [comment]
Based on https://maven.apache.org/configure.html
I created a new eclipse installation.
I tried using:
- MAVEN_ARGS environment variable
- .mvn/maven.config

Both option works fine from CLI as @laeubi mention but against all hopes no effect on M2E.

**Comment by laeubi** [comment]
I think best would then to provide a test (e.g. https://github.com/eclipse-m2e/m2e-core/tree/master/org.eclipse.m2e.core.tests ) to show this behavior with a minimal project, that would also ensure that once fixed the problem will not be slip in undiscovered again.

**Comment by eitan-rosenberg** [comment]
> I think best would then to provide a test (e.g. https://github.com/eclipse-m2e/m2e-core/tree/master/org.eclipse.m2e.core.tests ) to show this behavior with a minimal project, that would also ensure that once fixed the problem will not be slip in undiscovered again.

Since I am not using GitHub, I will describe the steps to show this behavior.

Install "Eclipse IDE for Java Developers" from
https://www.eclipse.org/downloads/packages/release/2024-03/r
**Eclipse 2024-03 (4.31) include M2E 2.6.0.20240220-1109**	

Add Java 22 Support for Eclipse 2024-03 (4.31)
https://marketplace.eclipse.org/content/java-22-support-eclipse-2024-03-431

Create a project that will have javafx dependency

		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-web</artifactId>
			<version>22</version>
		</dependency>
		
The dependencies are OK.

Close the project.

Check for update and select M2E for update (only M2E).

Open the project.

You will see the behavior mention in my first message.

In order to fix the problem, I uninstall M2E, and then I reinstall M2E 2.6.0 from:
Eclipse Repository https://download.eclipse.org/releases/2024-03

**Comment by tadamovsky** [comment]
It looks to be this maven issue: https://issues.apache.org/jira/browse/MNG-8131
it was fixed in  maven 3.9.8 while embedded maven is currently 3.9.7 which is exactly the buggy version
see also this thread: https://stackoverflow.com/questions/78542808/maven-project-fails-to-resolve-javafx-dependencies

**Comment by eitan-rosenberg** [comment]
> It looks to be this maven issue: https://issues.apache.org/jira/browse/MNG-8131 it was fixed in maven 3.9.8 while embedded maven is currently 3.9.7 which is exactly the buggy version see also this thread: https://stackoverflow.com/questions/78542808/maven-project-fails-to-resolve-javafx-dependencies

Odd....

https://issues.apache.org/jira/browse/MNG-8131 say "Use maven != 3.9.7"
I currently use apache-maven-3.9.7-bin.zip with M2E 2.6.0, and it is working....

**Comment by tadamovsky** [comment]
In maven settings, it says embedded maven is always used for dependency resolution, maven you select is only used for launch. 2.6.0 embedded version is not 3.9.7 that's why it is working.

**Comment by eitan-rosenberg** [comment]
I created a test installation:

- M2E **2.6.1.20240602-2342** 
- Maven embedded and external 3.9.7
- 
		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-web</artifactId>
			<version>23-ea+22</version>
		</dependency>

![image](https://github.com/eclipse-m2e/m2e-core/assets/48506054/e2272352-54a1-4855-a381-f237e0e9f11f)

Works.

**Comment by tadamovsky** [comment]
@eitan-rosenberg 
So it started working for you or what happened?

**Comment by eitan-rosenberg** [comment]
> @eitan-rosenberg So it started working for you or what happened?

**Not really.**

`<version>22</version>` still have this problem.

From the discussions mentions in https://issues.apache.org/jira/browse/MNG-8131 

https://mail.openjdk.org/pipermail/openjfx-dev/2024-May/047279.html

"In short, OpenJFX parent provides invalid POM since 2021."

"The problem is fixed in the artifacts for JavaFX version 23-ea+20."

So I test it with <version>23-ea+22</version> (early access).

I guess we will have to wait for version JavaFX version 23.

**Comment by eitan-rosenberg** [comment]
Hot from the oven....
**Maven 3.9.8 Release Notes:** 
https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12316922&version=12354748
Property replacement in dependency pom no longer works (https://issues.apache.org/jira/browse/MNG-8131)

**Comment by HannesWell** [comment]
> Hot from the oven.... **Maven 3.9.8 Release Notes:** https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12316922&version=12354748 Property replacement in dependency pom no longer works (https://issues.apache.org/jira/browse/MNG-8131) CLI works now without -Djavafx.platform=win

I just submitted the update of the embedded runtime to Maven 3.9.8 (https://github.com/eclipse-m2e/m2e-core/pull/1781)
Can you try out the latest snapshot available in a few minutes at:
https://download.eclipse.org/technology/m2e/snapshots/2.6.2/

**Comment by eitan-rosenberg** [comment]
Good morning !

Thanks for the late night work.

Seems to work.

![image](https://github.com/eclipse-m2e/m2e-core/assets/48506054/0d43390a-0abe-4e80-9942-b64b41395228)

**Comment by HannesWell** [comment]
Great. Good news in the morning.
Thanks for checking.
