### ISSUE TITLE
m2e feature is incomplete

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#180]
I have added the m2e-core feature to a product but eclipse complains about missing requirements

![grafik](https://user-images.githubusercontent.com/1331477/116398639-513c5a00-a828-11eb-8ee8-c892c408efea.png)

I don't know if a feature can support package requirements, but at least the required bundles should be included in the feature so it is self-contained.

**Comment by mickaelistria** [comment]
If you think about it that way, then it means that the m2e feature should also include the platform feature and all dependencies. In practice, features are not really meant to be self-contained, but are more a grouping of functionalities to help users in picking some interesting subsets. One issue with including dependencies is that features will force a specific version of each deps, which may then later cause conflicts because some other bundle require a different version.
I see this more as an issue of product launch failing at including necessary dependencies.

**Comment by laeubi** [comment]
>  then it means that the m2e feature should also include the platform feature

it should actually list perquisites in the "dependency" section (currently empty).

>  One issue with including dependencies is that features will force a specific version of each deps, which may then later cause conflicts because some other bundle require a different version

But that's actually a limitation of the feature file-format and I suppose that "how platform works"... but it seems dependencies could specify version ranges in some kind.

My product currently includes pde, jdt nad platform but m2e requires guava 27 and platform does not require this by default, so I'm forced to write a feature my own that includes "a very specific version" and that's just contrary to "grouping of functionalities to help users in picking some interesting subsets".

**Comment by laeubi** [comment]
It seems also some feature dependencies are not declared, if I use "add required" I still get missing bundles:

![grafik](https://user-images.githubusercontent.com/1331477/116403417-d24a2000-a82d-11eb-90e7-f1425aec3fb1.png)

**Comment by mickaelistria** [comment]
> it should actually list perquisites in the "dependency" section (currently empty).

That the purpose of p2 to resolve transitive dependencies and allow features to not explicitly declare every dependency.

**Comment by laeubi** [comment]
but whats the purpose of the dependency section then? Fact is, it is currently not possible to use the m2e feature without some magic knowledge....

**Comment by mickaelistria** [comment]
> but whats the purpose of the dependency section then?

It's more or less to add extra requirements on things that do not come as transitive deps by lack of Require-Bundle/Import-Packages (eg more general Require-Capability that p2 isn't able to process).

m2e feature is included in several EPP products successfully. So I wouldn't say "not possible".
I have the impression that it's more PDE's "Validation" process that's failing at properly processing the product definition and at dealing with transitive dependencies. As fas as I know, building a product wth Tycho just resolves and include those transitive deps as expected.

**Comment by laeubi** [comment]
Nope you'll end up with a product that simply has missing dependencies and don't start. If you take a look at https://ci.eclipse.org/m2e/job/m2e/job/PR-181/2/console it indeed validates things if I add them to the requirements....

Sure it is possible to configure it somehow, but please try the following:

1. create an empty product (feature based)
2. add m2e feature+platform+jdt
3. validate the product -> fails
4. use "add required" -> still fails but adds some features that are marked as required

so for me it seems as if it is expected to declare requirements for PDE tooling to work. There is even a "caclulate dependecies" that adds required bundles + an option to automatically update them. So it seems that PDE is capable of determine them.

The Eclipse help says:
> The Dependencies page lists all Required Features and Plug-ins that must be present in the product before the feature can be installed. If any of these pre-requisites are missing, the feature will not be installed.

**Comment by mickaelistria** [comment]
We want some flexibility in deployment and don't want to enforce a feature or another to users. (Unlike Tycho that works well) PDE doesn't leverage p2 to compute a valid set of dependencies; that's a pity but not something we should bend m2e for.
