### ISSUE TITLE
Bug 441978 - Snapshot sources/javadoc not updated with "Force Update of Snapshots/Releases"

### ISSUE THREAD

**Issue by rhoehener** [eclipse-m2e/m2e-core#188]
https://bugs.eclipse.org/bugs/show_bug.cgi?id=441987 (2014)
https://bugs.eclipse.org/bugs/show_bug.cgi?id=367758 (2012)

**Comment by mickaelistria** [comment]
Fixed with #238

**Comment by mickaelistria** [comment]
I merged a related change which is available in latest snapshots. Please give it a try and report here if you see any issue regarding "force updates"
