### ISSUE TITLE
Eclipse 2021-06M2 has no maven console output with embedded maven

### ISSUE THREAD

**Issue by dstango** [eclipse-m2e/m2e-core#191]
I'm playing around with the newest eclipse milestone.

When I want to build a project (e.g. clean install) with the embedded maven, the usual console output is not showing up. Instead SLF4J pops up complaining that StaticLoggerBindings are no longer supported:
```
SLF4J: No SLF4J providers were found.
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#noProviders for further details.
SLF4J: Class path contains SLF4J bindings targeting slf4j-api versions prior to 1.8.
SLF4J: Ignoring binding found at [jar:file:/C:/Java/eclipse-2021-06-M2/plugins/org.eclipse.m2e.maven.runtime.slf4j.simple_1.16.0.20200610-1735/jars/slf4j-simple-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#ignoredBindings for an explanation.
```

The build actually seems to run fine - yet the output is missing.

The issues seems to affect also the m2e maven console, as no messages show up if I want to do a maven-pom-update with ATL-F5.

Starting a build with an external maven works fine.
(I like to use the plugins "ANSI Escape in console" and "m2e-chromatic" for colored output, but they seem not to be involved: I double-checked by uninstalling them an the issue still persists.)

**Comment by dstango** [comment]
Just saw this is a duplicate of https://github.com/eclipse-m2e/m2e-core/issues/182.

**Comment by akurtakov** [comment]
Dup of #182.
