### ISSUE TITLE
Content on https://www.eclipse.org/m2e/ is heavily outdated

### ISSUE THREAD

**Issue by rolfth** [eclipse-m2e/m2e-core#192]
The web page has 'copyright 2016' so assuming that it didn't have a proper update in years. Every page seems outdated:
- 'News': latest entry in 2018 (release 1.9.0)
- 'Documentation': Every entry mentions old releases
- 'Community': Links to no longer available Bugzilla projects and Github repositories.

**Comment by akurtakov** [comment]
Do you want to help with bringing it uptodate? Web page lives in https://git.eclipse.org/c/www.eclipse.org/m2e.git/

**Comment by rolfth** [comment]
Sorry, don't know enough about the m2e project to add something meaningful here. Rather like spend my time on Eclipse Platform instead of updating outdated documentation, especially if its only a afterthought when migrating to new infrastructure. It already takes me too much time to just divert issues to the right locations (projects), which is increasingly difficult by projects moving to other locations without leaving a proper trail.

**Comment by mickaelistria** [comment]
The "community" link should now redirect to the GitHub repo.
On the long term, we'll try to migrate all necessary documentation into the GitHub repo and just remove the website; which is not a criterion of success and is more complicated to maintain and track than documentation in Git repo.
