### ISSUE TITLE
replace github.com gh-pages links to github.io in m2e-discovery-catalog

### ISSUE THREAD

**Issue by jpraet** [eclipse-m2e/m2e-core#200]
See https://github.com/takari/m2e-discovery-catalog/issues/67

There are a lot of links in the catalog referencing gh-pages at github.com,
for example https://m2e-code-quality.github.com/m2e-code-quality/site/latest/.

These links [no longer work](https://github.blog/changelog/2021-01-29-github-pages-will-stop-redirecting-pages-sites-from-github-com-after-april-15-2021/) and should be replaced by github.io.

![image](https://user-images.githubusercontent.com/2212615/118497277-36714d00-b725-11eb-8996-16e1b0753284.png)

Connectors refering to gihub.com are greyed out in the wizard:

![image](https://user-images.githubusercontent.com/2212615/118497474-64ef2800-b725-11eb-8890-52f70946b598.png)

**Comment by mickaelistria** [comment]
Thanks. Can you please submit a PR against https://github.com/eclipse-m2e/m2e-discovery-catalog/blob/master/org.eclipse.m2e.discovery.oss/connectors.xml to fix the URLs?
