### ISSUE TITLE
New using lemminx editor with POM editor source format not working 

### ISSUE THREAD

**Issue by gayanper** [eclipse-m2e/m2e-core#205]
When using the lemminx editor with POM editor by altering the feature configurations, the source formatting action in generic editor doesn't work. But when opening the pom file in generic editor it works fine.

**Comment by vrubezhny** [comment]
@gayanper Could you please provide steps to reproduce for the issue? 

In my case, using WWD+M2E Core gives two editors for editing pom.xml files - "Maven POM Editor" and "Generic Text Editor" - and "Source->Format" action works fine in any of these either they are opened both at the same time or one by one. 
So, could you please specify your configuration and steps for reproducing the issue?

**Comment by gayanper** [comment]
I’m running the Eclipse SDK i-builds and using generic editor inside the POM editor as the source editor. This done by removing the SSE xml editor from the installation.

**Comment by vrubezhny** [comment]
An upstream issue is created in order to track this issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=574396

**Comment by mickaelistria** [comment]
Thanks Victor. There is no action to take from m2e to fix the issue. People can already get the fix by installing latest snapshots of LSP4E. This bug will progressively vanish when LSP4E is released and gets part of Wild Web Developer and SimRel so more and more users get LSP4E with the fix.

**Comment by httpants** [comment]
I've recently installed eclipse 2022-03 and encountered this issue.  I checked which version of lsp4e is included with 2022-03 and it's the latest version from http://download.eclipse.org/lsp4e/releases/latest/

**Comment by gnl42** [comment]
Still seeing this problem with 2202-06

**Comment by gnl42** [comment]
Also ctrl-shift-c (comment) makes a mess of if

**Comment by mickaelistria** [comment]
There have been some major improvements in LemMinX lately regarding formatting. It will take a bit of time for those change to be included in Eclipse Wild Web Developer and m2e unless someone is willing to work on that topic; but this will eventually get better when adoption of newer LemMinX is complete.

**Comment by gnl42** [comment]
One way or the other I've tried it out every since it started showing up as an option, and every time I've replaced it with the "old" version since it was too broken.

I don't understand why it is offered as an option when it is not ready for prime time ? And why it is not described as the 'buggy beta version'?
