### ISSUE TITLE
Make it easier to copy Maven dependencies to target

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#212]
Would be nice if we could easier copy Maven dependencies to the target platform:

For example I have the following in my pom.xml file.
````
<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-server</artifactId>
			<version>11.0.3</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-servlet</artifactId>
			<version>11.0.3</version>
		</dependency>

````

It would be nice if I could simply paste it to my target platform:

````
	<location includeDependencyScope="compile" includeSource="true" missingManifest="generate" type="Maven">
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-server</artifactId>
			<version>11.0.3</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-servlet</artifactId>
			<version>11.0.3</version>
		</dependency>
		</location>		
````
Instead I have to convert it into two location entries:

````

	<location includeDependencyScope="compile" includeSource="true" missingManifest="generate" type="Maven">
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-server</artifactId>
			<version>11.0.3</version>
		</location>		
			<location includeDependencyScope="compile" includeSource="true" missingManifest="generate" type="Maven">
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-servlet</artifactId>
			<version>11.0.3</version>
		</location>		
````

Not a big thing, but it would make moving deps from Maven to Eclipse plug-in much easier IMHO.

**Comment by laeubi** [comment]
> Not a big thing

Currently one entry is one dependency as otherwise the UI would be much more complicated. So the very first thing to make this happen would be think about how the UI should looks like to make the user capable of adding/removing/managing multiple dependency entries.

**Comment by laeubi** [comment]
Prototype UI  for managing multiple dependencies
![grafik](https://user-images.githubusercontent.com/1331477/126075863-ee075afb-c4e1-423d-acc0-8174905378dd.png)

**Comment by mickaelistria** [comment]
I don't think tabs scale enough for this user story. A master-details pattern with a FilteredTree listing GAVs on the left part would be more usable.

**Comment by laeubi** [comment]
It depends a bit how this feature is used, I think we can start with this simple UI and improve it later if it is clearer how this is used by people or if it is more common to simply use the Source-Editor instead of the graphical one.

**Comment by laeubi** [comment]
This is how it looks like in the source now, old formats are automatically converted
```
<target name="multipleElements">
<locations>
	<location includeDependencyScope="compile" includeSource="true" missingManifest="generate" type="Maven">
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-server</artifactId>
			<version>11.0.3</version>
			<type>jar</type>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jetty</groupId>
			<artifactId>jetty-servlet</artifactId>
			<version>11.0.3</version>
			<type>jar</type>
		</dependency>
	</location>
</locations>
</target>
```

**Comment by laeubi** [comment]
![grafik](https://user-images.githubusercontent.com/1331477/126106751-892626dc-46d5-45a5-841b-beff82085de0.png)

**Comment by laeubi** [comment]
@vogella m2e snapshot + tycho snapshot now support this, please test and give feedback if anything is missing

**Comment by vogella** [comment]
Thanks for this enhancement.

Would be nice if the snapshot update site could be easier to find-> #281

**Comment by vogella** [comment]
AFAICS the copy from clipboard functionality does not work anymore with the new UI. Opened #289 for this.
