### ISSUE TITLE
Synchronize and maybe unify target definitions into one

### ISSUE THREAD

**Issue by HannesWell** [eclipse-m2e/m2e-core#214]
With commit bbea072d694a386269ce20e0c85dce7e98f92581 the target definition `target-platform.target` and `dev-workspace.target` went out of sync (i.e. in the locations for `https://download.eclipse.org/eclipse/updates` and `https://download.eclipse.org/tools/orbit`).

This made me think about if those to target-definitions could be merged into one.
The difference between these to is that the `dev-workspace.target` contains sources, the maven-runtime bundles and the   `org.eclipse.sdk` feature additionally to the content of `target-platform.target`.
Having those in the target-platform used for builds should not have a negative impact on the out-come of the build and could only slightly increase the runtime of dependency resolution (I did not measure a difference at my computer, both took 3:06min, when all dependencies are fetched).

In favor of avoiding problems due to not synchronized target definitions and the synchronization effort, I suggest to merge those to target definitions into one.

Furthermore the maven-runtime bundles could be removed from the target-platform used in the workspace because with the Oomph setup they are imported into the workspace anyways. So if you consider using the Oomph setup as default, I suggest to remove the runtime-bundles from the TP.

I can provide a PR if you agree.

**Comment by laeubi** [comment]
> This made me think about if those to target-definitions could be merged into one.

Good idea, tycho can be configured to ignore sources even if the are enabled in the target. Instead of the org.eclipse.sdk a reference to the current eclipse can be used (`<location path="${eclipse_home}" type="Profile"/>`) what will then be ignored by tycho as well...

**Comment by HannesWell** [comment]
> Good idea, tycho can be configured to ignore sources even if the are enabled in the target. 

Thanks for that hint. I didn't know yet that this is possible. You mean the [`target-platform-configuration` plugin's `filter` parameter](https://www.eclipse.org/tycho/sitedocs/target-platform-configuration/target-platform-configuration-mojo.html#filters)?

>Instead of the org.eclipse.sdk a reference to the current eclipse can be used (`<location path="${eclipse_home}" type="Profile"/>`) what will then be ignored by tycho as well...

That would be one solution. But I'm not a big fan of using the current eclipse as part of the target-platform because it makes the target-platform depended of your running eclipse. And this in turn can lead to problems if your development eclipse is not the one the m2e in workspace target to. So I would prefer to filter out the `org.eclipse.sdk`, if necessary.
The question is, if it is necessary to filter out the SDK feature? Since the filtering happens after the dependency resolution there is no runtime saved. The only advantage I see, is to avoid potential conflicts? But is this a high a likely case?

But would any of the filters below do the job? And would it also filter the transitive dependencies of the skd:
```
<filter>
  <type>eclipse-feature</type>
  <id>org.eclipse.sdk</id>
</filter>
<filter>
  <type>p2-installable-unit</type>
  <id>org.eclipse.sdk.feature.group</id>
</filter>
```

Another problem is that the maven-runtime bundles in the workspace are never considered in the workspace PDE-build because they are only Maven projects and not Eclipse PDE plug-ins. At the moment all other m2e plug-ins are compiled (in the workspace!) against those from the target platform which are latest released once (probably the latest snapshots would be better).
I learned this the hard way while testing #182.
Of course it would be best if those in the workspace would be used but I think this requires more changes (the jars have to be fetched, the manifest has to be written etc. and in the end it has to be a valid PDE plugin, created by maven) and I'm sure this was previously attempted and would have been completed if it were possible.

My quick workaround to get local maven-runtime bundles in the TP was to use corresponding maven targets, which fetch my local maven-repo. But this has the disadvantage that you have to run the maven build, keep the versions in the tp in sync and have to reload the TP in order to make changes visible in the workspace or if you launch an Eclipse-Application to test the latest changes at the runtime.

**Comment by laeubi** [comment]
> You mean the [`target-platform-configuration` plugin's `filter` parameter](https://www.eclipse.org/tycho/sitedocs/target-platform-configuration/target-platform-configuration-mojo.html#filters)?

See [targetDefinitionIncludeSource](https://www.eclipse.org/tycho/sitedocs/target-platform-configuration/target-platform-configuration-mojo.html#targetDefinitionIncludeSource) (its just badly documented in the HTML as oyu can't see the values for [IncludeSourceMode](https://github.com/eclipse/tycho/blob/master/tycho-bundles/org.eclipse.tycho.core.shared/src/main/java/org/eclipse/tycho/core/resolver/shared/IncludeSourceMode.java).

>  But I'm not a big fan of using the current eclipse as part of the target-platform because it makes the target-platform depended of your running eclipse. And this in turn can lead to problems if your development eclipse is not the one the m2e in workspace target to

m2e should work on a wide variety of eclipse versions and in the context of a setup.file we setup an IDE specifically for that purpose. But using the exclude option might be another option...

**Comment by mickaelistria** [comment]
it's not an issue if `.source` file are in the build target platform. They won't participate anyway as long as nothing in build does require them.

**Comment by HannesWell** [comment]
> See [targetDefinitionIncludeSource](https://www.eclipse.org/tycho/sitedocs/target-platform-configuration/target-platform-configuration-mojo.html#targetDefinitionIncludeSource) (its just badly documented in the HTML as oyu can't see the values for [IncludeSourceMode](https://github.com/eclipse/tycho/blob/master/tycho-bundles/org.eclipse.tycho.core.shared/src/main/java/org/eclipse/tycho/core/resolver/shared/IncludeSourceMode.java).

Thanks. For whatever reason I was thinking of sources in the terms of origins of artifacts not in terms of source-code.
But since source artifacts are ignored anyway, as Mickael stated, I would keep it simple and not exclude them.

> 
> m2e should work on a wide variety of eclipse versions and in the context of a setup.file we setup an IDE specifically for that purpose. But using the exclude option might be another option...

That's a point. So I will implement, whichever you prefer. In doubt I would take the simpler approach.


Another problem at the moment is that, the maven-runtime-bundles have to be included in the target-platform. Otherwise some plug-ins do not compile since the maven-runtime projects are pure Maven projects and therefore do not participate in the PDE workspace build. I already tired out to find a solution and just opened issue #223.

**Comment by mickaelistria** [comment]
> get local maven-runtime bundles in the TP was to use corresponding maven targets, which fetch my local maven-repo. But this has the disadvantage that you have to run the maven build, keep the versions in the tp in sync and have to reload the TP in order to make changes visible in the workspace or if you launch an Eclipse-Application to test the latest changes at the runtime.

This wouls be a major improvement over the current state, and is the best proposal on that topic IMO. So despite the glitches (sich as the need to refresh and so on), which should be documented the existing doc files and why not also in .target and m2e-maven-runtime/pom.xml files, it would still.be a good step forward.
I'd gladly review and merge a PR for that.

**Comment by HannesWell** [comment]
> This wouls be a major improvement over the current state, and is the best proposal on that topic IMO. So despite the glitches (sich as the need to refresh and so on), which should be documented the existing doc files and why not also in .target and m2e-maven-runtime/pom.xml files, it would still.be a good step forward.
> I'd gladly review and merge a PR for that.

Great.
But since issue #223 would make maven-runtime bundles in the target-platform completely obsolete, I suggest to wait until that issue is closed. In the undesired case, that issue is not successful we can fall back to that solution including the mentioned documentation.

**Comment by mickaelistria** [comment]
I fear #223 is a bit more complicated and can take more time to be resolved. This one seems to already increase the value more easily. I recommend we work on this one as a 1st good step that will already be beneficial to others in the meantime while we cover #223.

**Comment by HannesWell** [comment]
> I fear #223 is a bit more complicated and can take more time to be resolved. This one seems to already increase the value more easily. I recommend we work on this one as a 1st good step that will already be beneficial to others in the meantime while we cover #223.

Agree on that. I've just opened a PR to implement it.

**Comment by mickaelistria** [comment]
PR merged, thanks a lot!
