### ISSUE TITLE
Failing test testDownloadSources_006_nonMavenProject should be disabled

### ISSUE THREAD

**Issue by cal101** [eclipse-m2e/m2e-core#222]
Does anyone have any objections against disabling the testDownloadSources_006_nonMavenProject test?

It fails for quite some time and just documents a long standing bug in the used libraries as far as I understand.

https://ci.eclipse.org/m2e/job/m2e/job/master/11/testReport/org.eclipse.m2e.tests/BuildPathManagerTest/testDownloadSources_006_nonMavenProject/

I find it annoying looking into the failing PR tests just for looking if anything else fails IN ADDITION.

If no objections arrise I can provider a PR that disables the test.

Suggestions for the comment explaining the reason to disable the test welcome.

**Comment by mickaelistria** [comment]
Yes, I have objection. It mustn't be disable, it has to be fixed.
