### ISSUE TITLE
[Maven-runtime projects] Generate Eclipse plug-ins meta-data and include them in m2e-core build

### ISSUE THREAD

**Issue by HannesWell** [eclipse-m2e/m2e-core#223]
At the moment the projects in `m2e-maven-runtime` are pure Maven projects. Because they aren't Eclipse plug-ins, they do not participate in a Eclipse Workspace's PDE build and therefore bundles like `org.eclipse.m2e.maven.runtime` are only considered from the target platform and not from the workspace. This has the down-side that the maven-runtime bundles have to be part of the target-platform and it is not sufficient to have them in the workspace.
Additionally if you modify the maven-bundles in the workspace and want to test them e.g. by launching an Eclipse-Application, you first have to get them into the target-platform (the known maven-install procedure and then you can include them for example using a Maven-target). This is quite cumbersome.

Therefore I suggest to generate the required Metadata files (driven by Maven) to make the maven-runtime projects full Eclipse-plugins too. 
This requires mainly two things: the nested jars need to be fetched and the MANIFEST.MF need to be generated into the META-INF folder.
For the latter a m2e-profile is already present in the `m2e-maven-runtime/pom.xml` but this does not seem to have any effect in my workspace. I suspect that's because the `bundle` goal of the maven-bundle-plugin is not specified explicitly as execution (does m2e even honor lifecycle goals automatically?). But even if it is covered my Eclipse did not find a connector for it.

However the jar fetching could be done, using the `copy-dependencies` goal of the `maven-dependency-plugin` and the manifest generation by using the `manifest` goal of the maven-bundle-plugin. I've already done some prototyping for the `org.eclipse.m2e.maven.runtime` in my [m2e-fork](https://github.com/HannesWell/m2e-core/commits/runtime).
I still have to experiment which project natures and builders are required (maybe the .project file needs to be commited) and if the jars need to be added solely to the `.classpath` in order to make it a fully functional Eclipse plugin that participates in the PDE workspace builds and can be used in launched Eclipse applications.

If you like this idea, I continue to fully implement it.

Besides that I want to suggest to integrate the maven-runtime projects into the maven build of m2e-core so that those projects don't have to be build separately. Are there general objections against that? It would have the advantage that only one build is required and configurations/versions/properties can be inherited.

**Comment by mickaelistria** [comment]
That's a great goal, and the implementation seems to be on the right track.
My only concern is the redundancy of exclusions; which ultimately can lead to inconsistency that will be hard to understand and debug. I'd rather see a solution which doesn't carry such risk.
I imagine that instead of the pom.xml redefining a MANIFEST and nested jars, we could instead just have a `pde` profile (turned on by default via project settings) that would take place *after* packaging and would just extract the MANIFEST.MF and the jars from the built bundle, With this approach, we have less risk of un-synchronizing build vs iDE content.
What do you think?

**Comment by HannesWell** [comment]
> That's a great goal, and the implementation seems to be on the right track.

I'm glad that you like the suggestion.

> My only concern is the redundancy of exclusions; which ultimately can lead to inconsistency that will be hard to understand and debug. I'd rather see a solution which doesn't carry such risk.

That's definitely a thing I also want to avoid. Therefore my goal is also to include the maven-runtime bundles in to the regular m2e-core build so there is no need to have them in the target-platform or the have them as maven dependencies. So there should be no exclusion at all (if you meant that?).

But I have to admit that I have to experiment if it (mainly the dependency resolution) works in a tycho build if eclipse-plugins and maven-projects/modules are mixed together and the maven-projects are OSGi bundles in the end but do have packing type `jar` and not `eclipse-plugin` and the MANIFEST.MF is generated during build. I've never done or seen something similar before (maybe that's a sign). I expect an initial pass before the actual build will still be necessary to generate the manifest (and maybe other files). But at least some configuration can be inherited.
But that's actually the second step.

> I imagine that instead of the pom.xml redefining a MANIFEST and nested jars, we could instead just have a `pde` profile (turned on by default via project settings) that would take place _after_ packaging and would just extract the MANIFEST.MF and the jars from the built bundle, With this approach, we have less risk of un-synchronizing build vs iDE content.
> What do you think?

You mean a Maven-profile named `pde` that is listed as in the `Active Maven Profiles` List  under the Maven node of the project's preferences?
I've never used it actively, but shouldn't an `m2e` profile like below have the same effect?
```
<profile>
	<id>m2e</id>
	<activation>
		<property>
			<name>m2e.version</name>
		</property>
	</activation>	
</profile>
```

However your suggestion to unpack the jar was also my first thought. But unfortunately there is no lifecycle-mapping for the `bundle` goal of the `org.apache.felix:maven-bundle-plugin`. At least my Eclipse does not find any and I don't know any. So this seems not to be feasible for me.

But since there is a mapping for the maven-bundle-plugin's `manifest` goal I split the manifest generation and retrieval of the nested jars into the plugin execution (which are both covered by existing maven life-cycle mappings).
The result of both goals is placed in a location that PDE understands too. Those steps are the same in the IDE and during Maven-build. The final step of the maven build is then to assemble the jar from the usual "PDE known" locations. 
So this is kind of the reverse process but it should lead to the same results in both situations.
That was the motivation/intention with the currently proposed approach.

**Comment by laeubi** [comment]
Mostly the runtime-bundles seem to integrate existing OSGi artifacts that are not available as P2-sites.
Maybe it would be better to leverage the m2e-pde integration to pull those in instead of the maven-bundle-plugin?

**Comment by mickaelistria** [comment]
> However your suggestion to unpack the jar was also my first thought. But unfortunately there is no lifecycle-mapping for the bundle goal of the org.apache.felix:maven-bundle-plugin. 

Have you tried configuring the pom to just "execute" the mojo on full build?

> Mostly the runtime-bundles seem to integrate existing OSGi artifacts that are not available as P2-sites.

Most Maven artifacts are not OSGi bundles, they use Plexus DI and other component approach that is not working well with OSi as they expect flat classpath. We should really avoid the path of OSGifying Maven, it's more or less a dead end; and if it's not it would have to be a full project on its own with months of work before a completely usable reuslt.
We do need to embed the Maven jars "as is" to ensure the embedded Maven behaves closelyy enough to the official Maven. Unless I missed something, this is not the purpose of the m2e-pde integration, and maven-bundle-plugin is still better at it..

**Comment by HannesWell** [comment]
> 
> Mostly the runtime-bundles seem to integrate existing OSGi artifacts that are not available as P2-sites.
> Maybe it would be better to leverage the m2e-pde integration to pull those in instead of the maven-bundle-plugin?

Even tough I like the idea, I agree with Mickael that we should stick as close as possible to original Maven. In the end this is probably the simpler and more reliable way.

> > However your suggestion to unpack the jar was also my first thought. But unfortunately there is no lifecycle-mapping for the bundle goal of the org.apache.felix:maven-bundle-plugin.
> 
> Have you tried configuring the pom to just "execute" the mojo on full build?
> 
No, not yet but this should be an option.

But I would also like to integrate the build of the Maven-runtime components into the `m2e-core` build.
This has the advantage that a lot of configuration can be inherited from the `m2e-core/pom.xml` and less synchronization is required. And additionally a git installation is not required because jgit timestamp provider could be used.
But this requires the maven-runtime projects to be Eclipse plugins since building Maven-project and Eclipse plug-ins is, as far as I know, not supported by Tycho. And even if it would be possible (e.g. by disabling the tycho-maven-plugin somehow), the Maven projects could not referenced by Eclipse plug-ins because their OSGi meta-data are not present during the initial resolution. But please correct me if I'm wrong.

With this approach a first initial maven run still required to generate the OSGi meta-data and to fetch the jars (during build and in the IDE). For this the `maven-bundle-plugin:bundle` goal could be used and then the jars could be unpacked. Alternatively we could use the `maven-bundle-plugin:manifest` goal to generate the manifest and the `maven-dependency-plugin:copy-dependencies` to fetch the dependency jars. Both have their pros and cons.
In either way the maven-runtime projects would be build as ordinary Eclipse-plugins during, the m2e-core build, where the manifest provides the meta-data and the build.properties file controls the included files etc.

The most difficult part in this approach is from my point of view the generation of the `.classpath` file to resolve the errors in the IDE. The `.project` and the `build.properties` won't change without general changes of that maven-runtime projects. But the .classpath file changes, when the maven version changes. Therefore I would like to generate it in the IDE. The key point is to add the jar files in the jars folder.
I recognized that a lib entry for each jar in the jars folder is sometimes automatically added but I could not find out yet who exactly is responsible for that and which events trigger it. I suspect it is derived by PDE from the `Bundle-classpath` entries in the MANIFEST.
However to make the `.classpath` generation more predictable I think about using an ant-task to generate the .classpath. This way a clean generation can forced by running the "initial meta-data generation maven build" in the Oomph setup.

A second approach would be to stick with the current approach and build the maven-runtime projects as Maven projects before the m2e-core build, just like it is at the moment. In this approach it should also be possible to inherit from the `m2e-core/pom.xml` to avoid duplicated configuration. We could leverage that a project need not to be a module of its parent pom.
In the IDE, from the maven-runtime jars build initially the MANIFEST and nested jars would have to be extracted in a way that the projects become valid Eclipse plug-ins.
In this approach the `.classpath` file still needs to be generated, the `.project` file can be committed and the `build.properties` file should be irrelevant.

The downside of this approach is that the maven-runtime bundles have to remain in the target-platform and a local git installation is required in order to build the build-qualifier.
Besides that I see no significant difference in both approaches. Both require an additional maven run to prepare the maven-runtime bundles, both require some extra steps for the use in the IDE (mainly to generate the `.classpath` consistent and reliably).

Therefore I'm in favor of the first approach because it avoids the need to synchronize the maven-runtime versions in the target platform and does not need a local git installation.

**Comment by HannesWell** [comment]
But as a first step I would like to start with formatting all poms and to let `m2e-maven-runtime/pom.xml` inherit from the `m2e-core/pom.xml`. This should be possible with both approaches.

Besides that, as preparation for the further improvements, I would like to embed the nested jars in a `jars` folder in the archetype.commons and maven.indexer bundle, too.
