### ISSUE TITLE
[Update-site] include all versions in the 'releases' and 'snapshots' updatesites

### ISSUE THREAD

**Issue by HannesWell** [eclipse-m2e/m2e-core#224]
The composite repositories `releases` and `snapshots` in `https://download.eclipse.org/technology/m2e/` do not specify all of the nested version folders as their child.
The releases repo contains only versions up to 1.15, the snapshot repo only contains the version 1.12 and 1.13.
If they would contain all nested repos as their child it would have the advantage that one can reference the composite and get the latest release or snapshot updates from the site automatically.

For example the snapshots repo is used in the m2e-core setup and its URL has to be updated with each release at the moment.

Furthermore I ask my self if it is necessary to have snapshot repos for each released version?
I know (p2) repos should never change their content, but they do not add real value because for all versions but the latest the content should be equal to the corresponding releases repo?
From that I think there should only be one snapshot repo that contains the latest master branch build and is replaced with each new build. So users that want the latest snapshot can use that repo.

A scenario were you want the latest snapshot but only until the the next release seems to be not very relevant to me, but please correct me if I'm wrong. I would use snapshots only for prototyping/testing/dog-feeding, so in an environment were I can change to the corresponding release, that contains the brand new feature/bug fix I only wanted, once it is published.

**Comment by mickaelistria** [comment]
IMO, we should simply remove the composite repositories.

**Comment by HannesWell** [comment]
For the snapshot repo I agree with you. Especially since m2e does not require them anymore since #228 is merged.

But for the `releases` repo, I think the situation is different and I find composite-repos very handy. For example I've include m2e in several Oomph setups in conjunction with Eclipse products that don't include m2e. For the eclipse products I've selected latest-released as version so the installations are updated automatically. But for m2e these setups have to be adjusted with each release. If I forget it, m2e stucks with an old release. I think others are probably in comparable situations.
Having a composite repo with all releases (especially the latest) would be much more convenient.

From a maintainers point of view it would be best if a new release would be added automatically when it is deployed. 
I'm not fully aware of the deployment process, but if you guide me, I can work on a solution.

Alternatively a `releases/latest` sub-repo could be provided, which either is a copy of the latest release repo or could be a composite with a single child pointing to the latest version. Then at each release only the pointer would have to be updated.

**Comment by mickaelistria** [comment]
> From a maintainers point of view it would be best if a new release would be added automatically when it is deployed.
I'm not fully aware of the deployment process, but if you guide me, I can work on a solution.

The promotion job is https://ci.eclipse.org/m2e/job/promote-snapshots-to-release/configure . Here could be placed some extra steps to edit te composite repo.

> Alternatively a releases/latest sub-repo could be provided, which either is a copy of the latest release repo 

There is already https://download.eclipse.org/technology/m2e/releases/latest/

**Comment by HannesWell** [comment]
> > Alternatively a releases/latest sub-repo could be provided, which either is a copy of the latest release repo
> 
> There is already https://download.eclipse.org/technology/m2e/releases/latest/

Pardon me, but somehow I oversaw/forgot this.
In this case I agree: The composite repos can be removed. The latest repo can serve the same purpose. And since it is there we should not remove it and replace it with a more complicated to maintain repo.

But in contrast what I've said before I think a `snapshot/latest` repo would be useful for m2e itself, since we use the latest snapshot of m2e in the Oomph setup. So in order to not have to update the setup with every release I suggest to add a `snapshot/latest` repo.

I can provide a PR to adjust the Jenkinsfile to deploy the repo to `https://download.eclipse.org/technology/m2e/snapshot/latest/` too.
Somebody with the corresponding modification rights has to perform the removal of the composite repos.

**Comment by mickaelistria** [comment]
We're done here thanks to #230 ; latest snapshots published at https://download.eclipse.org/technology/m2e/snapshots/latest/

**Comment by HannesWell** [comment]
Thanks for reviewing and merging.

Do you still want to remove the composite repos? Since they are not updated to the newest versions users may wonder why they don't get the latest versions, so I would also vote for removing them.
Or do you want to avoid to _break_ existing usages, even tough I think it wont be that bad?
When the URL's target site is not available the update-manager simply says that the site does not exist.

**Comment by HannesWell** [comment]
I've changed my opinion regarding the deletion of the composite repositories.
It is not only handy to have always the latest version (for this the `releases/latest` repo is sufficient),
it also, I tend to say absolutely, necessary when you want to install m2e in an older version of Eclipse.

It is likely that the latest version of m2e can only be installed with the latest eclipse, since we use the latest eclipse SDK in the m2e target-platform (actually we should set the lower bounds for all dependency to the currently available version, but that's another worth another issue).
Therefore if you want to install m2e into an older Eclipse, you probably need an older version of m2e.
But at least I don't want to search old release repos one by one, hoping to find the one that contains the suitable version.
So a repository is necessary that contains all versions of m2e and P2 can to its job and the search for us.

Nevertheless I think we should keep the `releases/latest` repo pointing to the latest release in order to speed up the resolution for users that are sure that they want the latest version.

**Comment by HannesWell** [comment]
@mickaelistria I can take care of this and I know about the [P2 Ant-Tasks to manage composite-repositories](https://wiki.eclipse.org/Equinox/p2/Ant_Tasks#Composite_Repository_Task), but can you tell me how I can run them on the web-server?
As far as I know the P2-Ant-task can be run using the `org.eclipse.ant.core.antRunner` application. But this requires an Eclipse installation or at least Maven (using the `tycho-eclipserun` to run the `antRunner` also does the job).

If you know a 'working example' that already does this, it would be great to know.

**Comment by mickaelistria** [comment]
I perceive efforts to facilitate people in sticking to older releases as one of the most harmful thing an OSS project can do to self. So I won't really support actively this idea.
But if you find a solution, you can look at the jobs on ci.eclipse.org/m2e to add what's needed where needed.

**Comment by HannesWell** [comment]
> I perceive efforts to facilitate people in sticking to older releases as one of the most harmful thing an OSS project can do to self. So I won't really support actively this idea.

That's indeed a valid point.

> But if you find a solution, you can look at the jobs on ci.eclipse.org/m2e to add what's needed where needed.

I did not find a quick solution to create the composite repositories in the existing Jenkins jobs of m2e, so I agree we should not provide them. But I wonder how they were maintained before? Manually?

Since the existing composite-repo files are outdated, should I delete them (or at least move them to `archive.eclipse.org`)?

**Comment by mickaelistria** [comment]
> But I wonder how they were maintained before? Manually?

Yes, via some SCP or SFTP access. But Eclipse Foundation doesn't allow such access these days. So changes have to be done from Jenkins with freestyle jobs, which are allowed to access the download area via scp.

> Since the existing composite-repo files are outdated, should I delete them (or at least move them to archive.eclipse.org)?

Moving to archive would basically delete them (ie previously working URLs would now give a 404). So deleting is IMO enough.

**Comment by HannesWell** [comment]
I noticed (because of Ed's bug-report) that you have already taken care of deleting the composites and created the [Jenkins Job download-cleanup](https://ci.eclipse.org/m2e/job/download-cleanup/).

The composite files for the release repo are still there but I thought they should be removed as well?
Besides that we could consider to remove the milestone repositories as well.

Furthermore I suggest to update the `promote-snapshots-to-release` job to delete the `m2e/snapshots/${releaseVersion}/latest` repo upon release. With the next successful build of the master branch a new repo `m2e/snapshots/${nextVersion}/latest` is created. So there are always only two snapshot repositories available:
1. `m2e/snapshots/${versionUnderDevelopment}/latest`
2. `m2e/snapshots/${releaseVersion}/latest`

They both have the same content, but I think they are useful in case you want only the snapshots for the version being developed at the moment (e.g. because you want a certain bug-fix) and want to return to the release train after the next release.
Then you specify `m2e/releases/latest` and `m2e/snapshots/${versionUnderDevelopment}/latest` repository as available update-sites. As soon the release is performed the referenced snapshot-site is not available any more and you don't accidentally go into the next snapshot cycle because you forgot to remove the snapshot/latest site.

If you agree I can offer to update the `download-cleanup` to remove the releases composite*.xml files and the `promote-snapshots-to-release` job to remove `m2e/snapshots/${versionUnderDevelopment}/latest`. I won't run them so you can review if you want to. If you agree on the milestones I can include them for removal as well.

**Comment by mickaelistria** [comment]
I'm fine will all that.
As committer, you should already have the permission to edit/run the download-cleanup job. As long as you do not delete the latest release, it's all good to me.

**Comment by HannesWell** [comment]
I have deleted
- `releases/compositeArtifacts.xml`
- `releases/compositeContent.xml`

I also tried to delete the entire milestones folder with all its specific repos, but it failed with permission-denied errors: https://ci.eclipse.org/m2e/job/download-cleanup/5/
Do you know why this is the case or have we can get permission to delete those files?

Furthermore I have updated the [promote-snapshots-to-release job](https://ci.eclipse.org/m2e/job/promote-snapshots-to-release/jobConfigHistory/) to delete the repo `m2e/snapshots/${releaseVersion}/latest` as last step in its execution.
When I added the extra line and saved it the Jenkins web-interface also changed some more lines in the xml config. I tried to revert them but in my second attempt to add the extra shell command (through the web-interface) the same changes where introduced: https://ci.eclipse.org/m2e/job/promote-snapshots-to-release/jobConfigHistory/
Can you please check if those changes are ok? I think the added/removed empty XML-elements shouldn't be problematic but I'm not sure about the other changed elements.

**Comment by HannesWell** [comment]
Additionally I could delete the [`scripts` directory on the download site](https://download.eclipse.org/technology/m2e/scripts/). The contained script seems to be outdated.

**Comment by mickaelistria** [comment]
> @mickaelistria do you know why the milestones cannot be deleted?

not really. My 1st guess would be some permission issue. Doesn't the job log tell more?

**Comment by HannesWell** [comment]
ls -all showed the following result:
```
+ ssh genie.m2e@projects-storage.eclipse.org 'ls -all /home/data/httpd/download.eclipse.org/technology/m2e/milestones/1.6'
total 24
drwxrwsr-x  6    9175 technology.m2e 4096 Oct  3 04:30 .
drwxrwsr-x 11    9175 technology.m2e 4096 Oct  3 04:30 ..
drwxrwsr-x  4 fbricon common         4096 Dec 16  2014 1.6.0.20141216-1909
drwxrwsr-x  4 fbricon common         4096 Dec 17  2014 1.6.0.20141217-1418
drwxrwsr-x  4 fbricon common         4096 Mar 24  2015 1.6.0.20150324-2020
drwxrwsr-x  4 fbricon common         4096 Mar 25  2015 1.6.0.20150325-2013
```

But unfortunately chmode was not permitted as well:
```
+ ssh genie.m2e@projects-storage.eclipse.org 'chmod +w -R /home/data/httpd/download.eclipse.org/technology/m2e/milestones/1.6'
chmod: changing permissions of '/home/data/httpd/download.eclipse.org/technology/m2e/milestones/1.6': Operation not permitted
chmod: changing permissions of '/home/data/httpd/download.eclipse.org/technology/m2e/milestones/1.6/1.6.0.20150324-2020': Operation not permitted
...
```

Do we have to contact some admin to ask to delete it for us?

**Comment by HannesWell** [comment]
As a second approach I attempted to move the milestone 1.5 to archive and hoping I could delete it from there (this issue from Denis Roy mentioned that possibility: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/78)
but it failed with the following message:
```
1.5 (Folder cannot be archived: failed with 256. Please contact webmaster.)
```

@eclipsewebmaster do you read this? If yes, we would like to the m2e-milestones folder and its content deleted from download.eclipse.org:
https://download.eclipse.org/technology/m2e/milestones/

Or do we have to read an E-Mail to webmaster@eclipse.org ?

**Comment by mickaelistria** [comment]
I think the best is to open an issue to request webmaster to remove or chown those folders to the m2e user; opening a request to https://bugs.eclipse.org/bugs/enter_bug.cgi?product=Community&component=Servers may be the best way to achieve that at the moment (unless you're able to directly open an issue to the GitLab helpdesk project).

**Comment by HannesWell** [comment]
I have commented on the help-desk issue 78 and Denis Roy fixed the permissions:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/78#note_318760
After that I was able to delete the milestones via CI and by moving it to archives via the web-interface and deleting them there.

I also moved the scripts folder to archives.

We could also think about moving older releases to archive.
In the Eclipse-HelpDesk issue 78 it is stated that archived p2-repos are still reachable through their `download.e.o` address even if they have been moved to archives because redirects are implement.
You can test it with:
`https://download.eclipse.org/technology/m2e/milestones/1.6/1.6.0.20141216-1909/`
WDYT?

**Comment by mickaelistria** [comment]
+1, all that sounds good. FWIW, I personally only care about latest release and snapshots. Whatever happens to other repos is fine with me.

**Comment by HannesWell** [comment]
> 
> 
> +1, all that sounds good. FWIW, I personally only care about latest release and snapshots. Whatever happens to other repos is fine with me.

Great.

All releases repos below `1.18.0` were successfully moved to `https://archive.eclipse.org/technology/m2e/releases/`, but are still available via their corresponding `https://download.eclipse.org/technology/m2e/releases/` links.
The milestones repo is fully purged.
In the end this reduced the memory footprint of the m2e repos from around 1GB plus the deleted snapshots repos (which I estimate to had a similar size like the releases repo which was at 778MB) to estimated 140-150MB.
