### ISSUE TITLE
Enable Auto-update by default

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#234]
The Auto-update preference is around since a long time and IMHO super nice and useful. Can this be enabled by default? I see new m2e users struggeling with the update of the project and this will make their life easier.

**Comment by mickaelistria** [comment]
The code says https://bugs.eclipse.org/bugs/show_bug.cgi?id=462898 is to be considered as a requirement for auto-build to be on by default, which I agree with. Issues like #123 may be related.

**Comment by laeubi** [comment]
@mickaelistria this should be fixed now by https://github.com/eclipse-m2e/m2e-core/blob/master/RELEASE_NOTES.md#automatic-configuration-updates-of-maven-projects-enabled-by-default ?

**Comment by vogella** [comment]
Thanks
