### ISSUE TITLE
"Show in Local Terminal" not exposed for nested module projects

### ISSUE THREAD

**Issue by kwin** [eclipse-m2e/m2e-core#241]
Nested Maven modules are all exposed as top level projects in Eclipse. That leads  to the fact that only the reactor module is exposing the menu item "Show in Local Terminal" in the package explorers context menu:

![Screenshot 2021-06-17 at 12 50 46](https://user-images.githubusercontent.com/185025/122383243-f04d1a80-cf6a-11eb-94b0-5fff82950e2d.png)

but not for other nested projects

![Screenshot 2021-06-17 at 12 51 24](https://user-images.githubusercontent.com/185025/122383284-fa6f1900-cf6a-11eb-838f-3306f12a9111.png)

I tested with Eclipse 2021-03 and 2021-06 and m2e 1.17.2 and 1.18, but expose the same (incorrect) behaviour.

**Comment by mickaelistria** [comment]
I don't think this issue belongs to m2e as AFAIK m2e doesn't include anything related to terminal. Please report it to the Terminal component.

**Comment by kwin** [comment]
You are right, this is an issue with Terminal. Just for the record: The menu item is hidden for all project with Java nature whenever no external shell command is defined (https://github.com/eclipse-cdt/cdt/blob/481f08beb43d41de50f3465004b29c0c2fd9ace5/terminal/plugins/org.eclipse.tm.terminal.connector.local/plugin.xml#L101)
