### ISSUE TITLE
m2e-pde integration for pom dependencies

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#242]
AFAIK the current m2e-pde integration does not allow to use Maven dependencies if they are "only" poms. For example:

`````
<dependency>
  <groupId>com.itextpdf</groupId>
  <artifactId>itext-parent</artifactId>
  <version>1.0.0</version>
  <type>pom</type>
</dependency>

`````

Would be cool if m2e-pde could also support these and get the defind dependencies as it does for the dependencies of Java libraries.

**Comment by laeubi** [comment]
Yep that is an open issue :-)

Its on my todo list but at the moment not high-priority, if there are customer demands feel free to contact me and offer a funding for such a feature.

**Comment by laeubi** [comment]
@vogella I have created some adjustment but your example seems to be a bad use-case (except for the fact that it should not generate an error) as it has no compile or other dependencies. So adding this to the target currently could not have any effect.

**Comment by vogella** [comment]
Looking at the  itext pom dependency again, I see that it has no dependency. Sorry for this bad example.

**Comment by laeubi** [comment]
No problem if you find a more suitable one I could use for testing let me know!

**Comment by laeubi** [comment]
I have checked this with the jaxws-ri dependency mentioned above and it works like expected:

![grafik](https://user-images.githubusercontent.com/1331477/136897689-35b6c0e0-d689-4130-b892-924e25df88ff.png)
