### ISSUE TITLE
Downgrade "Plugin execution not covered by lifecycle configuration" to warning

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#243]
Using Tycho I always end up with the following errors in my IDE:

Multiple markers at this line
- Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-resources-plugin:3.1.0:resources (execution: default-resources, phase: process-resources)
- Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-resources-plugin:3.1.0:testResources (execution: default-testResources, phase: process-test-resources)

Can the M2e setting changed so that this is only a warning? It is definitely not an error, as a Tycho build runs fine. 

Please note that I did not install the full m2e, only the m2e-pde integration and I still get this error.

**Comment by mickaelistria** [comment]
We cannot know if a missing lifecycle support is just a warning or is an error; whether it's going to prevent from good usage of the IDE or not. So the general rule is that it's an error by default.
Such errors can be avoided by improving the related Maven mojos by having them declaring some compatibility and using more incremental APIs: https://www.eclipse.org/m2e/documentation/m2e-making-maven-plugins-compat.html

**Comment by fbricon** [comment]
Also see Preferences > Maven > Errors/Warnings > Plugin execution not covered...

**Comment by vogella** [comment]
@laeubi could the m2e-pde integration declare compatibility for the Eclipse targets?

**Comment by laeubi** [comment]
Don't think so but see eclipse/tycho#146
