### ISSUE TITLE
Bug 534772 - m2e does not involve project's maven.config file when building the effective POM

### ISSUE THREAD

**Issue by BrannanH** [eclipse-m2e/m2e-core#274]
[See original bugzilla issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=534772) and [a related messaged](https://www.eclipse.org/lists/m2e-users/msg05711.html).

Maven allows arbitrary command line instructions to be specified in `.mvn/maven.config` [as detailed here.](https://maven.apache.org/configure.html#mvn-maven-config-file)

As in the above, this file should be able to be used to specify any arbitrary properties allowing various properties to be parameterised in POM files, and for instructions to be invoked by default when running maven commands.

One particular application of this is to externalise versions when using CI-friendly maven versions, and as such it can seen mentioned on [this page](https://maven.apache.org/maven-ci-friendly.html). The properties supported through `.mvn/maven.config` shouldn't be limited to `revision`, `sha1` and `changelist` however. Arbitrary properties and command line instructions should be supported as if manually specified in a POM, and/or as command line arguments.

**Comment by mickaelistria** [comment]
Mostly, such extra properties should be added to the ProjectBuildingRequest used by `MavenImpl.readProject()` and similar.
It shouldn't be too hard to implement, at least partly. Feel free to provide a PR about that.

**Comment by mickaelistria** [comment]
I don't think m2e should fix it. The proper project model is the pom.xml; default value for properties is expected to be set directly in pom.xml. The maven.config are not parameters for the project model per se, but more parameters for the CLI execution, which is a different topic.
To get what you want, just use what Maven model does provide as more standard about it: defining default values for the properties in pom.xml.

**Comment by laeubi** [comment]
Requires
- https://github.com/eclipse-m2e/m2e-core/issues/546

I think we should consider this as the `maven.config` can contain other useful hints and will be the only option to use when configuring extension versions.

**Comment by laeubi** [comment]
This should work now, please open specific bugs with a runnable example or better an junittest.
