### ISSUE TITLE
Add Snapshot update site to Readme

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#281]
In https://github.com/eclipse-m2e/m2e-core/issues/212 @laeubi provided an nice enhancement and suggested to try it out via the snapshot update site. Can you add this update site to the readme?

**Comment by vogella** [comment]
https://download.eclipse.org/technology/m2e/snapshots/latest/

**Comment by mickaelistria** [comment]
A pull request would be welcome.
