### ISSUE TITLE
Adding Maven dependency from clipboard does not work anymore

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#289]
This might be related to #212.

If I have a Maven dependency in the clipboard and add a new Maven dependency to your target platform, the dialog does not use the entry from the clipboard anymore.

To test: 

1.) Add the following into your clipboard

````
<dependency>
  <groupId>com.google.code.gson</groupId>
  <artifactId>gson</artifactId>
  <version>2.8.6</version>
</dependency>
````

2.) Create Target platform
3.) Press new -> Maven

-> Dialog is empty.

**Comment by laeubi** [comment]
@vogella can you test/confirm that it works when you edit the location and adds an additional dependency?

**Comment by vogella** [comment]
Cool. Thanks a bunch!
