### ISSUE TITLE
M2E does not follow maven-ear-plugin output filename mapping change since version 3.0.0 of the plugin

### ISSUE THREAD

**Issue by marioja** [eclipse-m2e/m2e-core#291]
Since maven-ear-plugin 3.0.0 (See JIRA [MEAR-171](https://issues.apache.org/jira/browse/MEAR-171)) the name of the artifacts in the ear file defaults to @{groupId}@-@{artifactId}@-@{version}@@{dashClassifier?}@.@{extension}@ (see outputFilenameMapping in maven-ear-plugin documentation [here](https://maven.apache.org/plugins/maven-ear-plugin/examples/customize-file-name-mapping.html).  m2e-core still works using the old defaults (prior to 3.0.0) and uses the old names for the artifacts in includes in the EAR which will differ from the ones written by maven in the generated application.xml.

To reproduce this problem import this [sample maven multi-module project](https://github.com/marioja/maven-ear-example) into an eclipse with the latest m2e and perform the following command:

Select the ModuleEAR and file/export/EAR file.  When you look inside the EAR file, you will notice that the EJB module is called ModuleEJB-1.0-SNAPSHOT.jar but the META-INF/application.xml (created by maven) says the EJB module is rightly called com.example-ModuleEJB-1.0-SNAPSHOT.jar.  This is an invalid EAR that will not deploy to any Jave EE container.

This bug has been affecting people using the IBM WebSphere Tools eclipse plugins as well as the Red Hat CodeReady or JBoss Tools eclipse plugins to deploy ear to their respective application servers.

If you want to see the problem without recreating it just look at the ModuleEAR.ear in the folder Eclipse-EAR folder.

**Comment by marioja** [comment]
I looked at a lot of code both in m2e, eclipse webtools and JBoss wildfly eclipse plugins and I won't presume to understand it all but I think that the right fix for this (and it so happens that it would most likely fix the eclipse export to ear problem and the application server eclipse plugins for wildfly and IBM WebSphere) should be to change the module name of the eclipse project when the maven import project is done.  I would make that change but everytime I try to build an eclipse workspace with m2e I have a lot of problems.  That is not to say even creating a run configuration to test/debug this which I can never get working.

**Comment by mickaelistria** [comment]
Isn't it more an issue to report to the m2e maven-ear-plugin connector; which is part of the m2e-wtp project?

**Comment by marioja** [comment]
I would have no idea if this is the case.  I do not know the source code nor it's structure.  Where is the place to report this problem?

**Comment by mickaelistria** [comment]
I believe this is something to report to m2e-wtp, see info at https://projects.eclipse.org/projects/technology.m2e.m2e-wtp/ . The WTP connectors are in a separate project.
If you're facing the issue in WebSphere and Red Hat tools, I suggest you report this issues to those projects, so they may get involved in the resolution.
