### ISSUE TITLE
Update site unavailable

### ISSUE THREAD

**Issue by kriegaex** [eclipse-m2e/m2e-core#294]
No matter if I add https://download.eclipse.org/technology/m2e/releases/latest/ to Eclipse or as a p2 site to a Maven project, I always get errors:
  * Eclipse IDE: `Could not find https://download.eclipse.org/technology/m2e/releases/latest/`
  * Maven: `ProvisionException: No repository found at https://download.eclipse.org/technology/m2e/releases/latest.`

**Comment by laeubi** [comment]
There are still [heavy outages](https://www.eclipsestatus.io/) on eclipse infra that influences a lot of services. Please retry once the status is back to green if the problem perists.

**Comment by kriegaex** [comment]
Oh, OK. Sorry for the noise. I really did not expect this problem to persist for so long and also to affect update sites. The M2E website is available again, so I thought it was fixed. Other update sites also work correctly. Otherwise I would not have bothered you.

**Comment by laeubi** [comment]
No problem, seems to be a real serve issue as yesterday Bugzilla was offline and some CI service still seem down, but I don't know any details beside that status site so I assume we have to be patient.

**Comment by mickaelistria** [comment]
eclipse.org Infra should be fixed now.
