### ISSUE TITLE
Test failure with Maven 3.8.2

### ISSUE THREAD

**Issue by HannesWell** [eclipse-m2e/m2e-core#324]
Since Maven 3.8.2 is embedded (PR #323) `MavenImplTest.testReadRemoteParent` fails on the master branch:
```
testReadRemoteParent(org.eclipse.m2e.tests.embedder.MavenImplTest)  Time elapsed: 0.44 s  <<< FAILURE!
java.lang.AssertionError: remote-parent.artifact.file
	at org.eclipse.m2e.tests.embedder.MavenImplTest.testReadRemoteParent(MavenImplTest.java:430)
```
It looks like `parent.getArtifact().getFile()` returns null now.

Unless anybody else already knows how to address this, I will investigate it.

**Comment by mickaelistria** [comment]
That's strange it didn't fail on the PR, did it?

**Comment by HannesWell** [comment]
I have to admit that I don't know it. The Jenkins executors were very busy at the weekend and my PR's were waiting for free executors for a long time. When I looked for the result this morning the jobs were either still pending or were aborted after about 8h (I'm not sure if it was that PR or another one from the weekend).

But I can reproduce the error locally so I can investigate it.

**Comment by mickaelistria** [comment]
Ok, I may have missed the failure before merging.
Maybe it's better if revert now and reopen a PR?

**Comment by HannesWell** [comment]
> Ok, I may have missed the failure before merging.
> Maybe it's better if revert now and reopen a PR?

Yes that's probably better, I also thought about that already. I submit a PR.
Maven 3.8.2 seems to have more changes than I would expect from a minor version update.

**Comment by mickaelistria** [comment]
Thanks. Can you please open a "revert revert" PR to check whether test fails there as well?

**Comment by mickaelistria** [comment]
Let's close this ticket and track further discussion and work directly in PR #326
