### ISSUE TITLE
M2Eclipse keeps on downloading sources/javadoc even-though I asked it not to 

### ISSUE THREAD

**Issue by gkfirst8** [eclipse-m2e/m2e-core#332]
I setup the settings of M2Eclipse like so:
![M2Eclipse-maven-settings](https://user-images.githubusercontent.com/10880452/134170835-e4a2b5e5-abb2-444f-8486-fd0e6aa41cba.png)

So it would not download sources automatically. But ever since I upgraded to 1.18.1 (in 2021-09 of Eclipse) the progress-dialog does not stop from popping up and the system keeps telling me it is busy downloading sources/javadoc and the lot.

This slows my workflow considerably. Please help out. What should I change or could this be a bug? (I did try turning the options on-and-off-again to no avail.)

**Comment by HannesWell** [comment]
This is a known issue (see bug #252) that is resolved already, but was not yet released.

Please try the latest m2e snapshot, which should resolve your problem. You can use the following repository (add it to `Available Software Sites` in the preferences and check for updates):
https://download.eclipse.org/technology/m2e/snapshots/1.18.2/latest/

**Comment by mickaelistria** [comment]
Let's close as already tracked in #252

**Comment by gkfirst8** [comment]
Indeed, the provided 1.18.2 solved the problem, thanks!

**Comment by gkfirst8** [comment]
Ok, the problem re-occurred in Eclipse:
Version: 2022-12 (4.26.0)
Build id: 20221201-1913

What am I to do?
