### ISSUE TITLE
Multiple SLF4J bindings

### ISSUE THREAD

**Issue by kwin** [eclipse-m2e/m2e-core#354]
Eclipse comes with a default binding in Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/8/0/.cp/org/slf4j/impl/StaticLoggerBinder.class and m2e contains one in https://github.com/eclipse-m2e/m2e-core/blob/master/m2e-maven-runtime/org.eclipse.m2e.maven.runtime.slf4j.simple/pom.xml as well. So whenever you install "M2E - SLF4J over Logback Logging" you get this warning in the Maven Console.

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:...plugins/org.eclipse.m2e.maven.runtime.slf4j.simple_1.18.1.20211004-1243/jars/slf4j-simple-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [file:/.../Eclipse.app/Contents/Eclipse/configuration/org.eclipse.osgi/8/0/.cp/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
```

That issue was already reported in https://bugs.eclipse.org/bugs/show_bug.cgi?id=506676.

**Comment by kwin** [comment]
This affects some standard distributions e.g. "Eclipse IDE for Enterprise Java and Web Developers (2021-09)" (https://git.eclipse.org/c/oomph/org.eclipse.oomph.git/tree/setups/org.eclipse.products.setup#n1986).

**Comment by mickaelistria** [comment]
@HannesWell Is this something you want in 1.18.2 ? Should we wait for it?
