### ISSUE TITLE
Where is org.sonatype.plexus:plexus-build-api artifact maintained?

### ISSUE THREAD

**Issue by cstamas** [eclipse-m2e/m2e-core#364]
Given you depend on this artifact, can you tell me where are the sources for it? 

As Maven depends on this as well, but we plan to remove this "experimental" feature, as a) it is experimental for 11 years, and b) the project seems dead, at least sources seems completely unmaintained for over 11 years (if not lost, as no "live" repo available at all for it).

https://github.com/eclipse-m2e/m2e-core/blob/81d08b78f787dd561c59153c5970199c3bbd682a/m2e-maven-runtime/org.eclipse.m2e.maven.runtime/pom.xml#L69

We _could_ "revive" the archived https://github.com/sonatype/sisu-build-api (still unsure is this the legitimate source) under https://github.com/codehaus-plexus organization, but I'd rather first learn it's use (is it used, does it has to be used? etc) about it first.

**Comment by laeubi** [comment]
The [Dependency](https://xkcd.com/2347/) Problem:

![Image](https://imgs.xkcd.com/comics/dependency.png)

**Comment by fbricon** [comment]
m2e does actually depend on this incremental builder API (https://github.com/eclipse-m2e/m2e-core/search?q=BuildContext)
As for the original sources, maybe contact Sonatype to see if they have the sources somewhere (was http://svn.sonatype.org/spice/tags/plexus-build-api-0.0.7 as per its pom file)

**Comment by laeubi** [comment]
m2e uses the incremental builder API to support plugins getting aware of the eclipse-build when resources changes and such... given that there is no much changes in the past 11 years we obviously could declare this API as "stable" but will this change anything? I'm a bit confused about the scope of this topic, do you suggest to remove the API itself from maven (is it part of macen?) from m2e, or do you need enhancements/fixes/updates for this API?

**Comment by fbricon** [comment]
m2e uses it to provide an incremental build context to maven plugins in user projects. So it's rather a question of : does any maven plugin in the whole maven ecosystem use this API? The goal of this build context being to avoid unnecessary processing when m2e calls those maven plugins, as part of the Eclipse incremental build.

**Comment by cstamas** [comment]
Ok, so the project has been revived here https://github.com/codehaus-plexus/plexus-build-api

So, my plans (draft):
* make project Java5 (it is 4 currently), as AFAIK m2e support maven 3 but not 2
* keep 100% binary compatibility
* but split package (pull out tests) to let consumers not depend in test-classes, but instead have dedicated test module
* as this would allow later adding new test helpers, with different approach as ancient PlexusTestCase

I consider my issue "solved" with this, and please follow changes in this project. Thanks!

**Comment by laeubi** [comment]
Thanks for the hint, please let us know if we can update/upgrade to a new version then :-)
