### ISSUE TITLE
Plugin could not be resolved

### ISSUE THREAD

**Issue by oliviercailloux** [eclipse-m2e/m2e-core#384]
Adding a plugin with some configuration or execution parts yields an invalid warning `Plugin could not be resolved. Ensure the plugin's groupId, artifactId and version are present. Additional information: Unable to resolve [plugin]`.

For example, adding this to an otherwise unproblematic `pom.xml` (in the `plugins` section):

```xml
<plugin>
	<groupId>org.sonatype.plugins</groupId>
	<artifactId>nexus-staging-maven-plugin</artifactId>
	<version>1.6.8</version>
	<extensions>true</extensions>
	<configuration>
		<serverId>ossrh</serverId>
		<nexusUrl>https://oss.sonatype.org/</nexusUrl>
		<autoReleaseAfterClose>true</autoReleaseAfterClose>
	</configuration>
</plugin>
```

yields: `Plugin could not be resolved. Ensure the plugin's groupId, artifactId and version are present. Additional information: Unable to resolve org.sonatype.plugins:nexus-staging-maven-plugin`.

For example, [this project](https://github.com/oliviercailloux/pom)’s pom produces 6 such warnings.

Using Eclipse IDE for Java Developers Version: 2021-09 (4.21.0) Build id: 20210910-1417.

The problem has also been reported [here](https://community.openhab.org/t/plugin-could-not-be-resolved-ensure-the-plugins-groupid-artifactid-and-version-are-present-on-2-5-x/106328) and [here](https://community.openhab.org/t/latest-eclipse-june-2020-has-warnings-in-the-demo-app/101768).

A similar, but distinct, problem has been reported as [bug #563624](https://bugs.eclipse.org/bugs/show_bug.cgi?id=563624).

**Comment by mickaelistria** [comment]
Sorry, we won't be able to help if you're not able to try latest snapshot build. I suggest you figure out why "updates are not permitted."; and maybe try a staging package from https://download.eclipse.org/technology/epp/staging/ and add to it m2e snapshot (particularly the feature about "LemMinX") and retry.

**Comment by oliviercailloux** [comment]
Just tried the same thing with eclipse release 2021-12. Now I observe the same thing as you [reported](https://github.com/eclipse-m2e/m2e-core/issues/384#issuecomment-950684553) with my sample [project](https://github.com/oliviercailloux/pom): only one warning (not six as previously).

> Only warning I see is with checkstyle because groupId is effectively missing.

I believe that this is a bug. The groupId may be omitted when it is apache’s group id. And several other plugins in that same sample miss the groupId, so reporting only one problem is incoherent.

**Comment by runeflobakk** [comment]
I also observe this, warning about non-resolvable plugin:
```
Plugin could not be resolved. Ensure the plugin's groupId, artifactId and version are present.

Additional information: Unable to resolve maven-javadoc-plugin
```

I have declared maven-javadoc-plugin without groupId, as it is a core Maven plugin. The other core plugins does not emit this warning, so the javadoc plugin does seem a bit random as such. The maven-javadoc-plugin, including the declared version, is available in my local repository, and M2E also has access to resolve/download anything it needs (other stuff, such as artifacts, sources, javadocs are downloaded as needed)


Eclipse version: 2021-12 (4.22) Build id: I20211124-1800

M2E - Maven Integration for Eclipse (includes Incubating components) 1.20.0.20220210-1034
M2E - POM Editor (Legacy) using WebTools SourceEditing UI	1.18.3.20220122-2204
M2E - POM Editor using LemMinX language server (includes Incubating components)	1.18.4.20220127-1634

**Comment by mickaelistria** [comment]
Can you please look for the "type" of this marker in the Problems view? Is this error coming from the language server or from internal m2e model?

**Comment by runeflobakk** [comment]
Looks like it is coming from the language server.
<img width="711" alt="javadoc-plugin-warn" src="https://user-images.githubusercontent.com/174823/156205349-a6f9e2c5-ac41-42a2-94da-6eca71b97e73.png">


---

Interestingly, in this particular project I also get warns from Language Servers about "Invalid plugin configuration". It complains about invalid contents of `header` and `excludes` in the configuration of the [license-maven-plugin](https://mycila.carbou.me/license-maven-plugin/), even though the same editor offers the tags as auto-complete, with indicated content types as String and String[].

<img width="745" alt="license-plugin-header-warn" src="https://user-images.githubusercontent.com/174823/156207399-04b5e86a-33d6-4d36-a5bd-20e7a34abbbc.png">

<img width="738" alt="license-plugin-excludes-warn" src="https://user-images.githubusercontent.com/174823/156207425-810a3081-90a7-4ccc-b6d1-79e8c960a6c5.png">

Upon a bit more inspection, these warnings may actually be warranted.
If I run the following command (may be used outside a Maven project)
```sh
mvn help:describe -Ddetail -Dplugin=com.mycila:license-maven-plugin:4.1 -Dgoal=check
```

I see the following:
```
...
    legacyConfigExcludes
      Alias: excludes
      User property: license.excludes
      Specifies files, which are excluded in the check. By default, only the
      files matching the default exclude patterns are excluded.
      Deprecated. use {@link LicenseSet#excludes}

    legacyConfigHeader
      Alias: header
      User property: license.header
      Location of the header. It can be a relative path, absolute path,
      classpath resource, any URL. The plugin first check if the name specified
      is a relative file, then an absolute file, then in the classpath. If not
      found, it tries to construct a URL from the location.
      Deprecated. use {@link LicenseSet#header}
```
So reading the output from `mvn help:describe` suggests that I am indeed using deprecated configuration directives. Though they are still available (as aliases), and suggested by the auto-complete, and seemingly warning about what I guess may be some kind of deprecation mechanism? Or perhaps some logic is not aware of the alias mechanism, and resulting in a warn for actually valid (though deprecated) configuration?

Is it related? Should I open a new issue about this?

**Comment by mickaelistria** [comment]
@runeflobakk Can you please post a minimal pom.xml that allows to reproduce this issue about "Plugin could not be resolved"?
And yes, please open separate tickets for separate problems.

**Comment by runeflobakk** [comment]
Minimal reproducing POM:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>plugin-resolve-warn</artifactId>
    <groupId>com.github.runeflobakk.eclipse</groupId>
    <version>1-SNAPSHOT</version>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-javadoc-plugin</artifactId>
                    <version>3.2.0</version>
                    <configuration></configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>
```
Importing this to a new Maven project in Eclipse reproduces the issue.

Note the empty `<configuration></configuration>`. Although obviously not very sensible with an empty configuration element, it is valid, and it illustrates that this seems to be what triggers the warning. Removing the configuration-element makes the warning disappear. (I can also add any valid elements inside configuration, and the warning persists)

https://user-images.githubusercontent.com/174823/156227229-38bbba61-182d-4600-ab01-022e7a8482d3.mp4

**Comment by mickaelistria** [comment]
Thanks, I can reproduce the issue with the pom from https://github.com/eclipse-m2e/m2e-core/issues/384#issuecomment-1055882446 . @runeflobakk can you please report it upstream to https://github.com/eclipse/lemminx-maven/issues ?

**Comment by mickaelistria** [comment]
This should now be resolved if you use latest m2e snapshots (which include latest lemminx-maven snapshots).
