### ISSUE TITLE
Edit button in the target editor for one Maven dependency

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#395]
It would be nice if I could edit one dependency from my Maven dependencies. Currently the Edit button is "only" active if I select the location which can be difficult to handle if I have lots of Maven dependencies, e.g. > 100.

![image](https://user-images.githubusercontent.com/139910/140922521-9b0d1833-18ec-4ed5-9039-8fbb18a96f12.png)

**Comment by vogella** [comment]
cc @HannesWell

**Comment by laeubi** [comment]
Actually the PDE editor is missing good user-assitance (what m2e can't change) especially:

1. Expand/Collapse all button
2. Filtering (by label)

Beside this the Edit button currently is used to edit the BND instructions (if applicable) so it is a bit hard to decide how to handle this case. Another problem is that not every dependency you see in the tree is "editable" so the location itself seems a logical place to handle the edit.
