### ISSUE TITLE
http Maven repository no longer works, need to change to https

### ISSUE THREAD

**Issue by sharpentheaxe** [eclipse-m2e/m2e-core#411]
I am trying to remote deploy my code to a raspberry PI.  I have been following the example at http://www.raspirecipes.org/archives/218.  I get to the part when is says run the build.xml file as ant, then I get the errors below.   I found that Maven repositories no longer support HTTP and need to be https.  How do I change the repository location for the M2E plug in to point to https://repo1.maven.org/maven2/ ?

I have tried to put the repository in my POM.xml file and this did not work.

This is the error message when I go to http://repo1.maven.org/maven2/
501 HTTPS Required. 
Use https://repo1.maven.org/maven2/
More information at https://links.sonatype.com/central/501-https-required

This is the error message from output window in Eclipse:

[artifact:mvn] [WARNING] Unable to get resource 'org.apache.maven:apache-maven:pom:2.0.10' from repository central (http://repo1.maven.org/maven2): Error transferring file: Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/org/apache/maven/apache-maven/2.0.10/apache-maven-2.0.10.pom
     [null] An error has occurred while processing the Maven artifact tasks.
     [null]  Diagnosis:
     [null] 
     [null] Unable to resolve artifact: Missing:
     [null] ----------
     [null] 1) org.apache.maven:apache-maven:pom:2.0.10
     [null]   Path to dependency: 
     [null]   	1) org.apache.maven:super-pom:pom:2.0
     [null]   	2) org.apache.maven:apache-maven:pom:2.0.10
     [null] 
     [null] ----------
     [null] 1 required artifact is missing.
     [null] 
     [null] for artifact: 
     [null]   org.apache.maven:super-pom:pom:2.0
     [null] 
     [null] from the specified remote repositories:
     [null]   central (http://repo1.maven.org/maven2)
     [null]

**Comment by mickaelistria** [comment]
Which version of m2e are you using?

**Comment by sharpentheaxe** [comment]
I am using version 1.18.2

**Comment by mickaelistria** [comment]
Do you have any idea where this `http://repo1.maven.org` repository may be coming from? It's not referenced anywhere in m2e nor in Maven 3.8.1.

**Comment by sharpentheaxe** [comment]
This is where it is breaking down in the POM.xml file.

	<target name="maven-install"> 
		<artifact:mvn pom="pom.xml"> 
			<arg value="install"/> 
		</artifact:mvn> 
	</target>

**Comment by HannesWell** [comment]
It looks like this is the place where you are calling Maven from your ANT build.xml file.
More interesting would be the content of the `pom.xml` file.

Furthermore I'm not sure, respectively I would expect that it is not the case that, if you call Maven from an ANT build script, the Maven version bundled with m2e is used.

After searching for the `Maven-Install` ANT Task I found this: http://maven.apache.org/ant-tasks/installation.html
This site says that the `Maven-Install` task has its own Maven distribution packed into the jar and that is last published in 2014.
Therefore I suspect you are using an ancient version of Maven unintentionality, that uses the old URL.
The following error message part
`[artifact:mvn] [WARNING] Unable to get resource 'org.apache.maven:apache-maven:pom:2.0.10'`
... let me think it is 2.0.10, which is from 2009.

**Comment by sharpentheaxe** [comment]
I just installed recently installed Eclipse and all the plugins, so I am not sure why I was using the older version of Maven.  The helped my find the correct direction. I was able to fix\work around the issue by doing the following:

In the Maven Installations, I added Maven 3.8.3 
I followed the instructions here to install Maven: http://maven.apache.org/install.html
This was under preferences->Maven->Installations, then add the newly installed Maven installation
I had to create a settings.xml file in C:\users\my folder with my name\.m2\settings.xml
To create the settings file, I copied the settings file from C:\Users\my folder with my name\apache-maven-3.8.3\conf\settings.xml

Then I updated the settings.xml file with he following:

`<settings>    
<mirrors>
        <mirror>
            <id>central.mirror</id>
            <url>https://repo1.maven.org/maven2/</url>
            <mirrorOf>central</mirrorOf>
        </mirror>
    </mirrors>
</settings>`
 
I found the information at this site:
https://clutcher.github.io/post/hybris/maven_central_repository_http_issue/

I then ran the build and the libraries began to download as expected.

**Comment by HannesWell** [comment]
> I just installed recently installed Eclipse and all the plugins, so I am not sure why I was using the older version of Maven. Your comment helped my find the correct direction. I was able to fix\work around the issue by doing the following:

I think the cause of the problem is that, as your linked guide states, the Ant's Maven tasks are not maintained any more and therefore come with a old Maven version.

> 
> In the Maven Installations, I added Maven 3.8.3 I followed the instructions here to install Maven: http://maven.apache.org/install.html This was under preferences->Maven->Installations, then add the newly installed Maven installation I had to create a settings.xml file in C:\users\my folder with my name.m2\settings.xml To create the settings file, I copied the settings file from C:\Users\my folder with my name\apache-maven-3.8.3\conf\settings.xml
> 
> Then I updated the settings.xml file with he following:
> 
> `<settings> <mirrors> <mirror> <id>central.mirror</id> <url>https://repo1.maven.org/maven2/</url> <mirrorOf>central</mirrorOf> </mirror> </mirrors> </settings>`
> 
> I found the information at this site: https://clutcher.github.io/post/hybris/maven_central_repository_http_issue/
> 
> I then ran the build and the libraries began to download as expected.

Installing Maven on your system likely makes the `Maven-Install` task use that recent version. Therefore I suspect you don't have to change the M2E/Maven Preference to make the Ant-Build work. In fact I think M2E is actually not involved at all, I think it is only ANT and your Maven stand-alone installation. But it's good that it is working now. 👍🏽
