### ISSUE TITLE
Please enable Gihub Discussions

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#420]
It was discussed on the mailinglist to [use GH-discussions](https://www.eclipse.org/lists/m2e-dev/msg02424.html) as there are +3 votes ( @laeubi , @mickaelistria and @HannesWell ) and no negative vote I'd like to propose to

- [x] enable GH Discussions, AKAIK the projectlead must enable this @akurtakov has done this for tycho already, maybe he can explain a bit more on how to do it?
- [ ] send a notification to the https://accounts.eclipse.org/mailing-list/m2e-users that we have switched

**Comment by fbricon** [comment]
Discussions have been enabled.

**Comment by HannesWell** [comment]
Is somebody taking care of sending a message to m2e-users and closing it for writes, so the transition can be completed?

**Comment by vogella** [comment]
> Is somebody taking care of sending a message to m2e-users and closing it for writes, so the transition can be completed?

@mickaelistria can you do this? I think you have done this also for Tycho.

**Comment by akurtakov** [comment]
Mickael is off this week. Someone else will have to handle it.

**Comment by HannesWell** [comment]
> Mickael is off this week. Someone else will have to handle it.

Mickael seems to be back. :)

**Comment by HannesWell** [comment]
We still have to disable the m2e-user mailing-list.

How can the Mailing-List be disabled? If this only requires an EF-Helpdesk request and a final E-Mail I can do that.
Is there a template/best-practice for the announcement E-Mail?

**Comment by vogella** [comment]
Is the mailing list not necessary for committer election?

**Comment by HannesWell** [comment]
> Is the mailing list not necessary for committer election?

Committer elections are done at the m2e-dev mailing list (which is the reason that list has to stay), the m2e-user list is/was only used for users questions.

**Comment by mickaelistria** [comment]
Before closing the m2e-users mailing-list, someone needs to announce that GitHub discussions are now preferred. I'm personally not subscribed to this ML, so I won't be able to do it.
Once the annouce is on, we can open a ticket to Eclipse Foundation helpdesk to ask the mailing-list ot be made read-only.

**Comment by HannesWell** [comment]
> Before closing the m2e-users mailing-list, someone needs to announce that GitHub discussions are now preferred. I'm personally not subscribed to this ML, so I won't be able to do it. Once the annouce is on, we can open a ticket to Eclipse Foundation helpdesk to ask the mailing-list ot be made read-only.

Done: https://www.eclipse.org/lists/m2e-users/msg05899.html

**Comment by HannesWell** [comment]
Not yet completely done, but created the help-desk issue to close the list:
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1306

**Comment by HannesWell** [comment]
> Not yet completely done, but created the help-desk issue to close the list: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1306

The list has been closed.
