### ISSUE TITLE
Downgrade the "Plugin Execution not covered by lifecycle configuration" error to warning / info or do not show it at all

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#424]
Currently helping a client and this client uses a lot of Maven. 

His and mine experience with Eclipse and importing a random Maven project are really bad as almost every Maven projects imports with errors. For example the "https://github.com/Atmosphere/atmosphere" project gives me the following errors:

Description	Resource	Path	Location	Type
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (execution: validate, phase: validate)	pom.xml	/annotations	line 3	Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (execution: validate, phase: validate)	pom.xml	/cpr	line 3	Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (execution: validate, phase: validate)	pom.xml	/jersey	line 3	Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-checkstyle-plugin:3.1.1:checkstyle (execution: validate, phase: validate)	pom.xml	/native	line 3	Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-pmd-plugin:3.13.0:check (execution: validate, phase: validate)	pom.xml	/annotations	line 3	Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-pmd-plugin:3.13.0:check (execution: validate, phase: validate)	pom.xml	/cpr	line 3	Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-pmd-plugin:3.13.0:check (execution: validate, phase: validate)	pom.xml	/jersey	line 3	Maven Project Build Lifecycle Mapping Problem
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-pmd-plugin:3.13.0:check (execution: validate, phase: validate)	pom.xml	/native	line 3	Maven Project Build Lifecycle Mapping Problem

Similar for C:\Users\vogella\git\atmosphere-samples\.git.

![image](https://user-images.githubusercontent.com/139910/145002165-a543be64-02b1-43af-8441-56f6a780f6f0.png)

The client (who also uses Eclipse for Plug-in development) started using Visual Studio code for Maven projects as it does not show these errors not does it show this as warnings. This allows the client to focus on the real issues.

![image](https://user-images.githubusercontent.com/139910/145002540-7f56108c-e402-47d6-8344-f3378d07d94a.png)

After trying to work on unknown Maven projects with Eclipse I have to agree, its is time consuming to work on these lifecycle configurations issues in Eclipse and simpler to quickly import these in Visual Studio code.

To allow users to use Eclipse as easy as Code for Maven projects I suggest we either:

- Change the error to a warning or info
-  Do not show these messages at all (as Code does)

**Comment by mickaelistria** [comment]
I opened https://github.com/eclipse-m2e/m2e-core/pull/425 to make those warnigns, @laeubi @HannesWell do you agree this is a desired improvement?

**Comment by laeubi** [comment]
I aways ignore uncovered lifecycle-phases. Down to the line, it seems people more often install dedicated plugins for check style (even if its a PITA).

**Comment by vogella** [comment]
Thanks @mickaelistria this will be a huge usability improvement for my client (and myself). Before @laeubi PDE integration I never installed m2e into my Eclipse because of these (very distracting) errors.

**Comment by vogella** [comment]
If @laeubi ignores them (also), maybe even warning is too strong? Info maybe?

**Comment by mickaelistria** [comment]
Warning is my last offer, nothing less, at least for now.
Those errors are valuable although people ignore them by "laziness" (in a good sense, people focus on their own goals). They do highlight that user shouldn't expect a particular mojo to work fine by default and it gives user the ability to mitigate that (with quick-fixes) and contributors a reminder that if they want to improve Maven support in Eclipse IDE, a part of the job can be done directly in the Maven mojos.

**Comment by HannesWell** [comment]
> Warning is my last offer, nothing less, at least for now. Those errors are valuable although people ignore them by "laziness" (in a good sense, people focus on their own goals). They do highlight that user shouldn't expect a particular mojo to work fine by default and it gives user the ability to mitigate that (with quick-fixes) and contributors a reminder that if they want to improve Maven support in Eclipse IDE, a part of the job can be done directly in the Maven mojos.

I agree with Mickael, for the mentioned reasons.
Sometimes those errors are irrelevant but I also had cases where my project didn't work until I installed the corresponding mapping-plug-ins. Therefore I think warning is a good compromise. And if one wants to entirely remove those warnings the issue level can be changed to info in the preferences (Maven -> Errors/Warnings -> `Plugin execution not covered by lifecycle configuration`). But I just noticed that one can only select between `Error`, `Warning` and `Ignore`. I think we should consider to either add `Info` or replace Ignore by `Info`?

**Comment by vogella** [comment]
> Warning is my last offer, nothing less, at least for now.

This would be much better than today so a big +1 from me to this change.

**Comment by vogella** [comment]
Just another example from an import of Windowbuilder

![image](https://user-images.githubusercontent.com/139910/145030885-557ca953-f268-4259-84ec-8751d707fe5d.png)

**Comment by mickaelistria** [comment]
As mentioned on https://github.com/eclipse-m2e/m2e-core/pull/425 , this also requires to update 19 tests. And working with those tests is a PITA, so I'm lowering priority on this for my backlog. Anyone interested in trying to make the tests pass with the suggested change is really welcome to contribute PRs.

**Comment by vogella** [comment]
Thanks, looks good to me in the latest build.
