### ISSUE TITLE
Allow to give the Maven part in the pde target editor a name

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#427]
Currently the M2e extension shows "Maven dependencies" with the number of libraries in the PDE editor.

Would be nice to allow to specify a label for these entries and show this label in the label of the editor, for example as

"Maven dependencies for Jetty" where "Jetty" in the label for this entry.

![image](https://user-images.githubusercontent.com/139910/145015613-4116d07f-9b0e-4cbc-b252-442ed619b441.png)

**Comment by mickaelistria** [comment]
Something like `org.eclipse.jetty:jetty:10.0.0 and dependencies` would indeed be a better label for the case of a single artifact referenced; however those Maven location can contain multiple artifacts, in which case it's hard to find a descriptive label that would be easy enough to read and would fit on the screen...

**Comment by vogella** [comment]
If we could specify a label in the "location" tag, this label could be used. Hence this enhancement request.

**Comment by laeubi** [comment]
This is something I'd like to adress after the next PDE release what will allow for advanced formatting capabilities. As this will then allow to generate a feature from a location as well, it might be a good deal to use the feature name (if present) then a user defined name (if given) and only as a last resort the number of dependent items.
One idea ways aslo to look for a common group-id e.g. and use this like (nn dependencies with group org.jetty)

**Comment by laeubi** [comment]
If a feature is defined, the name of the feature will be used now, I wonder if this already satisfies the requirement or if we need a dedicated "label" attribute for this?
![grafik](https://user-images.githubusercontent.com/1331477/145708625-458432a9-c0f2-4c02-9930-13b1c382cde4.png)

**Comment by laeubi** [comment]
You can now enter a custom name for a location:

![grafik](https://user-images.githubusercontent.com/1331477/145711088-26ce1e33-e652-4175-bc5c-e0318066e2f1.png)

this results in something similar to:

`<location includeSource="true" label="You name it!" missingManifest="generate" type="Maven">`

this is then used as the label for the location:
![grafik](https://user-images.githubusercontent.com/1331477/145711157-be3b6ee4-39b7-49d8-ac0c-d8e8874e4688.png)

**Comment by HannesWell** [comment]
Thank's Christoph, that's very handy to make the structure of a Target more clear!
IIRC we already discussed about this in another issue but I couldn't find it.

Does a explicitly specified label takes precedence over a feature name?

**Comment by laeubi** [comment]
Current precedence order is:
- name
- feature name
- auto generated name

**Comment by vogella** [comment]
Looks great. Thanks

Christoph Läubrich ***@***.***> schrieb am So., 12. Dez.
2021, 13:36:

**Comment by vogella** [comment]
Created https://bugs.eclipse.org/bugs/show_bug.cgi?id=577793 for a similar flag for p2 update sites.
