### ISSUE TITLE
Test failure at 	at org.eclipse.m2e.core.ui.tests.ConsoleTest.testConsoleHasOutput(ConsoleTest.java:61) in mvn clean verify build

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#431]
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.883 s <<< FAILURE! - in org.eclipse.m2e.core.ui.tests.AllTests
testConsoleHasOutput(org.eclipse.m2e.core.ui.tests.ConsoleTest)  Time elapsed: 2.857 s  <<< FAILURE!
java.lang.AssertionError: missing output in console
	at org.eclipse.m2e.core.ui.tests.ConsoleTest.testConsoleHasOutput(ConsoleTest.java:61)

**Comment by HannesWell** [comment]
This is a duplicate of #341.
