### ISSUE TITLE
Adopt PDE configurations for maven-bundle-plugins

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#439]
m2eclipse-tycho is no longer maintained but contains a very useful project configurator:

[PDEMavenBundlePluginConfigurator](https://github.com/tesla/m2eclipse-tycho/blob/master/org.sonatype.tycho.m2e/src/org/sonatype/tycho/m2e/internal/PDEMavenBundlePluginConfigurator.java)

this one instructs PDE to look at the right location for the `MANIFEST.MF` file. Although m2e should not host/contain specific code for all maven plugins, the maven-bundle-plugins (BND+Felix) are basically that "basic" that we should support them natively up to that point that the PDE project is configured accordingly and then the default lifecycle-mapping could be applied that is shipped with the plugin itself.

@mickaelistria what do you think? any concerns? I think a 1st-class support for plugin development in m2e is crucial for acceptance of more "maven-like" development.

**Comment by mickaelistria** [comment]
I think it makes sense to include it in m2e, together in the same feature or bundle as the .target support.

**Comment by laeubi** [comment]
> I think it makes sense to include it in m2e, together in the same feature or bundle as the .target support.

Yes that was also my intention as we already have a m2e.pde feature it would perfectly match to include it there.

**Comment by laeubi** [comment]
@HannesWell due to mi limited testing this restores the behavior of adding PDE nature and setting the BUNDLE_ROOT for bnd-/felix-maven plugins when uninstall the no longer maintained tycho-connector. for felix I'll have then added the follwoing pom configuration:

```
<plugin>
	<groupId>org.apache.felix</groupId>
	<artifactId>maven-bundle-plugin</artifactId>
	<version>5.1.2</version>
	<extensions>true</extensions>
	<configuration>
		<instructions>
			<Export-Package>*</Export-Package>
			<Import-Package>!sun.*,*</Import-Package>
		</instructions>
		<supportIncrementalBuild>true</supportIncrementalBuild>
	</configuration>
	<executions>
		<execution>
			<goals>
				<goal>manifest</goal>
			</goals>
			<phase>process-classes</phase>
		</execution>
	</executions>
</plugin>
```

to get automatic bundle manifest generation on code changes and PDE recognizing the project as a bundle.

Just in case you wanted to try this out/help with testing :-)

**Comment by laeubi** [comment]
I even got bnd-maven-plugin working now! I initially though to "magical" modify the execution request but think its better to direct the user how to configure this in the pom to make them aware of something is happening here. So I now added some warnings if required configuration is missing so the user can adjust the pom.

**Comment by HannesWell** [comment]
This looks very promising and I'm looking forward to use it!

> 
> Just in case you wanted to try this out/help with testing :-)

I will test it tomorrow when starting with #423.

**Comment by laeubi** [comment]
Great let me know of any issues.

**Comment by laeubi** [comment]
I think this is done so far.
