### ISSUE TITLE
Comment command in pom text editor 

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#462]
Would be great to have a comment available to comment the selected lines in the pom editor. For example, if I want to comment out a plug-in.

![image](https://user-images.githubusercontent.com/139910/147104888-e03e37f1-2a11-4096-a785-1e7672b1ec82.png)

**Comment by mickaelistria** [comment]
This is fixed upstream with https://github.com/eclipse/tm4e/pull/308 . Installing latest snapshot of TM4E Language Configuration support will solve the issue.
This will be automatically included in m2e when the releases start cascading (TM4E -> Wild Web Developer -> m2e)

**Comment by vogella** [comment]
Thanks

Mickael Istria ***@***.***> schrieb am Do., 6. Jan. 2022,
23:37:
