### ISSUE TITLE
Dark theme - color for matching tag in the text editor is too light

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#463]
If I select an entry in the pom text editor the corresponding opening or closing tag is highlighted. Unfortunately the select color does not fit to the dark theme.

![image](https://user-images.githubusercontent.com/139910/147105513-b00b1cb1-9be3-4a66-9f64-759f5fc1a587.png)

**Comment by laeubi** [comment]
@mickaelistria is this lemminx issue?

**Comment by mickaelistria** [comment]
No, it's more an issue in LSP4E I believe.
However, this was refactored in LSP4E a while ago and shouldn't be happening with latest LSP4E snapshots/upcoming LSP4E release, so let's close.

**Comment by vogella** [comment]
Tried with   M2E - Maven Integration for Eclipse (includes Incubating components)	1.20.1.20220227-1319	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e and its is still bad. To test:

1.) Switch to dark theme
2.) Open pom 
3.) Hover of project and observe the closing tag

![image](https://user-images.githubusercontent.com/139910/168759519-2978e57a-7232-4500-8a3e-479ac507726c.png)

**Comment by vogella** [comment]
Which it is not light anymore, now it is unreadable. 👎

**Comment by mickaelistria** [comment]
Please report to LSP4E.
