### ISSUE TITLE
Typo in PDE Feature generation text

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#485]
The text in the feature generation last page says:

"Select the plug-ins and fragments from your workspace that should be additionally package into the generated feature"

package should be "packaged" I think.

And not all of these artifacts need to be in the workspace, they can also come from the target platform so maybe a better text would be:

"Select the plug-ins and fragments that should be additionally packaged into the generated feature"

Or a bit shorter: 

"Select the plug-ins and fragments that are additionally added to the generated feature"

**Comment by mickaelistria** [comment]
Can you please submit a PR for that? You can do it directly from GitHub.
