### ISSUE TITLE
pom editor: type end-tag wrong

### ISSUE THREAD

**Issue by ca-stefan-cordes** [eclipse-m2e/m2e-core#490]
When typing end xml tags the editor completes with 
<version>1.0.0</>
but needs to be
<version>1.0.0</version>

![image](https://user-images.githubusercontent.com/50696194/149287165-daa33329-861c-4f12-9e66-135629b523a7.png)

Ref https://github.com/eclipse-m2e/m2e-core/issues/458#issuecomment-999089334

**Comment by mickaelistria** [comment]
Can you please give details (eg example pom) about how to reproduce this issue with latest snapshots? Here is what I get locally:
![Screenshot from 2022-01-13 10-04-15](https://user-images.githubusercontent.com/469058/149300135-2155bd2a-9dd5-4a36-a4a7-b27de9614214.png)

**Comment by laeubi** [comment]
@mickaelistria if that works as you described I think most users would expect that the end tag is automatically included as it is the only choice to get a well-formed xml.

**Comment by laeubi** [comment]
Just another thin I noticed, the comment+cdata suggestions should really be the lowest priority item here if you not assume most users like to participate in an obfuscated xml contest...

**Comment by ca-stefan-cordes** [comment]
Type "<"
![image](https://user-images.githubusercontent.com/50696194/149311361-64931a16-b9fa-40e5-b9a9-68523c6ca8a2.png)
Type "test"
![image](https://user-images.githubusercontent.com/50696194/149311407-27e34c69-ae64-415d-9770-467c362774e4.png)
Cursor right
type "value"
type "<"
![image](https://user-images.githubusercontent.com/50696194/149311487-ef955547-f63c-4fc6-9a93-1c74826d3b84.png)
(no fillout and no popup)

**Comment by ca-stefan-cordes** [comment]
XML content assist is "default" - but (as in previous editor) there need not to be a popup as the only 
valid input here is the end tag. (nobody is placing comments inside the textcontent of a node)

![image](https://user-images.githubusercontent.com/50696194/149312227-8aeb52ee-0831-4afb-9916-29701b4f9e77.png)

**Comment by mickaelistria** [comment]
@laeubi please report those issues to lemminx-maven.

**Comment by ca-stefan-cordes** [comment]
Normally that should be your job as "Eclipse pom Editor is not working".

Where is lemminx-maven ?
Can I report it with Eclipse UI or do I need to install lemminx-maven separately ?

**Comment by mickaelistria** [comment]
> Normally that should be your job as "Eclipse pom Editor is not working".

My pom editor is working ;)
Building and keeping active a community requires more subtle steps than just fixing everything for everyone on demand for free.

LemMinX-Maven is located at https://github.com/eclipse/lemminx-maven . At the moment, I suggest only the functional enhancement be reported there; the bugs you're facing with missing content are more likely some other integration issue that still needs investigation before finding a solution.

**Comment by ca-stefan-cordes** [comment]
For sure fixing and controlling demands needs to be focused.

From a user perspective:
* I opened "the pom editor" in 2021-12 and "nothing worked as before".

I understand the decision to switch from "own made editor" to some kind of standard (Wild Web Developer & LemMinX-Maven),
but "dropping" useful productive features due to that switch should have been checked in advance instead of waiting for "bugs".

Back to this problem:

Maybe missing popup (as popup seems current solution) is related to operating system?
I am using Eclipse on Microsoft Windows [Version 10.0.19042.1415].

**Comment by mickaelistria** [comment]
@ca-stefan-cordes Can you please try the following
* Share your eclipse IDE log (in ${workspace}/.metadata/.log )
* Share the language server logs: go to Preferences > Language Servers > Logs, enable "Log To File" for org.eclipse.wildwebdeveloper.xml, close all poms (to let the Language Server shutdown) and then re-open one (to restart the Language Server with logging turned on). Then the log file would be in ${workspace}/languageServers-log/org.eclipse.wildwebdeveloper.xml.txt).

**Comment by ca-stefan-cordes** [comment]
When typing "</" the only selection is "End with..." and "Enter" closes the tag.
So additionally type "/" is fine for workaround.
