### ISSUE TITLE
pom editor: format source not working

### ISSUE THREAD

**Issue by ca-stefan-cordes** [eclipse-m2e/m2e-core#493]
Ctrl-Strg-F no longer formats the xml source.

Should format according to xml formatting options in Window Preferences.

Ref https://github.com/eclipse-m2e/m2e-core/issues/458#issue-1082370111

**Comment by ca-stefan-cordes** [comment]
With enabled language Server (Window Preferences) the Format is working ( :-0 )

**Comment by gerib** [comment]
Exactly this happens here (again?) with:

Linux 6.1.0-28-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.119-1 (2024-11-22) x86_64 GNU/Linux

---
Operating System: Debian GNU/Linux 12
KDE Plasma Version: 5.27.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.1.0-28-amd64 (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-6700 CPU @ 3.40GHz
Memory: 15,6 GiB of RAM
Graphics Processor: NV124
Manufacturer: XMG
Product Name: P7xxDM(-G)
System Version: Not Applicable

---
Eclipse IDE for Enterprise Java and Web Developers (includes Incubating components)

Version: 2024-12 (4.34.0)
Build id: 20241128-0757

---
Plug-in:
03/10/2024, 18:53	Eclipse.org - m2e	M2E Maven POM File Editor using Wild Web Developer, LemMinX and Maven LS extension (requires Incubating components)	2.0.700.20240928-0605	org.eclipse.m2e.editor.lemminx

**Comment by gerib** [comment]
Same issue: [POM editor "Format" command is not available](https://github.com/eclipse-m2e/m2e-core/issues/1373#issue-1705786588).
