### ISSUE TITLE
Open Managed Location no longer available

### ISSUE THREAD

**Issue by a1dutch** [eclipse-m2e/m2e-core#496]
The previous editor used to offer "Open Managed Location" but this is no longer available, is there any plans to add this back?

<img width="698" alt="Screenshot 2022-01-13 at 20 57 30" src="https://user-images.githubusercontent.com/1457117/149408250-57a3f634-0def-4a29-9c67-608c91957344.png">

**Comment by HannesWell** [comment]
> The previous editor used to offer "Open Managed Location" but this is no longer available, is there any plans to add this back?
> 
At least there is another issue (#437) that is already reported upstream to [eclipse/lemminx-maven](https://github.com/eclipse/lemminx-maven)

**Comment by laeubi** [comment]
@HannesWell @mickaelistria I think we should close upstream-related stuff only if the upstream bug is fixed and m2e has in-cooperated the change. Its otherwise confusing for people seeing similar problems and a ticket that is closed but the problem remains.

**Comment by HannesWell** [comment]
> 
I agree with you. But the mentioned issue is for m2e, so it is a real duplicate, regardless of that it is actually caused upstream. Maybe my answer was a bit confusing. I have updated it to hopefully make it more clear.

**Comment by laeubi** [comment]
Duplicate of #437
