### ISSUE TITLE
Update links on https://projects.eclipse.org/projects/technology.m2e/developer

### ISSUE THREAD

**Issue by digulla** [eclipse-m2e/m2e-core#502]
The links to report and search bugs point to https://projects.eclipse.org/

Is that still correct? If not, then please change the document to point here.

**Comment by mickaelistria** [comment]
Which links? Where? Ideally, please submit a PR for those so everything is more explicit.

**Comment by digulla** [comment]
The links at the top of this page: https://projects.eclipse.org/projects/technology.m2e/developer

![image](https://user-images.githubusercontent.com/159306/149957902-8d790c50-5649-4be6-8df2-ae8720f00bd4.png)

**Comment by mickaelistria** [comment]
I couldn't change the links, but I removed them. So it's not wrong any more ;)
Thanks for the report.
