### ISSUE TITLE
Get rid of indexer, everywhere

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-m2e/m2e-core#509]
Maven indexer is an unhealthy project, and it relies on downloading indexes, which is a pretty expensive operation that is typically not desired as there are better alternatives.
m2e should soon initiate an effort to remove everything that relies on indexer and stop relying on indexer for anything.

**Comment by mickaelistria** [comment]
I reviewed usage of indexer and the only important use-case is about Archetype. However, we can usually load artifacts without an index, so this could probably be removed there.

**Comment by HannesWell** [comment]
Fully support! This will save me about 4GB of disk-space per workspace that uses M2E.

To remove the indexer the old editor has to be removed before, right?
We then also remove the `org.eclipse.m2e.maven.indexer` plug-in from m2e?

**Comment by mickaelistria** [comment]
This would more or less require to remove most features from `Maven Repositories` view.

**Comment by HannesWell** [comment]
Once the indexer is removed we should consider to (automatically) clean up the then unused workspace's indexing-data at `\.metadata\.plugins\org.eclipse.m2e.core\nexus`. The indexing-data can be huge (for me it is ~4,5GB per workspace that uses m2e!).
This would be convenient and could be done in the activator of `org.eclipse.m2e.core`.
We could ask the user in a dialog if the deletion should be performed or not or just delete the old files if they are present?

**Comment by vogella** [comment]
+1 for the removal

**Comment by mickaelistria** [comment]
Fixed with #510

**Comment by HannesWell** [comment]
> Fixed with #510

🎉 Thank you Mickael!

**Comment by ririliu** [comment]
I update eclipse to new 2022-09 version, which with m2e version 2.0.4, I found "maven repositories" view is broken, all repository include local repository is grey out, and without any icon, and there is no "rebuild index" or "update index" option in context menu, is the problem related to this issue?

**Comment by mickaelistria** [comment]
> s the problem related to this issue?

Yes. this view should have been removed entirely to be consistent with the indexer removal.

**Comment by ririliu** [comment]
> > s the problem related to this issue?
> 
> Yes. this view should have been removed entirely to be consistent with the indexer removal.

I found the "search" function in "pom editor"-"Dependencies tab"-"Add..." window need the index, I tried search in eclipse 2022-09, it's not work.
I kind like this search function 🤣

**Comment by ririliu** [comment]
I mean this window
![图片](https://user-images.githubusercontent.com/30514728/190377752-b08b56db-b760-4ccb-9328-dfe4b5cd26a2.png)
I don't konw where to find the section you talk about

**Comment by laeubi** [comment]
> You can simply type your search query into the Dependencies section of a pom and the content assist suggests corresponding results.

If it not [gets stuck forever](https://github.com/eclipse-m2e/m2e-core/issues/902#issuecomment-1243448964) ... 

Also as noted earlier, this is not really a full alternative, beside being buggy/slow it does not allow efficiently scroll, there is no way fro tree like representation as in the screenshot and so on....

**Comment by mickaelistria** [comment]
> I mean this window

I think there is already an issue open to replace this window by some integration of search.maven.org service that does a better job than the indexer. If you're willing to contribute a rework of this window, that would be really welcome.
