### ISSUE TITLE
POM editor - End tag incorrectly modified when modifying the start tag

### ISSUE THREAD

**Issue by gsmet** [eclipse-m2e/m2e-core#513]
Hi,

I'm in a `pom.xml`, I create a property in the `<properties>` block with:
```
<test.property>test</test.property>
```
Then I select `test` in the start tag by double clicking on it and try to change it to `plop` by typing `plop`, and I end up with the following content:
```
<plop.property>test</p.prpoloperty>
```

This is with Eclipse 2021-12 and:
```
Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	1.19.0.20211116-0804	org.eclipse.m2e.feature
```

**Comment by HannesWell** [comment]
I noticed this as well, but this seems to be an issue in eclipse-lemminx.
Can you please report this upstream in https://github.com/eclipse/lemminx-maven/issues

**Comment by gsmet** [comment]
Mickael asked me to report my issues here so I'll let you redirect them where you think they make more sense as all the reproducers I have are with the POM editor.

**Comment by mickaelistria** [comment]
I couldn't transfer to LSP4E, so I've opened https://github.com/eclipse/lsp4e/issues/52

**Comment by mickaelistria** [comment]
This is now tracked (and fixed) in LSP4E.
