### ISSUE TITLE
POM Editor - Pressing Enter has no effect (no new line) after closing tab completion

### ISSUE THREAD

**Issue by gsmet** [eclipse-m2e/m2e-core#515]
I'm in a POM file. I go to a `<dependency>` block, I start to type `<exclu`, it suggests `<exclusions>` which is what I want.

I type enter to select it. It inserts `<exclusions></exclusions>` which is good. The cursor is in the middle of the tag which is good too.

But when I type `Enter` to insert a new line. The first `Enter` somehow gets ignored and I have to type `Enter` a second time to get a new line.
AFAICS I can reproduce it any time I use completion on a tag.

This is with Eclipse 2021-12 and:
```
Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	1.19.0.20211116-0804	org.eclipse.m2e.feature
```

**Comment by mickaelistria** [comment]
This is also LSP4E: https://github.com/eclipse/lsp4e/issues/58

**Comment by mickaelistria** [comment]
Forgot to mention that the part about exclusion should be fixed already, in snapshots.

**Comment by mickaelistria** [comment]
This is fixed in [LSP4E](https://github.com/eclipse/lsp4e/), installing new snapshots of LSP4E will include the fix. Nothing further is required in m2e which gets LSP4E transitively.
