### ISSUE TITLE
POM Editor - Incorrect behavior with exclusions

### ISSUE THREAD

**Issue by gsmet** [eclipse-m2e/m2e-core#516]
In a pom, I go to a `<dependency>` block to add an exclusion.

I add the `<exclusions>` block, then I add the `<groupId>`, then the `<artifactId>`. If I use the completion to select a suggested `<artifactId>`, I end up with the `<artifactId>` (good!) AND a `<version>` (not good!) getting included, which doesn't make sense for an exclusion.
Also, the indentation is off (it might be another issue for when the `<version>` makes sense, I don't know).

See the picture of the result:
![Screenshot from 2022-01-21 13-44-26](https://user-images.githubusercontent.com/1279749/150529221-0e977460-7cc8-46cb-b989-af0f87fff7ac.png)

This is with Eclipse 2021-12 and:
```
Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	1.19.0.20211116-0804	org.eclipse.m2e.feature
```

**Comment by mickaelistria** [comment]
This should be fixed in upcoming snapshots, thanks to https://github.com/eclipse/lemminx-maven/commit/ac74f46cf6d8fe255593658b9b2c02a2a2a865c3

**Comment by gsmet** [comment]
I can confirm it works with the latest snapshots.
