### ISSUE TITLE
When adding multiple maven dependency elements the element cannot be removed via remove button

### ISSUE THREAD

**Issue by de-jcup** [eclipse-m2e/m2e-core#517]
### Situation
I played around with the new maven target possibilities and found a small bug.
Inside the target editor, I added not  only one maven dependency inside the `<dependencies>` element but multiple ones - as shown in next figure
![image](https://user-images.githubusercontent.com/11644753/150566064-73c83b82-a119-4a55-b3cf-d3eb4ff70654.png)

When you switch multi editor tab from `source` to `definition`, it looks like following:
![image](https://user-images.githubusercontent.com/11644753/150565998-a741adab-058b-4478-9068-0283eba6354b.png)

Unfortunately , you can only remove the top element (here in example labeled "asp client") but not the sub elements inside.
But you can remove it inside the source code tab, synchronization etc. works all well.

When pressing `add` button on UI are always location elements added - and these can be removed. So I am not sure if this is a bug or  a feature. If this is a feature, a different icon for the dependency elements (and not like the location or dependencies element) could be useful (IMHO).

Here the complete snippet:
```xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="asciidoctor-editor">
	<locations>
		<location includeAllPlatforms="false" includeConfigurePhase="true" includeMode="slicer" includeSource="true" type="InstallableUnit">
			<unit id="org.eclipse.sdk.ide" version="0.0.0"/>
			<repository location="https://download.eclipse.org/releases/photon/201806271001/"/>
		</location>
		<location includeDependencyDepth="infinite" includeDependencyScope="compile" includeSource="true" label="asp client" missingManifest="generate" type="Maven">
			<dependencies>
							
			<!-- https://mvnrepository.com/artifact/de.jcup.asp/asp-server-asciidoctorj-launcher -->
<dependency>
    <groupId>de.jcup.asp</groupId>
    <artifactId>asp-server-asciidoctorj-launcher</artifactId>
    <version>1.3.1</version>
</dependency>
<!-- https://mvnrepository.com/artifact/de.jcup.asp/asp-doc -->
<dependency>
    <groupId>de.jcup.asp</groupId>
    <artifactId>asp-doc</artifactId>
    <version>1.3.1</version>
</dependency>

			</dependencies>

		</location>
	</locations>
</target>
```
Remark: This is a very cool maven integration to build eclipse tooling. Thanx a lot! And this is just a mini bug - but I wanted to give feedback.

**Comment by laeubi** [comment]
@de-jcup thanks for reporting this.

This is because currently `MavenTargetLocationEditor` do not implement the `canRemove`/`remove` methods from `ITargetLocationHandler` do you like to give it a try and implement those methods?

**Comment by laeubi** [comment]
By the way: You should be able to hit the edit button on the top-element then remove it there from the UI, but supporting the remove button is much better from UX POV.

**Comment by de-jcup** [comment]
@laeubi : Thanx for fixing this so soon. I am sorry that I did not had the time to respond before - I was very busy.
