### ISSUE TITLE
Checkout as maven project gets stuck on Resolving plugin dependencies

### ISSUE THREAD

**Issue by Postremus** [eclipse-m2e/m2e-core#522]
eclipse version:
```
Version: 2021-12 (4.22.0)
Build id: 20211202-1639
```

java version:
```
openjdk version "17" 2021-09-14
OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)
```

thread dump:
[threaddump.txt](https://github.com/eclipse-m2e/m2e-core/files/7925417/threaddump.txt)

To reproduce:
1. workspace should already have at least one project
2. open the "SVN Repositories" view
3. right click on a maven project in SVN
4. checkout as maven project
5. Confirm
6. Sources are downloaded
7. Import is stuck (indefinetly) on "Resolving plugin dependencies"

**Comment by nicymike** [comment]
I also have this issue. Maybe it is related to #575.

It is stuck on Object.wait().

![image](https://user-images.githubusercontent.com/19415000/158665513-9a93f6fa-976c-4c3a-a6fe-a8016bf89891.png)

**Comment by mickaelistria** [comment]
The issue seems to come from APT support more than m2e core itself. Pease try upgrading to latest snapshots for Eclipse and m2e, using the APT support that's now part of the m2e and not in JBoss Tools.

**Comment by Postremus** [comment]
We have finally switched from svn to git.
Problem does not happen anymore.
Closing this issue, since this is solved for me.

**Comment by laeubi** [comment]
I was able to reproduce this also with git, the root cause is this one:
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/689
