### ISSUE TITLE
2021-12 version pom editor makes eclipse hang  when opened in old workspace

### ISSUE THREAD

**Issue by SoonPoong-Hong** [eclipse-m2e/m2e-core#525]
The new 2012-12 maven pom editor seems to be changed.
When I open the pom.xml file and modify , then eclipse hangs.
In the error.log pane, I can see some TimeoutException of lsp4e.

This problem seems to occur when I open a project in the **old workspace**.
And, This problem is solved by creating a new workspace, and open the project.

**Comment by SoonPoong-Hong** [comment]
I thought the new workspace would do right thing.
But, it does not.

In new workspace, the TimeoutException of lsp4e occurs.
And when I open the pom.xml, the eclipse hangs.

**Comment by mickaelistria** [comment]
Can you please try with latest snapshots from https://download.eclipse.org/technology/m2e/snapshots/latest/ ? Those received a bunch of major improvements since last release, and your issue might be fixed.

**Comment by dantran** [comment]
@mickaelistria  it fixed  this issue at my side

**Comment by mickaelistria** [comment]
@dantran Thanks for testing and reporting! Let's close and anyone can comment/reopen if it's still failing for them.

**Comment by dantran** [comment]
@mickaelistria will we see this fix at eclipse update soon?  we are currently blocked recommending eclipse-21-12, if the fix is available we can ask user to run update without the hassle of using the provided update link in this issue

**Comment by mickaelistria** [comment]
If you only use the Eclipse Simultaneous Release repository, then it won't be available in it until mid-March for the quarterly release. But we'd like to release m2e soon, ideally this week, so people who use the m2e repository should get the release immediately after that.
