### ISSUE TITLE
Improve error message for "Conflicting lifecycle mapping metadata (project packaging type="something")"

### ISSUE THREAD

**Issue by kwin** [eclipse-m2e/m2e-core#529]
Copied over from https://bugs.eclipse.org/bugs/show_bug.cgi?id=505626

In case of multiple extensions providing a lifecycle mapping metadata for the same packaging the error message is just something like 

"Conflicting lifecycle mapping metadata (project packaging type="content-package"). To enable full functionality, remove the conflicting mapping and run Maven->Update Project Configuration"

It does not state at all, in which extensions/plugins the conflicting metadata is found. In addition Properties->Maven->Lifecycle Mapping just exposes the error "Can not read pom.xml" in that case (therefore limiting the debugging capabilities) 
![Conflicting_Lifecycle_Mapping](https://user-images.githubusercontent.com/185025/151537524-bf937fc7-c3ab-40ed-9220-366546b41409.png)

**Comment by HannesWell** [comment]
I think this is not yet resolved, only the PR to update the tests was submitted.
