### ISSUE TITLE
org.eclipse.m2e.pde.connector should not conflict with built-in m2e support of bnd-maven-plugin/maven-bundle-plugin

### ISSUE THREAD

**Issue by kwin** [eclipse-m2e/m2e-core#539]
Currently `org.eclipse.m2e.pde.connector` overwrites the plugin lifecycle mapping of `bnd-maven-plugin` fully (https://github.com/eclipse-m2e/m2e-core/blob/master/org.eclipse.m2e.pde.connector/lifecycle-mapping-metadata.xml, compare with https://bugs.eclipse.org/bugs/show_bug.cgi?id=506357). An approach like https://github.com/apache/sling-ide-tooling/blob/93bcb69fe7cfad6b68d5caf838a14d3bdf887b92/eclipse/eclipse-m2e-ui/src/org/apache/sling/ide/eclipse/m2e/internal/AbstractProjectConfiguratorRunningDefaultOnIncrementalBuilds.java#L36 (probably used together the default configurator with https://github.com/apache/sling-ide-tooling/blob/93bcb69fe7cfad6b68d5caf838a14d3bdf887b92/eclipse/eclipse-m2e-ui/plugin.xml#L62) should be used.

**Comment by laeubi** [comment]
@kwin can you explain a bit more in detail where it conflicts? Actually m2e does not overwrites the mapping but extends it, so we need a concrete example to investigate any problems.

**Comment by kwin** [comment]
Ok, it turns out that a parallel installation of https://sling.apache.org/documentation/development/ide-tooling.html leads to the following errors:

```
Conflicting lifecycle mapping (plugin execution "biz.aQute.bnd:bnd-maven-plugin:6.1.0:bnd-process (execution: generate-osgi-metadata, phase: process-classes)"). To enable full functionality, remove the conflicting mapping and run Maven->Update Project Configuration.
Plugin execution not covered by lifecycle configuration: biz.aQute.bnd:bnd-maven-plugin:6.1.0:bnd-process (execution: generate-osgi-metadata, phase: process-classes)
```

Once the feature PDE integration is removed, the error vanishes. Any idea how to make one of the two extension take precedence and don't bail out with an exception?

Also I think the two missing goals from https://github.com/bndtools/bnd/blob/ddaa896bfb0e547ed563fb8d12f455d3f37fc921/maven/bnd-maven-plugin/src/main/resources/META-INF/m2e/lifecycle-mapping-metadata.xml#L8 (bnd-process-tests and test-jar) need to be added to https://github.com/eclipse-m2e/m2e-core/blob/840fb2e973d5edc1286d2c27dd24aff9a707f875/org.eclipse.m2e.pde.connector/lifecycle-mapping-metadata.xml#L41 as otherwise those goals are no longer supported during incremental build.

**Comment by laeubi** [comment]
> Any idea how to make one of the two extension take precedence and don't bail out with an exception?

I'm not a ware of any such feature maybe @mickaelistria know more about it? Maybe it would be an Option that sling no longer publish a mapping or defines some kind of upper bound? In general I think m2e might provide a feature to select what binding to use if there are multiple ones.

> Also I think the two missing goals

They should just work if you add an execution for them, in any case a reproducer project would help to investigate further.

**Comment by kwin** [comment]
> They should just work if you add an execution for them,

Indeed they do now
![Screenshot 2022-02-01 at 13 11 13](https://user-images.githubusercontent.com/185025/151966278-428e76c0-5c9a-4df5-af1a-b942869a064c.png)

Then the only issue is really two extensions with conflicting bindings.

**Comment by laeubi** [comment]
@kwin do you mind creating another ticket for support that?
Lets use your screenshot I would assume there will be an error "conflicting mapping" or something, I could guess that there could be a drop down box where I choose the desired mapping and store this somewhere in the project config (or even pom?).

Or you could try to repharese the title of this ticket if you find this more useful.

**Comment by kwin** [comment]
@laeubi Done in #549, let us track it there.

**Comment by laeubi** [comment]
@kwin how do you get those lifecycle mapping table? I thought it was a view but can't find it...

**Comment by kwin** [comment]
It is a project properties panel

**Comment by laeubi** [comment]
AH thanks never noticed that :-)
