### ISSUE TITLE
Remove deprecated code from IMaven

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#542]
There is alot deprecated stuff in IMaven we should get rid of.

**Comment by laeubi** [comment]
@HannesWell I think Ive seen a PR to "remove the last deprecated code" so can we close this now?

**Comment by HannesWell** [comment]
> @HannesWell I think Ive seen a PR to "remove the last deprecated code" so can we close this now?

Yes deprecated IMaven APi was removed with https://github.com/eclipse-m2e/m2e-core/pull/680.
The last removal of deprecated API in general was done with https://github.com/eclipse-m2e/m2e-core/pull/685

So there should not be any deprecated M2E-API any more. I also tried to replace all usage of deprecated API of external dependencies in m2e where possible.
