### ISSUE TITLE
Additional "runtime" scoped dependencies support?

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#543]
### Discussed in https://github.com/eclipse-m2e/m2e-core/discussions/461

<div type='discussions-op-text'>

<sup>Originally posted by **laeubi** December 18, 2021</sup>
Now that we correctly filter dependencies scopes it shows that it might cause confusion for[ runtime scoped dependencies](https://github.com/eclipse/tycho/issues/447).

The `runtime` scope is a bit special as maven [defines it as:](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html)

> runtime
> This scope indicates that the dependency is not required for compilation, but is for execution. Maven includes a dependency with this scope in the runtime and test classpaths, but not the compile classpath.

That mean that if we want it currently one has to select `test` scope.

I see the following options:

1. We allow to select `runtime` scope and handle it as something between `compile` and `test` (include everything `compile` would include and include `runtime` dependencies but not `test` scoped ones.
2. We add a boolean attribute `includeRuntime` that additionally include runtime scoped dependencies 
3. We do nothing an require people to explicitly include those if the only want compile scope

@akurtakov @mickaelistria @HannesWell any preferences?</div>

@akurtakov @mickaelistria @HannesWell I think it would be good t have this in before the next release see also
 - https://github.com/eclipse/tycho/issues/447

**Comment by mickaelistria** [comment]
Solution 1 seems to be the most correct from Maven and PDE POV. The "runtime" scope should also be the default scope in the UI as per expectation of target platform definition.

**Comment by laeubi** [comment]
I'll try to fix this this week, as I think we should include thin the the 1.20 release.

**Comment by laeubi** [comment]
Target used for testing [Issue_543.target.zip](https://github.com/eclipse-m2e/m2e-core/files/8000846/Issue_543.target.zip)

**Comment by laeubi** [comment]
@vogella @akurtakov @HannesWell this should shortly be available in the snapshot please test this if it works for all your cases (but keep in mind that tycho do *not* support this at the moment!) if no issues arise I'll adjust tycho support accordingly.

**Comment by laeubi** [comment]
Also fixed in tycho now: https://github.com/eclipse/tycho/issues/447
