### ISSUE TITLE
Provide an IMaven per project

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#546]
Currently IMaven is accessed via a static singleton.

We should change this in the following way:

1. There should be an adapter that allows adapting an IProject -> IMaven when the project is a m2e project we return a project scoped IMaven (could as a first step always return the static global one)
2. Register the global IMaven as a service
3. remove and/or make the accessor for IMaven internal

**Comment by HannesWell** [comment]
For clarification: What is the advantage?

> 
>     1. There should be an adapter that allows adapting an IProject -> IMaven when the project is a m2e project we return a project scoped IMaven (could as a first step always return the static global one)
> 
This could be done similar like in JDT where one can get a `IJavaProject` using `JavaCore.create(IProject)`.

In general I like it when there are only few, ideally just one, entry-points into a 'topic' from where I can get everywhere through a few intuitive steps. It makes it much easier to orientate oneself compared to when everything is distributed over multiple places that I all have to know.

**Comment by laeubi** [comment]
Adapters are much more flexible and do allow a loose coupling of things without exposing API (and you know how hard it is to change API ...)

And I don't see much value of `MavenPlugen.getInstance().getMaven(...)` over `Adapters.adapt(project, IMaven.class)`

**Comment by HannesWell** [comment]
> Adapters are much more flexible and do allow a loose coupling of things without exposing API (and you know how hard it is to change API ...)
> 
It's indeed hard. But what I always wonder about Adapters is that by providing a way as you suggested, you de-facto make it _API_ that that call will always return a corresponding `IMaven` object. You cannot simply change that an return for example an `IMaven2` object instead or just nothing. API is not only about class names and method signatures it also about behavior and behavior is IMHO much harder to enforce because it require extensive tests.

> And I don't see much value of `MavenPlugen.getInstance().getMaven(...)` over `Adapters.adapt(project, IMaven.class)`

I would suggest to make `getMaven()` a static method of `MavenPlugen`. Then `MavenPlugin` could one of the few entry-points into the Maven-world mentioned above. If there are more methods one can then enter `MavenPlugen` and see what the ContentAssist suggests me respectively what's available. With the Adapter approach it would have to be documented somewhere else (but where?) or I would have to guess it. And documentation tends to be outdated.
But this is a general question I also have for the Service approach and I could not yet get an answer for.

**Comment by laeubi** [comment]
> But what I always wonder about Adapters is that by providing a way as you suggested, you de-facto make it _API_ that that call will always return a corresponding `IMaven` object.

AN Adapter can always return null, the caller has to be aware of that, the recent eclipse adds a new `Adapters.of(...)` that returns an Optional to make this more convenient.

> You cannot simply change that an return for example an `IMaven2` object instead or just nothing.

Why not? Beside that if we mark IMaven as @noimplement we can simply enahnce the interface without this anoing x2, x3, x4 ...

> API is not only about class names and method signatures it also about behavior

The adapter behavior is well known and well defined. And its very flexible. For example I can have a bundle that only contains API and a consumer would only need to reference that. With a static singelton I'm always bound to that specific implementation bundle (and the implementation bundle must expose some of its classes as API). Thats also the power of OSGi-Services a consumer is (if not using require bundle, xfriends and all that stufff) is only bound to the API-contract but never to the implementation, so I'm free to change the Implementation, move it around or completely replace it. Togehter with semantic versioning and proper import ranges I have a very powerfull flexible toolset.

> I would suggest to make `getMaven()` a static method of `MavenPlugen`

This XPLugin static stuff is just bad style and we should not follow that. And we really should not enforce any explorative programming style with m2e API but have a documentation that tells the basics.

**Comment by mickaelistria** [comment]
I agree with @laeubi that adapters provide great opportunities.
I also agree with @HannesWell that providing APIs only via adapters is not really nice as there is no "contract" for adapters, so one cannot know when to expect adapter to be present or not.

IMO, the adapters should be IProject to IMavenProjectFacade (that could also help in plugin.xml filter expressions), and IMavenProjectFacade could add a `getMaven()` method. Both can be done separately.

**Comment by laeubi** [comment]
> IMO, the adapters should be IProject to IMavenProjectFacade (that could also help in plugin.xml filter expressions), and IMavenProjectFacade could add a `getMaven()` method. Both can be done separately.

Good idea! I think that developers extending core m2e functionality should be at least a bit familiar with the code.

**Comment by laeubi** [comment]
I think what was provided by mickael here is already the API work, the rest is internal and could be solved with more specific tickets.
