### ISSUE TITLE
Very high rate of unsuccessful installs at marketplace 

### ISSUE THREAD

**Issue by akurtakov** [eclipse-m2e/m2e-core#553]
At https://marketplace.eclipse.org/content/eclipse-m2e-maven-support-eclipse-ide there are 127 unsuccessful installs for the last 7 days.
51 of them being :

Cannot complete the install because one or more required items could not be found. Software being installed: M2E - Maven Integration for Eclipse (includes Incubating components) 1.19.0.20211116-0804 (org.eclipse.m2e.feature.feature.group 1.19.0.20211116-0804) Missing requirement: M2E Binary Project Core 1.17.4.20211002-1029 (org.eclipse.m2e.binaryproject 1.17.4.20211002-1029) requires 'bundle org.eclipse.jdt.core 3.7.0' but it could not be found Cannot satisfy dependency: From: Binary project UI 1.18.1.20210610-0713 (org.eclipse.m2e.binaryproject.ui 1.18.1.20210610-0713) To: bundle org.eclipse.m2e.binaryproject [1.16.0,2.0.0) Cannot satisfy dependency: From: M2E - Maven Integration for Eclipse (includes Incubating components) 1.19.0.20211116-0804 (org.eclipse.m2e.feature.feature.group 1.19.0.20211116-0804) To: org.eclipse.m2e.binaryproject.ui [1.18.1.20210610-0713]

**Comment by akurtakov** [comment]
Adding a reference to  https://download.eclipse.org/eclipse/updates/latest/ (for JDT)  or even https://download.eclipse.org/releases/latest/ (for lemminx deps) would hopefully improve that.

**Comment by mickaelistria** [comment]
It looks like some people are trying to install m2e on an RCP application that
* doesn't have Java installed, and
* either
  * Have "Contact all available sites" turned off, or
  * Don't have an p2 repository available that includes JDT
