### ISSUE TITLE
env.home or user.home in <localRepository> from settings.xml is not resolved properly, causing creation of needless folder

### ISSUE THREAD

**Issue by Unimeron** [eclipse-m2e/m2e-core#562]
I'm setting up a fresh installation of Eclipse 4.22.0 with m2e 1.19.0.20211116-0804. While checking my settings in `Preferences -> Maven -> User Settings`, I noticed, that the path given below _Local Repository (From merged user and global settings)_ to the local repository is not resolved properly. Here's a screenshot: 
![EclipseMavenUserSettings](https://user-images.githubusercontent.com/47747028/152600889-5b9363bf-859d-4b17-af82-b93963a01341.png)

Instead of the actual path it shows exactly the string from my .m2/settings.xml: `<localRepository>${env.home}/.m2/repository</localRepository>`.  It also doesn't work with `${user.home}`. A workaround is to just comment out the `localRepository` in settings.xml, so the default takes over.

As a strange side-effect, a directory named ${env.home} (or whatever is used in "localRepository") is created, either in the home directory itself or in the current directory where Eclipse was started from. Sometimes it's required to click "Open workspace lifecycle mappings metadata" to trigger the creation of this folder. This folder contains some sub-directories and a file named  index:
![strangeFolder](https://user-images.githubusercontent.com/47747028/152601409-d4b8b676-42bf-4e80-9337-128087a3adbb.png)

**Comment by mickaelistria** [comment]
I think this was fixed some weeks ago. Can you please try latest snapshots and report whether this issue is still present?

**Comment by bohni** [comment]
see #504
