### ISSUE TITLE
Consider inclusion/migration of jbosstools/m2e-apt

### ISSUE THREAD

**Issue by mickaelistria** [eclipse-m2e/m2e-core#578]
https://github.com/jbosstools/m2e-apt provide good support for annotation processing for m2e. As annotation processing is a standard practice used by multiple frameworks, we should consider having m2e-apt part of m2e-core.

**Comment by laeubi** [comment]
Sure, I always wondered all that cluttering of m2e stuff what makes it really hard to improve things. SO if there are no concerns e.g. regarding maintenance go for it :+1:

**Comment by mickaelistria** [comment]
I'm pretty sure their will be IP issues. But I filed https://dev.eclipse.org/ipzilla/show_bug.cgi?id=23942 and we'll see where it goes.

**Comment by mickaelistria** [comment]
CQ is pre-appproved, we can soon merge. I prepared #579
@waynebeaton do you confirm that we still have to squash history before merging such code in? I prepared the PR that way, but I think if we can keep history, it can be useful and worth reorganizing my PR.

**Comment by guillaumecle** [comment]
with the move of `m2e-apt` to `m2e-core`, will the publish location change? `https://download.jboss.org/jbosstools/updates/m2e-extensions/m2e-apt/` and `org.eclipse.m2e.sse.ui.feature.feature.group`

Also would it be possible to have a release of `m2e-apt` for this fix jbosstools/m2e-apt#79
