### ISSUE TITLE
Warning: NLS missing message: MavenTargetLocationWizard_11 in: org.eclipse.m2e.pde.ui.editor.messages

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#580]
I see at startup the following message cc @laeubi while using latest snapshot

Warning: NLS missing message: MavenTargetLocationWizard_11 in: org.eclipse.m2e.pde.ui.editor.messages

**Comment by laeubi** [comment]
@vogella do you think you can investigate/provide a fix? It might be that this message is simply no longer used but was not deleted from Messages java file.
