### ISSUE TITLE
xml:space="preserve" is ignored by Maven POM Editor

### ISSUE THREAD

**Issue by OLibutzki** [eclipse-m2e/m2e-core#581]
The Maven POM Editor which has been introduced in the 2021-12 release train ignores the `xml:space="preserve"` directive while formatting.

In my particular use case this leads to a broken configuration of the `spring-boot-maven-plugin` as the whitespace in `BPE_DELIM_JAVA_TOOL_OPTIONS` is removed by the formatter.

```
<project>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <image>
                        <env>
                            <BPE_DELIM_JAVA_TOOL_OPTIONS xml:space="preserve"> </BPE_DELIM_JAVA_TOOL_OPTIONS>
                            <BPE_APPEND_JAVA_TOOL_OPTIONS>-XX:+HeapDumpOnOutOfMemoryError</BPE_APPEND_JAVA_TOOL_OPTIONS>
                        </env>
                    </image>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by akurtakov** [comment]
@angelozerr This sounds like lemminx problem, right?

**Comment by mickaelistria** [comment]
@OLibutzki Can you please report it to https://github.com/lemminx/lemminx/issues which does provide the formatting?

**Comment by OLibutzki** [comment]
@mickaelistria there seems to be an issue: https://github.com/eclipse/lemminx/issues/826

I close this one as duplicate.

**Comment by laeubi** [comment]
Duplicate of eclipse/lemminx#826

**Comment by angelozerr** [comment]
> @angelozerr This sounds like lemminx problem, right?

Yes, we need to improve our formatting support. Ideally we must redo our formatting support because it doesn't take care of invalid XML content to format (we loose some invalid content).
