### ISSUE TITLE
m2e contributes an embedded jar file that contains unsigned content and therefore cannot be notarized on macOS

### ISSUE THREAD

**Issue by jonahgraham** [eclipse-m2e/m2e-core#591]
The 2022-03 M3 build currently cannot be fully notarizared due to unsigned content that comes from (AFAICT) m2e. Although it is an upstream project (jansi) that contains the actual native parts.

The error message from the notarization is:
```json
{
    "logFormatVersion": 1,
    "jobId": "5d49fcdd-e490-479a-8139-a66499aa33f7",
    "status": "Invalid",
    "statusSummary": "Archive contains critical validation errors",
    "statusCode": 4000,
    "archiveFilename": "eclipse-java-2022-03-M3-macosx-cocoa-x86_64-1445086157277215824.dmg",
    "uploadDate": "2022-02-24T15:01:21Z",
    "sha256": "02f07c7ecc3aa198325f76809a52bd7adc9d4c18c242730969ad6652cda9bb0d",
    "ticketContents": null,
    "issues": [
      {
        "severity": "error",
        "code": null,
        "path": "eclipse-java-2022-03-M3-macosx-cocoa-x86_64-1445086157277215824.dmg/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.m2e.maven.runtime_1.18.2.20211123-1648/jars/jansi-2.4.0.jar/org/fusesource/jansi/internal/native/Mac/x86/libjansi.jnilib",
        "message": "The binary is not signed.",
        "docUrl": null,
        "architecture": "i386"
      },
      {
        "severity": "error",
        "code": null,
        "path": "eclipse-java-2022-03-M3-macosx-cocoa-x86_64-1445086157277215824.dmg/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.m2e.maven.runtime_1.18.2.20211123-1648/jars/jansi-2.4.0.jar/org/fusesource/jansi/internal/native/Mac/x86/libjansi.jnilib",
        "message": "The signature does not include a secure timestamp.",
        "docUrl": null,
        "architecture": "i386"
      },
      {
        "severity": "error",
        "code": null,
        "path": "eclipse-java-2022-03-M3-macosx-cocoa-x86_64-1445086157277215824.dmg/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.m2e.maven.runtime_1.18.2.20211123-1648/jars/jansi-2.4.0.jar/org/fusesource/jansi/internal/native/Mac/arm64/libjansi.jnilib",
        "message": "The binary is not signed with a valid Developer ID certificate.",
        "docUrl": null,
        "architecture": "arm64"
      },
      {
        "severity": "error",
        "code": null,
        "path": "eclipse-java-2022-03-M3-macosx-cocoa-x86_64-1445086157277215824.dmg/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.m2e.maven.runtime_1.18.2.20211123-1648/jars/jansi-2.4.0.jar/org/fusesource/jansi/internal/native/Mac/arm64/libjansi.jnilib",
        "message": "The signature does not include a secure timestamp.",
        "docUrl": null,
        "architecture": "arm64"
      },
      {
        "severity": "error",
        "code": null,
        "path": "eclipse-java-2022-03-M3-macosx-cocoa-x86_64-1445086157277215824.dmg/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.m2e.maven.runtime_1.18.2.20211123-1648/jars/jansi-2.4.0.jar/org/fusesource/jansi/internal/native/Mac/x86_64/libjansi.jnilib",
        "message": "The binary is not signed.",
        "docUrl": null,
        "architecture": "x86_64"
      },
      {
        "severity": "error",
        "code": null,
        "path": "eclipse-java-2022-03-M3-macosx-cocoa-x86_64-1445086157277215824.dmg/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.m2e.maven.runtime_1.18.2.20211123-1648/jars/jansi-2.4.0.jar/org/fusesource/jansi/internal/native/Mac/x86_64/libjansi.jnilib",
        "message": "The signature does not include a secure timestamp.",
        "docUrl": null,
        "architecture": "x86_64"
      }
    ]
  }
```

**Comment by HannesWell** [comment]
You're right the jansi-jar is contributed by m2e and it is indeed not jar-signed, but it is embedded into the jar of the `org.eclipse.m2e.maven.runtime` bundle which itself is signed just like other Eclipse plug-in jars.

I wonder why this is an issue because all jars nested in `org.eclipse.m2e.maven.runtime` (at least those into which I looked which are not all, but a few) are not signed and this has been like that in the past already. I only checked the 1.18.0 release of m2e from last summer but assume that this is the situation since ever.

**Comment by jonahgraham** [comment]
@HannesWell it is ok if the embedded jars aren't signed - the issue isn't jarsigning, it is the mac natives are mac signed - the `*.jnilib`s - full list of missing signatures in the error messages.

**Comment by jonahgraham** [comment]
The embedded jansi was upgraded from 1.17.1 to 2.4.0 in `org.eclipse.m2e.maven.runtime` - that older version did have a `.jnilib` in a different location - but perhaps it was signed. Someone on a mac can check that.

Either way, Apple have been tightening the requirements and the depth they search through jars/zips to find more and more unsigned native code. With each release of Eclipse EPP we find more problems.

Normally I would say that we handle this in Orbit, but not sure that works with the flow here.

**Comment by HannesWell** [comment]
To be honest, I have no idea how this problem could be solved respectively what we could do at m2e to solve it.
I only work on Windows and Linux and have almost no knowledge about what's happening on Mac or how we could mac sign those artifacts by ourself (I can probably count on one hand how often I have used a Mac in my life).

Furthermore jansi is only an indirect dependency that is managed by maven. The upgrade from 1.17.1 to 2.4.0 happened with the switch from Maven `3.8.1` to `3.8.4` and m2e does not use it directly.

I would suggest to open a corresponding issue in jansi, but I assume that is too late now.

Maybe @mickaelistria or @akurtakov can help?

**Comment by jonahgraham** [comment]
If m2e can consume this from Orbit then it would be trivial in this case, add an empty file called `eclipse-sign-jnilibs.properties` to the bundle and the orbit build will sign all the `.jnilib`s in it.

See https://git.eclipse.org/r/c/orbit/orbit-recipes/+/180107 for when I implemented that in Orbit last year for JNA.

While I know that getting rid of orbit is a long term goal - the special cases will continue to need Orbit. Signing `.jnilib` files may remain one of those special cases. For example JNA project will not provide signed `.jnilib` files, in part out of principle (ref: https://github.com/java-native-access/jna/issues/1306#issuecomment-772696095)

I have requested if jansi are able to do the signing as that would be the simplest, and then m2e just needs to update to that version. See https://github.com/fusesource/jansi/issues/232

**Comment by laeubi** [comment]
@jonahgraham thanks for the effort and information. @HannesWell maybe we could do the same thing that orbit does?

What I'm wondering about: Are the native libs actually used if the jar is embedded?

**Comment by HannesWell** [comment]
> I have requested if jansi are able to do the signing as that would be the simplest, and then m2e just needs to update to that version. See [fusesource/jansi#232](https://github.com/fusesource/jansi/issues/232)

Thanks for that.

> If m2e can consume this from Orbit then it would be trivial in this case, add an empty file called `eclipse-sign-jnilibs.properties` to the bundle and the orbit build will sign all the `.jnilib`s in it.
> 
> See https://git.eclipse.org/r/c/orbit/orbit-recipes/+/180107 for when I implemented that in Orbit last year for JNA.
> 
> While I know that getting rid of orbit is a long term goal - the special cases will continue to need Orbit. Signing `.jnilib` files may remain one of those special cases. For example JNA project will not provide signed `.jnilib` files, in part out of principle (ref: [java-native-access/jna#1306 (comment)](https://github.com/java-native-access/jna/issues/1306#issuecomment-772696095))
> 

Consuming jansi from Orbit should be possible, although it will likely not work seamlessly. But in the worst case the mac-signed jansi jar can be put into o.e.m2e.maven.runtime manually which I think would be ok for as an intermediate quick-fix given that jansi signs its jars in the future.

> @HannesWell maybe we could do the same thing that orbit does?

That would definitely be the nicer option. I just skimmed the given code excerpt and if we just have to add some more elements a the pom.xml it should be possible, given we have access to all used resources. But I can have a deeper look into it this evening.

> What I'm wondering about: Are the native libs actually used if the jar is embedded?

AFAICT Jansi is used for coloring the console print-out if one specifies the corresponding Maven-property.
I also thought about excluding it temporary. We would likely lose colored print-outs and I cannot tell if this would cause other problems but if this is only for one release and jansi fixes the signing it could be an option if everything else fails.

**Comment by laeubi** [comment]
> if we just have to add some more elements a the pom.xml it should be possible

We already sign the bnd-lib stuff in m2e before we publish the repository.

> AFAICT Jansi is used for coloring the console print-out if one specifies the corresponding Maven-property.

For maven-cli, yes, but for m2e I think this just don't work as the native parts are for the native windows/mac/linux console and not for the eclipse embedded one.

**Comment by HannesWell** [comment]
Setting up the maintenance branch was surprisingly simple, thanks to the Jenkins Multibranche Pipeline setup.

@jonahgraham you can find the snapshot repo for `m2e-1.20.1` here:
https://download.eclipse.org/technology/m2e/snapshots/1.20.1/
Is this sufficient for you to test with the SimRel build if the signing is fine now?

**Comment by HannesWell** [comment]
There are test-failures on the maintenance branch which I suspect come from the fact the build always uses the current master of the m2e-tests sub-module, which is already adapted to the breaking changes of 2.0.0. Therefore I think this is OK.

**Comment by jonahgraham** [comment]
@HannesWell I can push that p2 repo to simrel for the m2e team and report back. When you have an updated/final version you can update again. It will take a few hours (at least, as I have to get in front of a computrt) and I'll report back later. You can speed things up by doing the simrel Gerrit as the rest I can do from my phone.

**Comment by jonahgraham** [comment]
A commit like https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/190719 is what I am not setup to do on my phone.

**Comment by HannesWell** [comment]
> A commit like https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/190719 is what I am not setup to do on my phone.

Done here: https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/191247

**Comment by jonahgraham** [comment]
Thank you @HannesWell - everything is notarized now. If you (or others) need to test the packages will be available for a day or so here: https://download.eclipse.org/technology/epp/staging/

Let me know if you need me to approve/submit the final build of m2e.

**Comment by HannesWell** [comment]
> Thank you @HannesWell - everything is notarized now. If you (or others) need to test the packages will be available for a day or so here: https://download.eclipse.org/technology/epp/staging/

Great. Thanks for the instructions. I did a few rudimentary tests with the staged build and it looks fine.

@mickaelistria, @akurtakov, @laeubi should we release the 1.20.1 version then? Could you do that? I won't have time to do that before my vacation till the end of this week and I think we should not wait longer than necessary.

**Comment by mickaelistria** [comment]
Yes, we should release 1.20.1 now. I believe we'll need to author custom copy scripts for this one, but nothing too difficult.

**Comment by HannesWell** [comment]
> Yes, we should release 1.20.1 now. I believe we'll need to author custom copy scripts for this one, but nothing too difficult.

Since there was no other release in the meantime I think the regular `promote-snapshots-to-release` Jenkins job with `releaseVersion` value `1.20.1` should be fine because it can also become the latest release.

@mickaelistria if you don't have the time to perform the release I would be available to do this this evening.

What are the exact steps to do?
1. Run `promote-snapshots-to-release` Jenkins job with `releaseVersion` value `1.20.1`
2. Create and push git tag `1.20.1` on the maintenance branch.
3. `Create a new Release` here https://projects.eclipse.org/projects/technology.m2e
4. Update release notes (is it sufficient to add them only on the master branch? Otherwise It should be the first step).
5. Send an Announcement to m2e-dev similar to https://www.eclipse.org/lists/m2e-dev/msg02464.html stating that only the *.jnilib files are signed now.
6. Update the SimRel contribution

Anything else?

**Comment by mickaelistria** [comment]
> If you don't have the time to perform the release I would be available to do this this evening.

I can find time if necessary, but I'm glad if you can take care of it ;)

> Since there was no other release in the meantime I think the regular promote-snapshots-to-release Jenkins job with releaseVersion value 1.20.1 should be fine because it can also become the latest release.
> [...]
> 1. Run promote-snapshots-to-release Jenkins job with releaseVersion value 1.20.1

promote-snapshots-to-release does turn latest snapshots for *master* into a release. I don't think it's what you want here.
You may need to create a similar job as promote-snapshots-to-release to copy the content of https://download.eclipse.org/technology/m2e/snapshots/1.20.1/ to m2e/releases/1.20.1 and m2e/releases/latest

> What are the exact steps to do?

Steps 2 to 6 are correct, however I suggest you prioritize 2 and 6 over 3,4,5.

**Comment by HannesWell** [comment]
> > If you don't have the time to perform the release I would be available to do this this evening.
> 
> I can find time if necessary, but I'm glad if you can take care of it ;)

Sure I'll take care of this :)

> promote-snapshots-to-release does turn latest snapshots for _master_ into a release. I don't think it's what you want here. You may need to create a similar job as promote-snapshots-to-release to copy the content of https://download.eclipse.org/technology/m2e/snapshots/1.20.1/ to m2e/releases/1.20.1 and m2e/releases/latest
> 
From reading the configuration of `promote-snapshots-to-release` I expect it would do exactly that when being launched with `releaseVersion=1.20.1`. The first command is the following and all subsequent commands use the copied repo:
```
ssh genie.m2e@projects-storage.eclipse.org cp -r /home/data/httpd/download.eclipse.org/technology/m2e/snapshots/${releaseVersion} /home/data/httpd/download.eclipse.org/technology/m2e/releases/${releaseVersion}
```

> > What are the exact steps to do?
> 
> Steps 2 to 6 are correct, however I suggest you prioritize 2 and 6 over 3,4,5.

Alright, I will do steps 1, 2 and 6 first.

**Comment by mickaelistria** [comment]
> From reading the configuration of promote-snapshots-to-release I expect it would do exactly that when being launched with releaseVersion=1.20.1. The first command is the following and all subsequent commands use the copied repo:

Ah OK; good then. I have not much memory of this particular scripts and its latest changes, so I didn't realize it was already capable of promoting branches. Good then.

**Comment by jonahgraham** [comment]
> 3. `Create a new Release` here https://projects.eclipse.org/projects/technology.m2e
> [...]
> 6. Update the SimRel contribution
> 
> Anything else?

Once 3 and 6 are done - send a response to Wayne's participation email to update the included version in SimRel 2022-03: https://www.eclipse.org/lists/cross-project-issues-dev/msg19014.html

**Comment by HannesWell** [comment]
Steps 1 to 6 are all performed. I hope everything worked well (but what I have checked looks good).

> > 3. `Create a new Release` here https://projects.eclipse.org/projects/technology.m2e
> >    [...]
> > 4. Update the SimRel contribution
> > 
> > Anything else?
> 
> Once 3 and 6 are done - send a response to Wayne's participation email to update the included version in SimRel 2022-03: https://www.eclipse.org/lists/cross-project-issues-dev/msg19014.html

I have done that as well.
The only thing I'm unsure about at the moment is if we have to start an IP Due Diligance Process for this release Wayne mentioned in his E-Mail?

@jonahgraham once you have submitted M2E's SimRel contribution update and confirmed that everything works well now, I would consider this issue as resolved.

**Comment by jonahgraham** [comment]
👍 The simrel change is submitted. Thanks @HannesWell for doing all this work. I think it is also great that someone else has more knowledge of the release process now.

**Comment by HannesWell** [comment]
> 👍 The simrel change is submitted. Thanks @HannesWell for doing all this work. I think it is also great that someone else has more knowledge of the release process now.

Great. Thanks and you are very welcome.
It is always interesting to learn new things and I agree the more people know the process the better. :)
