### ISSUE TITLE
Invalid plugin configuration for aliased elements

### ISSUE THREAD

**Issue by runeflobakk** [eclipse-m2e/m2e-core#598]
There seems to be an erroneous warning when using an _alias_ for a configuration parameter when configuring a plugin in the POM. The warning is:
> Invalid plugin configuration: 

followed by the name of the element which is an _alias_ for the actual field in the Mojo implementation. The type of the warning is "Language Servers".

According to the [Maven documentation](https://maven.apache.org/developers/mojo-api-specification.html#the-descriptor-and-annotations), a Maven plugin may specify an
> alias which can be used to configure this parameter from the POM. This is primarily useful to improve user-friendliness, where Mojo field names are not intuitive to the user or are otherwise not conducive to configuration via the POM.

My environment is:
MacOS Monterey
Eclipse version: 2021-12 (4.22) Build id: I20211124-1800

M2E - Maven Integration for Eclipse (includes Incubating components) 1.20.0.20220210-1034
M2E - POM Editor (Legacy) using WebTools SourceEditing UI	1.18.3.20220122-2204
M2E - POM Editor using LemMinX language server (includes Incubating components)	1.18.4.20220127-1634

---

I observe this when configuring the [license-maven-plugin](https://mycila.carbou.me/license-maven-plugin/), even though the same editor offers the tags as auto-complete, with indicated content types as String and String[]. 

<img width="745" alt="license-plugin-header-warn" src="https://user-images.githubusercontent.com/174823/156207399-04b5e86a-33d6-4d36-a5bd-20e7a34abbbc.png">

<img width="738" alt="license-plugin-excludes-warn" src="https://user-images.githubusercontent.com/174823/156207425-810a3081-90a7-4ccc-b6d1-79e8c960a6c5.png">

In this case, the warnings reads as 
```
Invalid plugin configuration: header
Invalid plugin configuration: excludes
```

The license-maven-plugin seems to be using aliases as a deprecation facility, but it is really just an alias for a configuration parameter, which should be treated as valid.

If I run the following command (may be used outside a Maven project)
```sh
mvn help:describe -Ddetail -Dplugin=com.mycila:license-maven-plugin:4.1 -Dgoal=check
```

I see the following:
```
...
    legacyConfigExcludes
      Alias: excludes
      User property: license.excludes
      Specifies files, which are excluded in the check. By default, only the
      files matching the default exclude patterns are excluded.
      Deprecated. use {@link LicenseSet#excludes}

    legacyConfigHeader
      Alias: header
      User property: license.header
      Location of the header. It can be a relative path, absolute path,
      classpath resource, any URL. The plugin first check if the name specified
      is a relative file, then an absolute file, then in the classpath. If not
      found, it tries to construct a URL from the location.
      Deprecated. use {@link LicenseSet#header}
```
So reading the output from `mvn help:describe` suggests that I am indeed using deprecated configuration directives. Though they are still available and valid as aliases, and suggested by the auto-complete.

Example POM for reproducing the issue:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>plugin-alias-warn</artifactId>
    <groupId>com.github.runeflobakk.eclipse</groupId>
    <version>1-SNAPSHOT</version>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>com.mycila</groupId>
                    <artifactId>license-maven-plugin</artifactId>
                    <version>4.1</version>
                    <configuration>
                        <header>license-header.txt</header>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>
</project>

```

**Comment by mickaelistria** [comment]
This is now supposed to be fixed in upcoming snapshots
