### ISSUE TITLE
NPE in org.eclipse.m2e.core.internal.embedder.EclipseLogger.warn(String, Throwable) when Throwable null

### ISSUE THREAD

**Issue by rakus** [eclipse-m2e/m2e-core#603]
Eclipse 2021-12 / org.eclipse.m2e.core_1.18.3.20211018-0804.jar
EclipseLogger throws a NPE when one of the `(String, Throwable)` methods is called and the Throwable is null.
This should be more forgiving and forward to  the corresponding `(String)` method in that case.
Current code:
```
  @Override
  public void warn(String msg, Throwable t) {
    if(isWarnEnabled()) {
      log.warn(msg + " " + t.getMessage(), t);
    }
  }
```

**Comment by laeubi** [comment]
DO you like to propose a patch?

**Comment by rakus** [comment]
This will take a while. First have to read the ECA and clarify whether I
