### ISSUE TITLE
POM-Editor not closed when pom-file is deleted

### ISSUE THREAD

**Issue by HannesWell** [eclipse-m2e/m2e-core#607]
When one has opened a pom.xml in a the POM-Editor and deletes that pom.xml file (for example when noticing that the pom.xml is not necessary for a Plug-in Project due to Tycho-build), the POM-Editor is not closed automatically.

For other files this usually happens automatically and I assumed it would be handled deep in the Eclipse-Platform (likely in the vicinity of the `org.eclipse.core.resources`), therefore I'm a bit surprised this is not the case for the POM-Editor.

**Comment by mickaelistria** [comment]
I think it's automatically handled by the Platform when the editor input is a FileEditorInput, but maybe it's not the case here?
Or maybe Platform does call what's necessary for the editor to be disposed, but something fails in the editor itself?

**Comment by mickaelistria** [comment]
I could write a test case that verifies this issue: https://github.com/eclipse-m2e/m2e-core/pull/612

**Comment by HannesWell** [comment]
Thank you Mickael for the remarks and the tests. If you don't have the time to look into this, I can take care of this later.

**Comment by HannesWell** [comment]
Thanks Mickael.
