### ISSUE TITLE
m2e link dependency is bad ver 1.20.1 in eclipse 4.22, it's good ver 1.18.2 in eclipse 4.21

### ISSUE THREAD

**Issue by takeseem** [eclipse-m2e/m2e-core#608]
m2e	1.18.2.20211011-2139 in eclipse 4.21.0 is good.
but m2e 1.20.1.20220227-1319 in eclipse 4.22.0 is bad.
![image](https://user-images.githubusercontent.com/4768523/158182908-6b8bbc6a-146c-4ad8-ae8d-95d71e7e7317.png)

**Comment by mickaelistria** [comment]
Can you please try latest m2e snapshots from https://download.eclipse.org/technology/m2e/snapshots/latest/ ?

**Comment by takeseem** [comment]
thanks for your help. (my eclipse 4.21 install spring STS3 plugin it's ok)

may be need a wtp xml editor will work ok.

so I download eclipse EE 4.22, i found the work method:
1. windows -> Preferences -> File Associations: set *.xml and pom.xml defult editor is XML Editor
2. reopen use XML Editor, it's work for me.
![image](https://user-images.githubusercontent.com/4768523/158212323-5362c0d5-b20a-440b-9491-17c7a57c868f.png)

**Comment by takeseem** [comment]
m2e pom.xml editor in eclipse 4.22 difference 4.21

1. it's good for me.  (M2E - POM Editor (Legacy) using WebTools SourceEditing UI)
2. it have some bug when link to dependcies other pom.xml. (M2E - POM Editor using LemMinX language server (includes Incubating components))

![image](https://user-images.githubusercontent.com/4768523/158479381-412ddbf3-6083-4d7a-a072-702db4572fde.png)

**Comment by takeseem** [comment]
That's too bad, the current m2e version is too slow.

Best in parallel for a long time 's good.

**Comment by mickaelistria** [comment]
Please report issue dedicated to built time and consider contributing a fix.
