### ISSUE TITLE
No files are generated with using APT with 2.0.0.20220412-1153

### ISSUE THREAD

**Issue by mpet** [eclipse-m2e/m2e-core#635]
Hi,
I have a maven multi-module project with an "annotation processor" module and a "processor-user" module.

I have installed the m2e with the APT included:
  M2E  2.0.0.20220412-1153

I have setup the APT processing for the processor-user module. The pom.xml has a dependency to the "annotation processor"
and

```
 <build>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <version>${build.helper.maven.plugin.version}</version>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <sources>
                                <source>${project.build.directory}/generated-sources/annotations/</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>

<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${maven.compiler.plugin.version}</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
```

From within Eclipse I use menu Project --> Clean 
it has the checkbox "start a build immediately" check and the radio button "Build only the selected projects" checked.
but nothing happens.

What needs to be done to generate my classes?

//mike

**Comment by mickaelistria** [comment]
Can you please try installing the 2.0.0 snapshots as described in reader? Those are supposed to include apt support without need for external plugins, and that may help your case.

**Comment by mpet** [comment]
I tried:
m2e-snapshots - https://download.eclipse.org/technology/m2e/snapshots/latest/
//mike










+++++++++++++

**Comment by mpet** [comment]
@mickaelistria I don't know. I have not tried for this project. Not sure what you mean with regression...

//mike

**Comment by mpet** [comment]
I tried to downgrade using:

1. https://download.eclipse.org/technology/m2e/releases/latest/

M2E - Maven Integration for Eclipse (includes Incubating components)	1.20.1.20220227-1319	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e

2. https://jbosstools.github.io/m2e-apt/latest/ ( Not working)

Tried this: the m2e discovery catalog : Window > Preferences > Maven > Discovery > Open Catalog

m2e-apt 1.5.3.20191108

Still no classes generated when doing a "Clean" and "Build" from eclipse menu.

Is there something I can check that should be in my maven modules. I checked the following files:

.settings/org.eclipse.jdt.apt.core.prefs
========================
eclipse.preferences.version=1
org.eclipse.jdt.apt.aptEnabled=true
org.eclipse.jdt.apt.genSrcDir=target\\generated-sources\\annotations
org.eclipse.jdt.apt.genTestSrcDir=target\\generated-test-sources\\test-annotations

.settings/org.eclipse.jdt.core.prefs
======================
eclipse.preferences.version=1
org.eclipse.jdt.core.compiler.codegen.targetPlatform=11
org.eclipse.jdt.core.compiler.compliance=11
org.eclipse.jdt.core.compiler.problem.enablePreviewFeatures=disabled
org.eclipse.jdt.core.compiler.problem.forbiddenReference=warning
org.eclipse.jdt.core.compiler.problem.reportPreviewFeatures=ignore
org.eclipse.jdt.core.compiler.processAnnotations=enabled
org.eclipse.jdt.core.compiler.release=disabled
org.eclipse.jdt.core.compiler.source=11

.factory_path has many jar dependencies. Not sure why so many ? Should it not only be my maven module containing the processor?

My processor module have defined a src/main/resources//META-INF/services/javax.annotation.processing.Processor containing the processor with package name and classname.

The annotation processor is included as a dependency my annotation-usage module. Is there something special I need to do in the annotation-usage module to make use of the annotation processor as a maven module ( more than defining a dependency)?

All hints appreciated since it stopping us from using Eclipse.

//mike

**Comment by mickaelistria** [comment]
OK, so apt is not working at all for your case. Can you please build a very minimal project that allows to reproduce the issue and share it so we can more easily give it a try and even create an automated test from it?

**Comment by mpet** [comment]
@mickaelistria  I will try to create a  minimal project.

**Comment by mpet** [comment]
@mickaelistria I have created a minmal project ( but it still has some company related naming in it ). Could I send it to you somehow without going  public ( it is ok to share in a minimal group)?

I am using Eclipse 4.22. 
1. From within Eclipse. Select 2 maven modules "annotations generator" and "processor-user". From Eclipse menu "Project" --> "Clean ..." 
Then there are no files generated in /processor-user/target/generated-sources/annotations
2. From within Eclipse or via command line run maven:
 ```
mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true

````
Then you should see generated classes in packages that ends with:

actions
example
configuration
jcat

( Eclipse will show some compiler error since the depending classes is not there.)

So just let me know where I can send the zip/tar ( which format you prefer)?

//mike

**Comment by mickaelistria** [comment]
Sorry, I personally won't consider testing or supporting stuff that cannot be shared publicly. Please try to reduce the example to not have such restricted content.
If reducing the example seems too hard, I'd recommend you get in touch with developers (eg @laeubi ) who can provide commercial support for your needs and who would be able to build some public example and patch for it.

**Comment by mpet** [comment]
ok. I will try to make the example more simple.

**Comment by mpet** [comment]
@mickaelistria  our company is a contributor to Eclipse foundation. That does not change the the above?

**Comment by mickaelistria** [comment]
The project is an OSS project under EPL license. It's much easier and more natural to work with open-source examples.

**Comment by mpet** [comment]
Hi @mickaelistria 

I found a much easier way for all of us :-)

https://www.baeldung.com/java-annotation-processing-builder

git clone https://github.com/eugenp/tutorials.git

Import into Eclipse using 

![image](https://user-images.githubusercontent.com/1445826/163386422-5e322038-bddf-4aea-b233-afc1db70d24d.png)

select the 3 modules for annotations.

Then when import is done.

1. Select maven modules and run "Clean..." from within Eclipse.

![image](https://user-images.githubusercontent.com/1445826/163387455-6f428107-e761-4683-94b4-b6142f145b1a.png)

This is what I have selected.

![image](https://user-images.githubusercontent.com/1445826/163388298-6ca0811a-ee8e-4d87-813d-cb2f917ab1c8.png)

This is the result:

![image](https://user-images.githubusercontent.com/1445826/163388481-4618aca9-3d70-4748-b705-148d2adb56dd.png)

No PersonBuilder is generated.


3. Running with maven

```
mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
```

![image](https://user-images.githubusercontent.com/1445826/163386723-7ffe5ee1-4a12-4ca2-8d24-0d050c9c2083.png)

I can see that the class PersonBuilder is generated.

**Comment by mpet** [comment]
@mickaelistria  is it sufficient?

**Comment by mickaelistria** [comment]
@mpet seems like an easily accessible and simple example.

**Comment by mickaelistria** [comment]
Hsve you tried tweaking options in right-click on project > Properties > Maven > Annotation Processing ?

**Comment by mpet** [comment]
@mickaelistria what do you suggest to tweak?

**Comment by mickaelistria** [comment]
I migrated documentation from jbosstools-apt to https://github.com/eclipse-m2e/m2e-core/blob/master/org.eclipse.m2e.apt.ui/README.md . Does this help?

**Comment by mpet** [comment]
@mickaelistria  I tried both options in pom.xml and nothing happened.

I added 'j**dt_apt**' as well as '**maven_plugin**' as values into annotation-user module and did a "Clean..." from within Eclipse.
Still nothing happens. So it seems this functionality is broken. Does it work for you @mickaelistria ?

br,

//mike

Below pom.xml is from annotation-user module using value 'maven_plugin' but it did not work.

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <artifactId>annotation-user</artifactId>
    <name>annotation-user</name>

    <parent>
        <groupId>com.baeldung</groupId>
        <artifactId>annotations</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>
    
  <properties>
  <m2e.apt.activation>maven_plugin</m2e.apt.activation>
</properties>

    <dependencies>
        <dependency>
            <groupId>com.baeldung</groupId>
            <artifactId>annotation-processing</artifactId>
            <version>${project.parent.version}</version>
        </dependency>
    </dependencies>

</project>
```

**Comment by mpet** [comment]
@mickaelistria  any progress?

I tried to debug of the plug-in.

I cloned this repo but I get errors in Eclipse 4.22

![image](https://user-images.githubusercontent.com/1445826/163952459-7039690b-9827-4237-bb04-55f2087b7f3d.png)

Do I need to do anything specific?

I aslo tried:

```
 mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
```
This is the error I got:
```
$ mvn clean install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true
Downloading from dsi-mje-nexus-sero: https://arm2s10-eiffel026.eiffel.gic.ericsson.se:8443/nexus/content/groups/public/org/eclipse/tycho/extras/tycho-pomless/2.7.1/tycho-pomless-2.7.1.pom
Downloaded from dsi-mje-nexus-sero: https://arm2s10-eiffel026.eiffel.gic.ericsson.se:8443/nexus/content/groups/public/org/eclipse/tycho/extras/tycho-pomless/2.7.1/tycho-pomless-2.7.1.pom (2.6 kB at 2.3 kB/s)
Downloading from dsi-mje-nexus-sero: https://arm2s10-eiffel026.eiffel.gic.ericsson.se:8443/nexus/content/groups/public/org/eclipse/tycho/extras/tycho-extras/2.7.1/tycho-extras-2.7.1.pom
Downloaded from dsi-mje-nexus-sero: https://arm2s10-eiffel026.eiffel.gic.ericsson.se:8443/nexus/content/groups/public/org/eclipse/tycho/extras/tycho-extras/2.7.1/tycho-extras-2.7.1.pom (6.5 kB at 6.0 kB/s)
Downloading from dsi-mje-nexus-sero: https://arm2s10-eiffel026.eiffel.gic.ericsson.se:8443/nexus/content/groups/public/io/takari/polyglot/polyglot-common/0.4.8/polyglot-common-0.4.8.pom
Downloaded from dsi-mje-nexus-sero: https://arm2s10-eiffel026.eiffel.gic.ericsson.se:8443/nexus/content/groups/public/io/takari/polyglot/polyglot-common/0.4.8/polyglot-common-0.4.8.pom (1.0 kB at 1.5 kB/s)
Downloading from dsi-mje-nexus-sero: https://arm2s10-eiffel026.eiffel.gic.ericsson.se:8443/nexus/content/groups/public/io/takari/polyglot/polyglot/0.4.8/polyglot-0.4.8.pom
Downloaded from dsi-mje-nexus-sero: https://arm2s10-eiffel026.eiffel.gic.ericsson.se:8443/nexus/content/groups/public/io/takari/polyglot/polyglot/0.4.8/polyglot-0.4.8.pom (8.8 kB at 14 kB/s)
Downloading from dsi-mje-nexus-sero: https://arm2s10-eiffel026.eiffel.gic.ericsson.se:8443/nexus/content/groups/public/org/eclipse/tycho/extras/tycho-pomless/2.7.1/tycho-pomless-2.7.1.jar
Downloading from dsi-mje-nexus-sero: https://arm2s10-eiffel026.eiffel.gic.ericsson.se:8443/nexus/content/groups/public/io/takari/polyglot/polyglot-common/0.4.8/polyglot-common-0.4.8.jar
Downloaded from dsi-mje-nexus-sero: https://arm2s10-eiffel026.eiffel.gic.ericsson.se:8443/nexus/content/groups/public/org/eclipse/tycho/extras/tycho-pomless/2.7.1/tycho-pomless-2.7.1.jar (30 kB at 171 kB/s)
Downloaded from dsi-mje-nexus-sero: https://arm2s10-eiffel026.eiffel.gic.ericsson.se:8443/nexus/content/groups/public/io/takari/polyglot/polyglot-common/0.4.8/polyglot-common-0.4.8.jar (35 kB at 124 kB/s)
[WARNING] org.eclipse.tycho.extras:tycho-pomless build extension will be replaced in a future version of Tycho by the new org.eclipse.tycho:tycho-build extension.
[WARNING] You can simply change your .mvn/extensions.xml to reference the new extension right now:
[WARNING] <extension>
[WARNING]    <groupId>org.eclipse.tycho</groupId>
[WARNING]    <artifactId>tycho-build</artifactId>
[WARNING]    <version>2.7.1</version>
[WARNING] </extension>
[INFO] Scanning for projects...
[ERROR] Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST C:\Users\eraonel\git\m2e-core\m2e-maven-runtime\org.eclipse.m2e.archetype.common\META-INF\MANIFEST.MF: Manifest file not found -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST C:\Users\eraonel\git\m2e-core\m2e-maven-runtime\org.eclipse.m2e.archetype.common\META-INF\MANIFEST.MF: Manifest file not found
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:120)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST C:\Users\eraonel\git\m2e-core\m2e-maven-runtime\org.eclipse.m2e.archetype.common\META-INF\MANIFEST.MF: Manifest file not found
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifestFromDirectory (DefaultBundleReader.java:96)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.doLoadManifest (DefaultBundleReader.java:63)
    at org.eclipse.tycho.core.osgitools.DefaultBundleReader.loadManifest (DefaultBundleReader.java:54)
    at org.eclipse.tycho.core.osgitools.OsgiBundleProject.readArtifactKey (OsgiBundleProject.java:194)
    at org.eclipse.tycho.core.osgitools.OsgiBundleProject.setupProject (OsgiBundleProject.java:176)
    at org.eclipse.tycho.core.resolver.DefaultTychoResolver.setupProject (DefaultTychoResolver.java:89)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead (TychoMavenLifecycleParticipant.java:111)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:264)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:288)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:192)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

**Comment by mickaelistria** [comment]
Sorry, I'm not personally skilled enough in APT and m2e-apt stuff in general to be more helpful for user support. Maybe @fbricon can tell more about what can cause your issue.

About working on m2e, see documentation at https://github.com/eclipse-m2e/m2e-core/blob/master/CONTRIBUTING.md . Don't hesitate to ask further (ideally in GitHub discussions) if you're stuck setting up your development environment.

**Comment by mpet** [comment]
I manged to run:
[INFO]
[INFO] --- maven-antrun-plugin:3.0.0:run (generate-classpath-file) @ org.eclipse.m2e.maven.runtime.slf4j.simple ---
[INFO] Executing tasks
[INFO] Executed tasks
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] M2E - Maven runtime bundles 1.16.0-SNAPSHOT ........ SUCCESS [  3.703 s]
[INFO] M2E Maven Archetype Common 1.18.2-SNAPSHOT ......... SUCCESS [  3.728 s]
[INFO] M2E Embedded Maven Runtime (includes Incubating components) 1.18.4-SNAPSHOT SUCCESS [  5.651 s]
[INFO] M2E SLF4J-Simple Binding for Embedded Maven Runtime 1.18.1-SNAPSHOT SUCCESS [  0.639 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.886 s
[INFO] Finished at: 2022-04-20T09:47:00+02:00
[INFO] ------------------------------------------------------------------------

eraonel@SE-00002119 MINGW64 ~/git/m2e-core (master)

This was the command that I executed:

mvn generate-sources -f m2e-maven-runtime -Pgenerate-osgi-metadata -Dtycho.mode=maven

Then it says I should do:

mvn clean verify

Is it needed? And why?

**Comment by mickaelistria** [comment]
I see on some other threads you've made progress with apt stuff. Is this issue resolved or is it still relevant?

**Comment by mickaelistria** [comment]
No news since last question, so let's assume it's fixed. Thanks.

**Comment by brikikeks** [comment]
Version: 2022-06 (4.24.0)
Build id: 20220609-1112
    M2E - Maven Integration for Eclipse (includes Incubating components)	1.20.1.20220227-1319	
    
The m2e don't generate correct org.eclipse.jdt.apt.core.prefs after "check out as maven project".

**Comment by mickaelistria** [comment]
Please try m2e 2.0.0 from https://download.eclipse.org/technology/m2e/releases/latest/

**Comment by brikikeks** [comment]
> Please try m2e 2.0.0 from https://download.eclipse.org/technology/m2e/releases/latest/

With m2e 2.0.0 it works fine. Thanks!
