### ISSUE TITLE
Maven dependency classes opened by debugger from sources jar

### ISSUE THREAD

**Issue by sfussenegger** [eclipse-m2e/m2e-core#659]
See this screenshot:

![opened](https://user-images.githubusercontent.com/117516/165701529-6f878568-59df-4e60-bbaa-9141c1566534.png)

The first tab (with the "J" icon) is opened by debugger. Hovering over it shows the path as a tooltip and it's "~/.m2/repository/.../...-sources.jar/../....java".

The editor opened by "Open Type" (with the "010" icon) has the qualified class name as tooltip.

So for some reason debugger chooses to open the source like an external source file, hence the "missing Java project context".

Related to [#546203](https://bugs.eclipse.org/bugs/show_bug.cgi?id=546203).

**Comment by mickaelistria** [comment]
Can you please provide some minimal steps to reproduce the issue with latest Eclipse SDK and m2e snapshots?

**Comment by arjantijms** [comment]
I know it's but a minimal data point but with 2021-12 I had exactly this all the time. M2E would see source jars not as attachments to jar files without source, but as a fully individual jar containing external source.

With 2022-03 this issue disappeared for me.

**Comment by mickaelistria** [comment]
Thanks @arjantijms . Let's be optimist and hope your positive experience applies generally, and close.
