### ISSUE TITLE
Remove org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.suspend()/resume()

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#698]
I don't know for what this would be useful and it seems only be used in test. Also the javadoc is a bit unclear to me how it archives the "suspend", from the usage in the test-code it seems one probably would more call getThreadContext() and check if it is null to see if the queue needs to do more work?

@mickaelistria @HannesWell what do you think?

**Comment by mickaelistria** [comment]
No objection to remove internal code as long as it doesn't cause regressions.
