### ISSUE TITLE
Remove IMavenExecutionContext getExecutionContext();

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#713]
We can furhter remove the footprint of IMaven here

IMavenExecutionContext getExecutionContext(); is only called internally and redirects to a static method MavenExecutionContext.getThreadContext() anyways.

We could think about two choices:

remove it completely and use the `MavenExecutionContext.getThreadContext()` internally, or we could add a static method to `IMavenExecutionContext` (now we can have satic methods in interfaces) if we think it is usefull for others as well...

@mickaelistria WDYT?

**Comment by mickaelistria** [comment]
I think we should remove it as it doesn't seem to be much related to current IMaven instance and is more a static internal accessor. Some basic search on GitHub also didn't highlight any maintained code that seems to use this API (only occurrence is https://github.com/random-maven/scalor-maven-plugin/blob/d20e55b4b4bf6f5647811272a08254fa430ccfd4/src/main/scala/com/carrotgarden/maven/scalor/eclipse/Maven.scala )
