### ISSUE TITLE
Remove getConfiguredMojo/releaseConfiguredMojo

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#720]
Both methods seem to be (no longer?) being called.

Also the implementation could (if some project still require it) easily be replicated using the existing API:

```
@Override
  public <T> T getConfiguredMojo(MavenSession session, MojoExecution mojoExecution, Class<T> clazz)
      throws CoreException {
    try {
      MojoDescriptor mojoDescriptor = mojoExecution.getMojoDescriptor();
      // getPluginRealm creates plugin realm and populates pluginDescriptor.classRealm field
      lookup(BuildPluginManager.class).getPluginRealm(session, mojoDescriptor.getPluginDescriptor());
      return clazz.cast(lookup(MavenPluginManager.class).getConfiguredMojo(Mojo.class, session, mojoExecution));
    } catch(PluginManagerException | PluginConfigurationException | ClassCastException | PluginResolutionException ex) {
      throw new CoreException(Status.error(NLS.bind(Messages.MavenImpl_error_mojo, mojoExecution), ex));
    }
  }

  @Override
  public void releaseMojo(Object mojo, MojoExecution mojoExecution) throws CoreException {
    lookup(MavenPluginManager.class).releaseMojo(mojo, mojoExecution);
  }
```

**Comment by mickaelistria** [comment]
+1

**Comment by fbricon** [comment]
-1 it's being used by 3rd party plugins: https://github.com/search?q=maven.getConfiguredMojo&type=Code, removing API without a deprecating cycle is bad for the ecosystem

**Comment by laeubi** [comment]
Anyone ever heard of https://github.com/svn2github/jamon ? what does it do? Seems it has not got any updates than nearly 10 years, probably dead project and won't notice any deprecation anyways.

https://github.com/charles-marques/dataset-375 seems to be at least active two years ago, so there might be a chance to getting updates.

for the https://github.com/tesla/m2eclipse-mavenarchiver I have opened
- #721

**Comment by mickaelistria** [comment]
I did miss those 2 matches when doing my search. Not sure whether I failed at reading results correctly or whether I used a different (bad) search request.
Anyway, now we're proven some extensions use it, -1 for a removal. But as m2e itself doesn't use it, I think it's OK to `@Deprecated(forRemoval = true)` it and document it with the provided snippet to replace it.

**Comment by laeubi** [comment]
Then lets keep this 'as-is' and wait for the desision about #721 I think if there is really a use-case inside m2e that reference this we might even considder to keep this permanent.
