### ISSUE TITLE
[regression] Autocompletion for directory/file based properties no longer working in the pom.xml editor

### ISSUE THREAD

**Issue by fbricon** [eclipse-m2e/m2e-core#723]
This feature was introduced in m2e 1.7, see https://www.eclipse.org/m2e/documentation/release-notes-17.html#autocompletion-for-directory-file-based-properties-in-the-pom-xml-editor

![folder-content-assist](https://user-images.githubusercontent.com/148698/169037505-ec2822a6-ce62-4fdc-8d66-9b7b802f906a.gif)

> It applies on:
> * Certain pom model elements (build/{directory, sourceDirectory, scriptSourceDirectory, testSourceDirectory, outputDirectory, testOutputDirectory, filters/filter});
> * Plugin configuration elements which allow files (either File type or name ends with ‘directory’);
> * Modules.

AFAICT directory completion only works for modules now.

**Comment by mickaelistria** [comment]
I think this one is fixed with latest lemminx-maven included. @fbricon please give it a try and either reopen or create more specific issue if this doesn't work for you.
cc @vrubezhny

**Comment by fbricon** [comment]
yes it works. Thanks @vrubezhny @mickaelistria
