### ISSUE TITLE
Cut dependency to maven archetype runtime from m2e.core

### ISSUE THREAD

**Issue by snjeza** [eclipse-m2e/m2e-core#731]
Related Eclipse bug - https://bugs.eclipse.org/bugs/show_bug.cgi?id=517822

> When embedding m2e-core to jdt.ls, we bring in the maven archetype runtime as dependency, which could be avoided if m2e-core were refactored to not depend on that runtime directly.
> We should extract all archetype related operations into a separate plugin.

**Comment by laeubi** [comment]
This seems a requirement for the Archetype migration. I have checked this and it seems at least we can reduce some dependencies as a first step.

**Comment by laeubi** [comment]
The m2e-core ui has now no more dependency on the maven archetype.

The fix for this issue was gently sponsored by [Faktor Zehn GmbH](https://www.faktorzehn.com).

**Comment by HannesWell** [comment]
Thank you Christoph!
Just a link to the corresponding PRs #758, #762 and #763.
