### ISSUE TITLE
Use latest maven-4.0.0.xsd to validate pom.xml

### ISSUE THREAD

**Issue by brbog** [eclipse-m2e/m2e-core#747]
At the moment following snippets are considered faulty inside a pom.xml:
```
	<distributionManagement>
		<site child.site.url.inherit.append.path="false">
			<id>...</id>
			<name>...</name>
			<url>...</url>
		</site>
	</distributionManagement>
```
```
	<scm child.scm.connection.inherit.append.path="false" child.scm.developerConnection.inherit.append.path="false">
		<connection>...</connection>
		<developerConnection>...</developerConnection>
	</scm>
```
This is because the xsd used to validate the pom.xml is cached instead of fetched from its internet location and the cached version is outdated. These attributes were additions to later Maven versions.

You can get the latest xsd from Maven (http://maven.apache.org/xsd/maven-4.0.0.xsd). I think the fix is replacing content of ``m2e-core/org.eclipse.m2e.model.edit/src-xsd/org/eclipse/m2e/model/pom/pom.xsd`` with that of the latest ``maven-4.0.0.xsd``, but I can be wrong.

**Comment by mickaelistria** [comment]
I couldn't reproduce it locally (that doesn't invalidate a caching issue). Can you provide steps to reproduce the issue with a fresh Eclipse IDE and installing m2e from https://download.eclipse.org/technology/m2e/snapshots/latest ?

**Comment by HannesWell** [comment]
> You can get the latest xsd from Maven (http://maven.apache.org/xsd/maven-4.0.0.xsd). I think the fix is replacing content of `m2e-core/org.eclipse.m2e.model.edit/src-xsd/org/eclipse/m2e/model/pom/pom.xsd` with that of the latest `maven-4.0.0.xsd`, but I can be wrong.

That XSD indeed can be updated. But it is not only about updating the xsd, the code generated from it also has to be re-generated (and the project itself can be cleaned up and its documentation can be improved). I started some work on this a while ago but did not complete it yet (I'm not sure about the reasons), but I can have a look at that again soon.

But with Mickaels comment I'm not sure if this is the actual root of your problem.

**Comment by brbog** [comment]
Reproduced using following steps:
1. download eclipse-jee-2022-03-R-linux-gtk-x86_64: [Eclipse IDE for Enterprise Java and Web Developers](https://www.eclipse.org/downloads/packages/release/2022-03/r/eclipse-ide-enterprise-java-and-web-developers) - Linux [x86_64](https://www.eclipse.org/downloads/download.php?file=/technology/epp/downloads/release/2022-03/R/eclipse-jee-2022-03-R-linux-gtk-x86_64.tar.gz)
2. installing m2e from https://download.eclipse.org/technology/m2e/snapshots/latest => had to choose some option to update existing plugins to be compatible.
3. import "Existing Maven project", I made a very minimal project: https://github.com/brbog/minimal-main/tree/issue-Eclipse-maven-4.0.0.xsd-validation (clone repo + checkout this branch)

Eclipse behaves a little different under Linux (Debian stable 11.3) than under Windows, so maybe that has something to do with it as well?

**Comment by mickaelistria** [comment]
Can you please try opening the Problems view and copying the error you mention? It's still not clear to me what they're sourced form, and some details of the specific project (eg type) will help.

**Comment by brbog** [comment]
Problems view:
Description	Resource	Path	Location	Type
cvc-complex-type.3.2.2: Attribute 'child.scm.connection.inherit.append.path' is not allowed to appear in element 'scm'.	pom.xml	/xxx	line 16	Language Servers
cvc-complex-type.3.2.2: Attribute 'child.scm.developerConnection.inherit.append.path' is not allowed to appear in element 'scm'.	pom.xml	/xxx	line 16	Language Servers

Some details of the specific project (eg type):
I'm importing an "existing Maven project" and it figures out that it is a Java project as it should be. The Project Natures automatically set are "Java" and "Maven Nature".

Since it doesn't seem to be specifically Linux or Windows related, maybe it is distribution related? I use [Eclipse IDE for Enterprise Java and Web Developers](https://www.eclipse.org/downloads/packages/release/2022-03/r/eclipse-ide-enterprise-java-and-web-developers), and not the default Eclipse download.

If I can do anything to help, just let me know. I thought it would have been easier to reproduce.

**Comment by brbog** [comment]
Maybe a helpful pointer. If you try to Ctrl+click on the xsd inside:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
```
you get a dropdown asking whether you want to open the xsd from a local file or open the url in a browser.

When you open the url in a browser, then it opens the latest correct xsd. This made me believe that the validation actually uses the local file to avoid downloading from the internet all the time. I tried fixing this problem by overwriting the xsd in the local location and that actually worked (no validation errors anymore), but it is a temporary fix and gave me other problems later on I think. The local file used to be in a location like: `eclipse/configuration/org.eclipse.osgi/617/0/.cp/xsd/maven-v4_0_0.xsd`, but now in the latest install it's `eclipse/configuration/org.eclipse.osgi/958/0/.cp/xsd/maven-v4_0_0.xsd`.

**Comment by brbog** [comment]
Updated to https://download.eclipse.org/technology/m2e/snapshots/latest/ and the validation errors are gone.

Thanks for the experience!
