### ISSUE TITLE
${project.build.outputDirectory} not available to maven-plugins when running inside m2e?

### ISSUE THREAD

**Issue by tomsontom** [eclipse-m2e/m2e-core#803]
As I did not get a response I think the worst that can happen is that this is a none issue

### Discussed in https://github.com/eclipse-m2e/m2e-core/discussions/790

<div type='discussions-op-text'>

<sup>Originally posted by **tomsontom** June 17, 2022</sup>
Before fileing a ticket I wanted to make sure that this is really a bug (I haven't written a maven-plugin before). In my Maven-Mojo i have:

```java
@Mojo(name = "generate-scr", defaultPhase = LifecyclePhase.GENERATE_SOURCES, requiresDependencyResolution = ResolutionScope.COMPILE_PLUS_RUNTIME, threadSafe = true)
public class BaesoSCRGenerateMojo extends AbstractMojo {
...
    @Parameter(property="project", required=true)
    protected MavenProject project;

    @Parameter(defaultValue = "${project.build.outputDirectory}", readonly = true)
    File outputDir;

 .....
```
In my `execute` I generate additional files into it. This works fine when I run the build on the command line. So far so good.

I then tried to integrate myself into the eclipse lifecycle by providing a `lifecycle-mapping-metadata.xml` but I run into errors because because it looks like the above value is `null` when m2e runs the plugin. My work around currently is to use `project.getBuild().getOutputDirectory()` instead but I wonder if it is expected that this value is null, I discovered a bug or I'm doing something I'm not supposed to do.</div>

**Comment by HannesWell** [comment]
Just for clearification, the value of the `outputDir` is null?
@laeubi you have done a lot of work with maven executions in the past. Can you say if this a bug or intended?
Or could it be that the lifecycle-mapping-metadata are not set up correctly?

@tomsontom you could also debug the execution of your plug-in? You can use the Oomph setup for M2E to set up a development environment and then launch the predefined `Eclipse-M2E-IDE` launch configuration and create a Maven project that uses your plug-in.

**Comment by tomsontom** [comment]
Yes outputDir is null.

**Comment by laeubi** [comment]
> Can you say if this a bug or intended?

Most probably a bug, I can't think of that one want this behavior, https://github.com/eclipse-m2e/m2e-core/issues/622 might be the same root cause.

**Comment by laeubi** [comment]
@tomsontom by the way does the name "SCRGenerateMojo" indicate you want to generate DS component xmls? Just wanted to let you know that Tycho already can handle this now (as well as bnd) so just in case...

**Comment by laeubi** [comment]
> Yes outputDir is null.

What about `protected MavenProject project;`? Any difference if you make the file field also `protected`?

**Comment by tomsontom** [comment]
> @tomsontom by the way does the name "SCRGenerateMojo" indicate you want to generate DS component xmls? Just wanted to let you know that Tycho already can handle this now (as well as bnd) so just in case...

well yes but in a bit different way (the xml part is already handled by bnd) what I generate is java code who is used by a custom service registry who allows me to use DS-Services in a default java-env.

**Comment by laeubi** [comment]
YOu might want to take a look at https://sling.apache.org/documentation/development/osgi-mock.html#implemented-mock-features-1 even tough it says it is a mock framework it support creation of DS components in standard java context and I already use this to emulate OSGi in some Tycho places :-)

Probably it would even be good to have such a OSGi-Polyfill as a generic project.

**Comment by mickaelistria** [comment]
I second @laeubi 's question from https://github.com/eclipse-m2e/m2e-core/issues/803#issuecomment-1161262051 . It could be that the context is not fully populated by m2e. At least if project is set, we know we can remediate it.
Is anyone aware of the code in Maven that generate all those properties from context/session? m2e might just need to call it before invoking the mojo.

**Comment by laeubi** [comment]
@mickaelistria this is most probably a `org.codehaus.plexus.interpolation.RegexBasedInterpolator` using a `org.codehaus.plexus.interpolation.ObjectBasedValueSource` thats why I wonder if the project is injected, then it should work for the other field as well:

`${project.build.outputDirectory} --> project.getBuild().getOutputDirectory()`

so maybe the setup of the mojo execution is not complete here.

But according to

> My work around currently is to use `project.getBuild().getOutputDirectory()`

it *seems* the project is actually injected but I just wanted to make that sure.

**Comment by tomsontom** [comment]
> YOu might want to take a look at https://sling.apache.org/documentation/development/osgi-mock.html#implemented-mock-features-1 even tough it says it is a mock framework it support creation of DS components in standard java context and I already use this to emulate OSGi in some Tycho places :-)
> 

well my solution works even in a JPMS and AOT world - if one resides to reflection you have to open your in module in a JPMS world for reflection and in an AOT world you need to provide the information to Graal so that it is not missed in the closed world analysis both possible but not the nicest things but we get off-topic. 

I'll see what happens if I make the file protected but I doubt that would change anything because from a Injection point-of-view this should not matter you anyways have to make the field accessible. Even if it would resolve my problem I don't think this can be a valid option as it is prefectly ok to declare those field `private` in standard maven.

**Comment by tomsontom** [comment]
So I've now tried to reproduce this again - and today everything works like a charme no matter if I use `private` or `protected` it just works. So I'm closing this one as it looks like it was something in my setup causing that problem.
