### ISSUE TITLE
Discovery catalog for Eclipse 2019-09 points to incorrect URL

### ISSUE THREAD

**Issue by martin-neuhaeusser** [eclipse-m2e/m2e-core#826]
Eclipse 2019-09 (Build id: 20190917-1200) fails to update the catalog under `Windows` -> `Preferences` -> `Maven` -> `Discovery` -> `OpenCatalog`. 
The (hard coded?) URL that it is trying to use is https://download.eclipse.org/technology/m2e/discovery/directory-1.12.xml. That XML file contains a link to https://dl.bintray.com/m2e/discovery-catalog/org.eclipse.m2e.discovery.oss-catalog-1.13.jar, which is dead and cannot be received. Hence Eclipse complains that it "Failed to discover all connectors" (it actually discovers none).
I saw that those URLs have been migrated to GitHub links (like https://github.com/takari/m2e-discovery-catalog/raw/gh-pages/catalogs/org.eclipse.m2e.discovery.oss-catalog-1.14.jar) in later versions of Eclipse.

Is there any fix available to get that working in Eclipse 2019-09? I am dependent on it for compiling a huge older code base that has dependencies forcing me to use the old version of Eclipse.

Thanks a lot for any hints.

**Comment by martin-neuhaeusser** [comment]
Thanks for the explanation. Is there any way to update the m2e release in Eclipse 2019-09?
Or does that force me to use a newer version of Eclipse, effectively breaking the project I am working on?

**Comment by mickaelistria** [comment]
> Is there any way to update the m2e release in Eclipse 2019-09?

I don't know. Try and see by yourself ;)

> Or does that force me to use a newer version of Eclipse, effectively breaking the project I am working on?

How is it breaking?

**Comment by martin-neuhaeusser** [comment]
I have an outdated research prototype of a verification tool \url(Ultimate Automizer)[https://github.com/ultimate-pa/ultimate] which heavily relies on the Tycho connector, Java 1.8 and Eclipse 2019-19 to build. Following the build instructions from 2019 requires to install that connector via the m2e catalog, which has gone.

**Comment by martin-neuhaeusser** [comment]
@fbricon Thank you so much! 
Your suggestion indeed helped. I only had to use directory-1.14.xml instead of directory-1.13.xml and was able to install the Tycho Configurator.
