### ISSUE TITLE
Ignore lifecycle configuration dialog too small

### ISSUE THREAD

**Issue by kjsmita6** [eclipse-m2e/m2e-core#854]
When you select the quick-fix for "Plugin execution not covered...", and select "Mark goal as ignored in pom.xml, the popup looks like this:
![Screen Shot 2022-07-12 at 2 28 00 PM](https://user-images.githubusercontent.com/9405706/178567706-97c59b35-f34c-4cf0-838d-5b6537dfef58.png)

And the location to ignore isn't visible at all. It can still be selected but I could not determine any way to make this dialog bigger to make the text visible.

**Comment by mickaelistria** [comment]
Would you be willing to submit a patch the fixes that?

**Comment by kjsmita6** [comment]
![5ab7d599d9a0b2dc3880731d302ad319](https://user-images.githubusercontent.com/9405706/179382196-2ccfc18f-3c95-4add-a938-0778d7fcf9d4.png)
Was going to work on this issue this weekend on my Windows PC but funnily enough, the issue doesn't happen. So I guess I'll do it next week when I have my work Mac.

Or it's just something that was fixed already and not released yet.

**Comment by kjsmita6** [comment]
Closed by #860.
