### ISSUE TITLE
POM-Editor (Lemminx based): Source/Comment-Options from legacy WTP based editor missing

### ISSUE THREAD

**Issue by caroso-de** [eclipse-m2e/m2e-core#856]
I hope this isn't a duplicate or hasn't been discussed earlier.

With the new lemminx-based editor, i sorely miss the line- and block editing options of the previous editor (Crtrl-Shift-C). Is this by design or will this feature be available again in the future?

Thanks!

**Comment by mickaelistria** [comment]
Please install latest snapshots for TM4E which have it fixed.

**Comment by caroso-de** [comment]
Thanks!
