### ISSUE TITLE
pom.xml editor marks "combine.self" as an error

### ISSUE THREAD

**Issue by oboguev** [eclipse-m2e/m2e-core#857]
When pom.xml contains

```
<plugin>
  <configuration combine.self="override">

```
M2E editor displays error message

`cvc-complex-type.3.2.2: Attribute 'combine.self' is not allowed to appear in element 'configuration'`

M2E POM schema definition needs to be updates with current Maven schema definition.

Versions:
Eclipse 2022-03
M2E - Maven Integration for Eclipse (includes Incubating components) 1.20.1.20220227-1319
M2E - POM Editor using LemMinX language server (includes Incubating components) 1.18.4.20220127-1634

**Comment by akurtakov** [comment]
@oboguev It's best to report this to maven itself and ask them to publish new version of the xsd with such additions.
