### ISSUE TITLE
How do BND instructions work in the .target file?

### ISSUE THREAD

**Issue by LorenzoBettini** [eclipse-m2e/m2e-core#862]
Hi
Maybe I'm doing something wrong but in the `.target` file I specified this entry (i.e., I removed the `wrapped.` prefix from `Bundle-SymbolicName`; I've used the Target editor to get this result):

```xml
		<location includeDependencyDepth="infinite" includeDependencyScopes="compile,runtime" includeSource="true" missingManifest="generate" type="Maven">
			<dependencies>
				<dependency>
					<groupId>org.pitest</groupId>
					<artifactId>pitest-command-line</artifactId>
					<version>1.6.8</version>
					<type>jar</type>
				</dependency>
			</dependencies>
			<instructions><![CDATA[
Bundle-Name:           Bundle derived from maven artifact ${mvnGroupId}:${mvnArtifactId}:${mvnVersion}
version:               ${version_cleanup;${mvnVersion}}
Bundle-SymbolicName:   ${mvnGroupId}.${mvnArtifactId}
Bundle-Version:        ${version}
Import-Package:        *;resolution:=optional
Export-Package:        *;version="${version}";-noimport:=true
DynamicImport-Package: *
]]></instructions>
		</location>
```

so I would expect to find `org.pitest.pitest-command-line` in the "Target Platform State" after resolution. Instead I still get `wrapped.org.pitest.pitest-command-line`. I can live with that, but isn't the above specification correct? Or am I missing something?

thanks in advance

**Comment by laeubi** [comment]
First, you might want to ask the project to add OSGi data in the first place, I'm currently preparing a template fo this, so you might want to help with that see https://github.com/laeubi/osgi-issue-templates/pull/3

And just to make sure, have you reloaded/set your target after the change and are you using the latest m2e release?

**Comment by LorenzoBettini** [comment]
@laeubi thanks for the fast response!

> First, you might want to ask the project to add OSGi data in the first place, I'm currently preparing a template fo this, so you might want to help with that see [laeubi/osgi-issue-templates#3](https://github.com/laeubi/osgi-issue-templates/pull/3)
> 

OK, I'll let them know

> And just to make sure, have you reloaded/set your target after the change and are you using the latest m2e release?

I'm using the one that comes with Eclipse 2022-06:

```
  M2E - Maven Integration for Eclipse (includes Incubating components)	1.20.1.20220227-1319	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e
```

**Comment by LorenzoBettini** [comment]
I don't have the same view, so I guess it's not the latest and greatest version:

<img width="501" alt="Screenshot 2022-07-28 at 12 29 52" src="https://user-images.githubusercontent.com/1202254/181484667-77a5a3d7-4b26-4ef5-b9e9-1e8eaf0d441f.png">

However, as I said, I can live with wrapped names :)

**Comment by laeubi** [comment]
You need to check "Show locations content" in the bottom of the target Locations Group!

**Comment by LorenzoBettini** [comment]
Ah OK!
Sorry I temporarily gave up on that: the workspace was so ruined that I used to have a mixture of wrapped and unwrapped... even stopping Eclipse and removing the pde.core directory in the workspace and reloading the TP didn't seem to help... I had a random mixture of wrapped and unwrapped... I decided to go for wrapped now, since at least that's reproducible (I had to remove the workspace entirely).
As you suggested, I guess here PDE is going crazy...

**Comment by Kummallinen** [comment]
I've found you need to remove the old artefacts from the local maven repo when changing the BND instructions, otherwise it still uses the old version.

**Comment by LorenzoBettini** [comment]
I had the same feeling as well... however, that's far from ideal...

**Comment by laeubi** [comment]
If any one can give steps to reproduce please let me know (or even better provide a PR to fix that)

**Comment by LorenzoBettini** [comment]
I thought you had already reproduced the problem yourself and opened another issue

**Comment by laeubi** [comment]
I tried with m2e 2.x and didn't see the issue there...

**Comment by LorenzoBettini** [comment]
Then I guess you can close this

**Comment by HannesWell** [comment]
> I've found you need to remove the old artefacts from the local maven repo when changing the BND instructions, otherwise it still uses the old version.

There was indeed a bug in the detection if the instructions changed, but this was fixed with https://github.com/eclipse-m2e/m2e-core/pull/1387.
You can try the latest snapshots here: https://download.eclipse.org/technology/m2e/snapshots/latest/
