### ISSUE TITLE
Using BND instructions is broken with more than one artifact

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#863]
I just tried this out and it seems that the instruction is not propagated correctly to all childs but only some:
![image](https://user-images.githubusercontent.com/1331477/181481264-de2eed57-2ee1-4c6e-b349-2971f66478d9.png)
 this seems to be a bug in m2e.

_Originally posted by @laeubi in https://github.com/eclipse-m2e/m2e-core/issues/862#issuecomment-1197945555_

**Comment by laeubi** [comment]
It seems this do not occur anymore on 2.0

**Comment by HannesWell** [comment]
Cannot reproduce this too.
