### ISSUE TITLE
Support exclusions  in target files for PDE

### ISSUE THREAD

**Issue by vogella** [eclipse-m2e/m2e-core#877]
Currently the M2E / PDE integration does not support exclusions.

For example, you cannot exclude the slf4j-api dependencies from the dependencies of a library and include your own.

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?pde version="3.8"?>
<target name="test">
	<locations>
		<location includeDependencyDepth="infinite" includeDependencyScopes="compile" includeSource="true" missingManifest="generate" type="Maven">
			<dependencies>
				<dependency>
					<groupId>ch.qos.logback</groupId>
					<artifactId>logback-classic</artifactId>
					<version>1.2.11</version>
					<type>jar</type>
					
					<exclusions>
			        <exclusion>
			            <groupId>org.slf4j</groupId>
			            <artifactId>slf4j-api</artifactId>
			        </exclusion>
    			</exclusions>
				</dependency>
				
            	<dependency>
			    <groupId>org.slf4j</groupId>
			    <artifactId>slf4j-api</artifactId>
			    <version>1.7.36</version>
			</dependency>
			</dependencies>
		</location>
	</locations>
</target>
````

Expected: slf4j-api from qos.logback should NOT be included into the target platform.

Actual: slf4j-api from qos.logback  is included into the target platform

![image](https://user-images.githubusercontent.com/139910/185925186-59f01978-364f-48ae-882e-226bc0dcbc32.png)

**Comment by laeubi** [comment]
You can select the dependency and press the "Exclude" button.

**Comment by vogella** [comment]
Thanks @laeubi, would be nice to support here also the standard Maven exclusion. IIRC you and @HannesWell had the target to use as much Maven standards as possible. https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

**Comment by laeubi** [comment]
Yes see https://github.com/eclipse-m2e/m2e-core/issues/286 but no one yet cared enough to implement this :-)

If this is crucial to someones business and likes to speed up the development in that area a [sponsoring](https://github.com/sponsors/laeubi?frequency=one-time) would allow me to assign more time-slots particular issue.

**Comment by vogella** [comment]
Dup of #286
