### ISSUE TITLE
Both 'org.eclipse.cbi.p2repo.p2.maven' and 'org.eclipse.m2e.model.edit' register a package for 'http://maven.apache.org/POM/4.0.0'

### ISSUE THREAD

**Issue by jukzi** [eclipse-m2e/m2e-core#881]
That error message appears when starting an OOmphed eclipse workspace.
was already reported in 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=527256

**Comment by mickaelistria** [comment]
There is no way m2e can work without registering this package, and I think the m2e model is better maintained (and at least as likely to be maintained because m2e is a more active project in term of users and maintainers).
So m2e cannot expect anything good by removing this model namespace.

**Comment by ewillink** [comment]
m2e may well require it, but if the use is solely from an edit plugin, surely a programmatic (local) declaration is adequate. No need to inflict the conflicting global registration on everyone.

In the unlikely event that a global registration is necessary m2e and cbi should negotiate to determine a single common point of registration.
