### ISSUE TITLE
Can support m2e connector m2e-buildhelper like m2e-apt?

### ISSUE THREAD

**Issue by zollum** [eclipse-m2e/m2e-core#885]
after upgrade to eclipse 2022-09 with _M2E - Maven Integration for Eclipse 2.0.1.20220805-1816_

the m2e connector m2e-buildhelper is incompatible any more, for m2e has bumped it's version to 2.0. 

m2e-buildhelper hasn't been maintained for a long time, so m2e can include m2e-buildhelper in source like apt? 

Thanks.

details:

```
Cannot complete the install because of a conflicting dependency.
  Software being installed: m2e connector for build-helper-maven-plugin 0.15.0.201405280027 (org.sonatype.m2e.buildhelper.feature.feature.group 0.15.0.201405280027)
  Software currently installed: M2E - Maven Integration for Eclipse 2.0.1.20220805-1816 (org.eclipse.m2e.feature.feature.group 2.0.1.20220805-1816)
  Only one of the following can be installed at once: 
    M2E JDT Integration 1.18.3.20211112-0847 (org.eclipse.m2e.jdt 1.18.3.20211112-0847)
    M2E JDT Integration 2.0.0.20220706-1958 (org.eclipse.m2e.jdt 2.0.0.20220706-1958)
  Cannot satisfy dependency:
    From: M2E - Maven Integration for Eclipse 2.0.1.20220805-1816 (org.eclipse.m2e.feature.feature.group 2.0.1.20220805-1816)
    To: org.eclipse.equinox.p2.iu; org.eclipse.m2e.jdt [2.0.0.20220706-1958,2.0.0.20220706-1958]
  Cannot satisfy dependency:
    From: m2e connector for build-helper-maven-plugin 0.15.0.201405280027 (org.sonatype.m2e.buildhelper 0.15.0.201405280027)
    To: osgi.bundle; org.eclipse.m2e.jdt [1.1.0,2.0.0)
  Cannot satisfy dependency:
    From: m2e connector for build-helper-maven-plugin 0.15.0.201405280027 (org.sonatype.m2e.buildhelper.feature.feature.group 0.15.0.201405280027)
    To: org.eclipse.equinox.p2.iu; org.sonatype.m2e.buildhelper [0.15.0.201405280027,0.15.0.201405280027]c
```

m2e-buildhelper installed from https://download.jboss.org/jbosstools/updates/requirements/m2e-buildhelper/

**Comment by laeubi** [comment]
If it is open source just propose a patch and ask for a release. If not, you need to contact the software suppliers support team.

Depending on what m2e-buildhelper there might be alternatives, or if it is important enough and we get IP clearance might also be an option for m2e to adopt the connector. Still all this would require some help from the community.

**Comment by zollum** [comment]
Thanks for your reply, i'll try to submit a patch, let me deep into eclipse plugin first.

**Comment by zollum** [comment]
after upgrade build-helper-maven-plugin to 3.3.0 with lifecycle-mapping-metadata.xml bounded, the connector not needed

**Comment by laeubi** [comment]
@zollum thanks for the feedback, can we remove the connector from the catalog @fbricon ?

**Comment by mickaelistria** [comment]
@zollum Thanks for sharing this happy end!
