### ISSUE TITLE
Latest M2E release requires not-yet-released (4.25 RC1) Eclipse version

### ISSUE THREAD

**Issue by guw** [eclipse-m2e/m2e-core#887]
We are using the M2E `/latest` update site for consuming M2E. With the *2.0.2* release this broke our whole installation process for a few thousand users because of:

```
Cannot complete the install because one or more required items could not be found.                                                                                                                     
        Software being installed: M2E - Maven Integration for Eclipse 2.0.2.20220828-2046 (org.eclipse.m2e.feature.feature.group 2.0.2.20220828-2046)                                                  
        Missing requirement: M2E Launching 2.0.1.20220828-2046 (org.eclipse.m2e.launching 2.0.1.20220828-2046) requires 'osgi.bundle; org.eclipse.ui.console [3.11.300,4.0.0)' but it could not        
```

It would be great if M2E can align with the Eclipse releases and **only release something** which depends on **released** artifacts. Today there is not chance to consume `org.eclipse.ui.console [3.11.300,4.0.0)` from any official release repository.

FWIW, every *mature* Eclipse project does follow at least some good practice to also guarantee backwards compatibility with Eclipse N-1 or N-2 versions. I do get the desire to stay on top of latest things but this needs a better policy and process (Eg., like a "beta" channel).

**Comment by laeubi** [comment]
> FWIW, every mature Eclipse project does follow at least some good practice to also guarantee backwards compatibility with Eclipse N-1 or N-2 versions. I do get the desire to stay on top of latest things but this needs a better policy and process (Eg., like a "beta" channel).

You can always install / use an older version see:
https://download.eclipse.org/technology/m2e/releases/

beside that there are no "guarantees" at all, only best effort based  on contributions, so if you like to ensure backward compatibility feel free to contribute patches towards that goal.

**Comment by guw** [comment]
@laeubi A release of an Eclipse project depending on non-release bits of another Eclipse project is not in alignment with the Eclipse Development and IP Process. I'll follow up on the M2E and PMC mailing list.

**Comment by laeubi** [comment]
> Eclipse project depending on non-release bits of another Eclipse project is not in alignment with the Eclipse Development and IP Process.

Well m2e do not strictly **depend** on something "not released", it only **requires** a higher version of the upcoming release, to enable features specific to the  2.0.2 release ...

> I'll follow up on the M2E and PMC mailing list.

@guw feel free to do so, writing that mail and waiting for a response will just most likely take **much more time** than simply using https://download.eclipse.org/technology/m2e/releases/2.0.1 what will fix your issue **immediately** ...

**Comment by mickaelistria** [comment]
While I support this discussion and understand the issue and possible workaround; I'm curious as to what can be a concrete resolution plan for this issue? Would you like `latest` to point to `2.0.1` until Platform 4.25 is released?

**Comment by guw** [comment]
To be consistent with platform, I'd recommend something like `/I-builds` for integration builds and `/latests` really being something that aligns with `/SDK/latest` (which doesn't exist but that's sort of the idea).

**Comment by HannesWell** [comment]
We have some sort of chicken-egg problem here, since we should not use snapshots in SimRel but wanted to provide support for the new colored console, that is not yet released. Alternativly we would have to wait for one full release cycle to make that available in SimRel.

It is a general question how to handle that best, with M2E's process (only releases and snapshots/I-builds). The current one ist indeed suboptimal.

> Would you like `latest` to point to `2.0.1` until Platform 4.25 is released?

That seems to be a good solution for me, that should fit all needs. 
We could use a simple composite repo that points to 2.0.1 or just again copy that repos content.

**Comment by C4J** [comment]
> @laeubi A release of an Eclipse project depending on non-release bits of another Eclipse project is not in alignment with the Eclipse Development and IP Process. I'll follow up on the M2E and PMC mailing list.

I have to agree - I spent a lot of time trying to figure out what was wrong until I came across this forum post.

**Comment by HannesWell** [comment]
To fix this issue now I will just replace the latest repo with the content of the 2.0.1 release repo.
We can then later think about streamlining the latest repo using a composite.

**Comment by mickaelistria** [comment]
We'll need a new m2e ASAP shortly for #867, so don't bother too much right now as the content of latest repo is likely to be overridden later today.

**Comment by guw** [comment]
I won't have time to verify it today. But I am not blocked as I did use the workaround of pointing to an older repo. I'll re-enable `/latest` early next week.

**Comment by mickaelistria** [comment]
>  use the new one only in SimRel?

That is the critical goal.

> Do you intend to make the new release the 'latest'? 

The promote script will do it anyway. Then we'll need to restore latest to 2.0.1; but I'd be fine doing nothing as well and sticking to latest being 2.0.3 for a few more days until it's not an issue.

**Comment by HannesWell** [comment]
> I won't have time to verify it today. But I am not blocked as I did use the workaround of pointing to an older repo. I'll re-enable `/latest` early next week. Thanks for checking.

OK. You're welcome and thanks for bringing that to our intention.

> > Do you intend to make the new release the 'latest'?
> 
> The promote script will do it anyway. Then we'll need to restore latest to 2.0.1; but I'd be fine doing nothing as well and sticking to latest being 2.0.3 for a few more days until it's not an issue.

That's right. You can just re-run the `batch infra stuff` job after the 2.0.3 release is done.
I think we should not again disturb our users again (btw. I'm also glad to know there is a great user base, although it was through bad circumstances). Once 4.25 is released I can just run `batch infra stuff` replacing latest with 2.0.3.

**Comment by HannesWell** [comment]
I think we can close this issue now.
As soon as Eclipse 4.25 is released on Wednesday I will update the [m2e/releases/latest](https://download.eclipse.org/technology/m2e/releases/latest/) to be equal to [m2e/releases/2.0.4](https://download.eclipse.org/technology/m2e/releases/2.0.4/).

**Comment by HannesWell** [comment]
`m2e/releases/latest` is now equals to `m2e/releases/2.0.5`
