### ISSUE TITLE
Support maven-mvnd

### ISSUE THREAD

**Issue by wsq93** [eclipse-m2e/m2e-core#897]
### Expected Behavior

maven-mvnd replaces maven

### Link

https://github.com/spring-projects/sts4/issues/835

https://github.com/apache/maven-mvnd

**Comment by HannesWell** [comment]
Can you please elaborate more how you expect `mvnd` to work with M2E?
M2E already has a complete Maven-runtime embedded and builds the projects in the workspace of your IDE incrementally. I have not yet worked with mvnd but it looks like M2E already works very similar.

**Comment by wsq93** [comment]
First, Installations supports two constituencies, one is maven and the other is maven-mvnd. It can be considered that only one can be enabled. 
![图片](https://user-images.githubusercontent.com/44887680/189590983-688041eb-6ec3-4966-93df-7632133e902e.png)

Second, this drop-down list supports choose them.
![图片](https://user-images.githubusercontent.com/44887680/189591985-47f10554-18d2-4269-959c-eb5c1d61cf5e.png)


When maven-mvnd is selected, the instruction `mvn` is replaced with `mvnd`.

That's all I could think of.

**Comment by wsq93** [comment]
I have a project that takes 43S to build using the `mvn clean package` instruction, but 13S to build using the `mvnd clean package` instruction. However, it cannot be used in IDE.

**Comment by mickaelistria** [comment]
I imagine m2e could allow path to binary (eg `mvnd`) additionally to path to folder in the Maven/Installations page. A contribution towards that would be welcome as a pull request!

**Comment by wsq93** [comment]
Sorry, I forgot that maven-mvnd has a configuration file directory. Although there is only one line of configuration in the file `conf/mvnd.properties`, It seems that the previous idea is not suitable.

Maybe it's better to create a menu item independently.

**Comment by wsq93** [comment]
Because maven has the same instructions as maven mvnd, I hope Maven will support the original ecology after upgrading. However, these are two projects.

And it is said that mvnd is not suitable for single module projects.

**Comment by wsq93** [comment]
> One could already facilitate the "External Tools" for that. Using it inside m2e would work for simple cases (e.g. Run As > ...) where it is only used as a convenient wrapper to a command line call, things like setting a JRE would obviously not work,
> 
> Because of that, I think it would be much more useful to have an own plugin (that might be hosted here) that supports a `mvnd` specific run type and appropriate UI representation.

The `mvnd` instruction can be executed in directory `${maven-mvnd}/bin`, and the `mvn` instruction can be executed in directory `${maven-mvnd}/mvn/bin`

**Comment by laeubi** [comment]
Still m22 does not execute an "executable" or "command" but fire a JVM process with a classpath and a main class.

While the result looks the same, it is still a different topic.

**Comment by wsq93** [comment]
Just now I tried to run the `mvnd` command again in the terminal of the IDE, and this time it was executed successfully. 

Maybe I could close this request.

**Comment by HannesWell** [comment]
Just for clarification, @laeubi was reffering to the `External Tools` launching facility:
![grafik](https://user-images.githubusercontent.com/44067969/189619445-263566da-5425-48f8-9fac-c8ac65672723.png)

You could simply create a new Program that points to `mvnd` and specify the desired arguments. That should work already.

Alternatively we could consider to support mvnd as External Maven installation for M2E, as far as I now that basically just calls the mvn command in the specified installation's home, similar to what happens on the command-line (and by using external tools) and unlike the embedded maven runtime is launched.

**Comment by wsq93** [comment]
OK,  I tried to configure it in `External Tools Configurations`, and it was executed successfully.  And this way takes only about 7S to complete.
I don't seem to have used this in my mind.
Thank you!
