### ISSUE TITLE
Ctrl + Click is not working in pom.xml for eclipse 4.22+

### ISSUE THREAD

**Issue by arpit-107** [eclipse-m2e/m2e-core#910]
For eclipse 4.22 and above versions, in pom.xml, when ctrl + clicked on a dependency, it doesn't navigate to the source of that dependency. Till 4.21, it is working fine. Problem starts 4.22 onwards

**Comment by arpit-107** [comment]
These are the files and folders of various org.eclipse.m2e* from "InstallationDirectory\eclipse-jee-2021-12-R-win32-x86_64\eclipse\plugins"

org.eclipse.m2e.archetype.common_1.18.1.20211011-2139
org.eclipse.m2e.maven.indexer_1.18.1.20211011-2139
org.eclipse.m2e.maven.runtime.slf4j.simple_1.18.1.20211008-0657
org.eclipse.m2e.maven.runtime_1.18.1.20211011-2139
org.eclipse.m2e.sourcelookup_1.17.4.20211002-1029

org.eclipse.m2e.binaryproject.ui_1.18.1.20210610-0713.jar
org.eclipse.m2e.binaryproject_1.17.4.20211002-1029.jar
org.eclipse.m2e.core.ui_1.18.2.20211002-1029.jar
org.eclipse.m2e.core_1.18.3.20211018-0804.jar
org.eclipse.m2e.discovery_1.18.1.20211002-1029.jar
org.eclipse.m2e.editor.lemminx_1.18.3.20211116-0804.jar
org.eclipse.m2e.editor_1.18.2.20211002-1029.jar
org.eclipse.m2e.importer_1.17.3.20211002-1029.jar
org.eclipse.m2e.jdt.ui_1.17.2.20210603-1006.jar
org.eclipse.m2e.jdt_1.18.3.20211112-0847.jar
org.eclipse.m2e.launching_1.17.4.20211002-1029.jar
org.eclipse.m2e.lifecyclemapping.defaults_1.17.1.20210115-1536.jar
org.eclipse.m2e.logback.appender_1.17.2.20211002-0721.jar
org.eclipse.m2e.logback.configuration_1.16.3.20211002-1029.jar
org.eclipse.m2e.model.edit_1.18.2.20211002-1029.jar
org.eclipse.m2e.pde.ui_1.18.2.20211002-1029.jar
org.eclipse.m2e.pde_1.18.3.20211112-0847.jar
org.eclipse.m2e.profiles.core_1.17.2.20211115-0834.jar
org.eclipse.m2e.profiles.ui_1.17.3.20211002-1029.jar
org.eclipse.m2e.refactoring_1.17.3.20211002-1029.jar
org.eclipse.m2e.scm_1.17.2.20210603-1006.jar
org.eclipse.m2e.sourcelookup.ui_1.17.3.20211002-1029.jar
org.eclipse.m2e.workspace.cli_0.3.1.jar
org.eclipse.m2e.wtp.jaxrs_1.4.4.20201128-1705.jar
org.eclipse.m2e.wtp.jpa_1.4.4.20201128-1705.jar
org.eclipse.m2e.wtp.jsf_1.4.4.20201128-1705.jar
org.eclipse.m2e.wtp.overlay.ui_1.4.4.20201128-1705.jar
org.eclipse.m2e.wtp.overlay_1.4.4.20201128-1705.jar
org.eclipse.m2e.wtp_1.4.4.20201128-1705.jar

**Comment by mickaelistria** [comment]
OK, please try a more recent release of m2e and m2e-wtp. Eclipse IDE 2022-09 is due today or tomorrow, just try it when it's generally available and report whether you can reproduce this issue.

**Comment by arpit-107** [comment]
I am not able to reproduce this issue in eclipse 4.25. 

Thanks

**Comment by mickaelistria** [comment]
Thank you for trying and reporting it works.
