### ISSUE TITLE
Classloader problem in spring ide 

### ISSUE THREAD

**Issue by ahoehma** [eclipse-m2e/m2e-core#913]
spring ide:
Version: 4.15.3.RELEASE
Build Id: 202208110744

m2e
Eclipse.org - m2e	M2E Maven Integration for Eclipse Core	1.20.1.20220227-1319	org.eclipse.m2e.feature

since yesterday (don't know why) ... I got all the time such errors .. i.e. saving java-editor, open launchers etc.

Errors occurred during the build.
Errors running builder 'Maven Project Builder' on project 'rest-service-dm'.
loader constraint violation: loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @2055e7c9 wants to load class org.apache.maven.project.MavenProject. A different class with the same name was previously loaded by org.eclipse.osgi.internal.loader.EquinoxClassLoader @1c388703. (org.apache.maven.project.MavenProject is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1c388703, parent loader 'platform')

Any idea about this?

Kind Regards :)
Andreas

**Comment by mickaelistria** [comment]
Can you please provide a minimal project with steps to reproduce on a fresh workspace?
Also, can you please check `<workspace>/.metadata/.log` if more details appear?
