### ISSUE TITLE
tycho configurators depend on m2e-core 1.4.0, cannot find the update site

### ISSUE THREAD

**Issue by simlei** [eclipse-m2e/m2e-core#917]
Hi, 
in [JCrypTool](https://github.com/jcryptool/core), we apparently have a dependency from the tycho project configurators. Our oomph configuration ceased to install the Eclipse IDE with the following complaint:
```
  ERROR: org.eclipse.equinox.p2.director code=0 Missing requirement: Tycho Project Configurators 0.9.0.201811261502 (org.sonatype.tycho.m2e 0.9.0.201811261502) requires 'osgi.bundle; org.eclipse.m2e.core [1.4.0,2.0.0)' but it could not be found
```
I have tried to find an update site that ships m2e.core in version 1.4.0, but did not succeed. Are there any?

**Comment by laeubi** [comment]
There is only a minimum requirement to m2e 1.4 you can use any that is smaller than 2.0

But question is more: Why do you require "tycho project configurators"?

**Comment by simlei** [comment]
I'd love to just bump the requirement version on m2e-core. However, we don't control that; it seems to be controlled by our requirement in the oomph setup:
```xml
      <requirement
          name="org.sonatype.tycho.m2e.feature.feature.group" />
```

> But question is more: Why do you require "tycho project configurators"?

The short answer is, the IDE supports a RCP project built with maven / tycho, and without the project configurators, we get warnings in all of our pom.xml. However, they are only warnings:

```txt
Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-clean-plugin:2.5:clean (execution: default-clean-1, phase: initialize)	pom.xml
```

I'm content with leaving out the m2e connectors of our setup for now; however, it would be good to know where the update site for 1.4.0+ versions of m2e-core are.

**Comment by HannesWell** [comment]
> The short answer is, the IDE supports a RCP project built with maven / tycho, and without the project configurators, we get warnings in all of our pom.xml. However, they are only warnings:
> 
> ```
> Plugin execution not covered by lifecycle configuration: org.apache.maven.plugins:maven-clean-plugin:2.5:clean (execution: default-clean-1, phase: initialize)	pom.xml
> ```

Unfortunately M2E does not provide a lifecycle-mapping for the `clean` goal by default at the moment. The sonatype.tycho.m2e feature provides such mapping, but only ignores the goal's execution. So basically it just silences the warning.
But I have it on my TODO-list to add a lifecycle-mapping for the clean goal and a configurator that also handles extra clean locations.
In the meantime you can either accept the warning or apply the quick-fix of m2e to ignore the goal in the pom.xml

> 
> I'm content with leaving out the m2e connectors of our setup for now; however, it would be good to know where the update site for 1.4.0+ versions of m2e-core are.

The content of older versions is still available, but it has been moved to the archive:
https://archive.eclipse.org/technology/m2e/releases/

Nevertheless the old links are still working and will be re-directed so they are still usable in targets or setups:
https://download.eclipse.org/technology/m2e/releases/1.4

**Comment by HannesWell** [comment]
Is this issue still relevant?

**Comment by fbricon** [comment]
I've published an m2eclipse-tycho 0.10.0 build, compatible with m2e 2.x, to this new update site: https://github.com/tesla/m2eclipse-tycho/releases/download/latest/

**Comment by laeubi** [comment]
@fbricon actually m2e should come with everything needed fro Tycho, so the connector actually causes conflicts and should not be part of an "modern" Eclipse installation.

**Comment by fbricon** [comment]
off-the-shelf Tycho doesn't come with everything I need:
- Importing maven projects with tycho packaging, which don't have the .project/.classpath metadata has no effect. 
- Changing the Bundle-RequiredExecutionEnvironment and updating the Maven configuration has no effect

m2eclipse-tycho addresses those use cases and I haven't seen any conflict so far.

**Comment by laeubi** [comment]
> off-the-shelf Tycho doesn't come with everything I need:

If anything is missing we should address this.

> Importing maven projects with tycho packaging, which don't have the .project/.classpath metadata has no effect.

This seems a general m2e issue then and should not require any connector at all.

> Changing the Bundle-RequiredExecutionEnvironment in MANIFEST.MF and updating the Maven configuration has no effect

This should actually addressed by  `org.eclipse.m2e.pde.connector` and would not be directly specific for Tycho, so also work for bnd/felix plugin. It even sounds like a general m2e issue as well that is that changing the jre level is not correctly propagated to the project.

> I haven't seen any conflict so far

m2e disables the mappings of m2eclipse-tycho so you don't see any warnings but probably will see some code of that ignored.

**Comment by mickaelistria** [comment]
I'm closing it here as the issue doesn't seem to be about m2e but about some outdated connectors.
