### ISSUE TITLE
ConcurrentModificationException when downloading sources and/or javadoc

### ISSUE THREAD

**Issue by pcdavid** [eclipse-m2e/m2e-core#924]
Using Spring Tool Suite, recently updated to version 4.16 based on Eclipse 2022-09, and:

`org.eclipse.m2e.feature.feature.group version 2.0.5.20220912-1211`

I switched to a different git branch (from the cli), and while the workspace was rebuilding I got a series of error dialogs. The error log afterwards shows several instances of this:

```
eclipse.buildId=4.16.0.202209151144
java.version=18.0.2
java.vendor=Eclipse Adoptium
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=fr_FR
Framework arguments:  -product org.springframework.boot.ide.branding.sts4 -cssTheme none
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.springframework.boot.ide.branding.sts4 -cssTheme none

This is a continuation of log file XXX/wks/.metadata/.bak_0.log
Created Time: 2022-09-22 09:01:41.642

org.eclipse.m2e.core
Error
Thu Sep 22 15:55:38 CEST 2022
Unexpected internal Error occured

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1221)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.lambda$25(ProjectRegistryManager.java:1036)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at org.eclipse.m2e.core.internal.project.registry.ProjectRegistryManager.getMavenProject(ProjectRegistryManager.java:1036)
	at org.eclipse.m2e.core.internal.project.registry.MavenProjectFacade.getMavenProject(MavenProjectFacade.java:269)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.downloadMaven(DownloadSourcesJob.java:248)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.downloadFilesAndPopulateToUpdate(DownloadSourcesJob.java:220)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.lambda$0(DownloadSourcesJob.java:149)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:350)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:262)
	at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:205)
	at org.eclipse.m2e.core.embedder.IMaven.execute(IMaven.java:270)
	at org.eclipse.m2e.jdt.internal.DownloadSourcesJob.run(DownloadSourcesJob.java:149)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
```

**Comment by mickaelistria** [comment]
I often see this as well when opening projects.

**Comment by HannesWell** [comment]
Me too.

Since this happens in a `Collections.syncronizedMap()` I think this can only mean tha in the same thread within the scope of the function passed to computeIfAbsent() the map is modified. Maybe with nested projects?

**Comment by laeubi** [comment]
`Collections.syncronizedMap()` only ensures that *each individual method call* is syncronized, see the example here that this do not hold true for "complex" methods: https://docs.oracle.com/javase/8/docs/api/java/util/Collections.html#synchronizedMap-java.util.Map- Especially `computeIfAbsent` is not atomic .

**Comment by mickaelistria** [comment]
Would using a ConcurrentHashMap instead lead to better results?

**Comment by laeubi** [comment]
> Would using a ConcurrentHashMap instead lead to better results?

Depends on if this is a real concurrency issue or it is a problem with reentrance, the problem with all the `compute*` methods are that they clearly state that modify the map from inside such a computation is not allowed.

One solution might be that one does not cache the object itself, but a "CacheLine" that has a method to (lazy init) the object in question in a synchronized way, then one can make sure that the compute method always can return an object that never cause reentrance. Still then the (syncronized) getter method might need to be aware of reentrance but that then much smaller scoped.

**Comment by mickaelistria** [comment]
I've submitted https://github.com/eclipse-m2e/m2e-core/pull/928 which leverages Guava's cache.

**Comment by HannesWell** [comment]
> > Would using a ConcurrentHashMap instead lead to better results?
> 
> Depends on if this is a real concurrency issue or it is a problem with reentrance, the problem with all the `compute*` methods are that they clearly state that modify the map from inside such a computation is not allowed.

I strongly suspect that this is the reason for the exception, not a concurrency issue.
The computeIfAbsentMethod is not atomic but it is fully synchronized so no other thread can modify the map inbetween.
Therefore I think using Guava's cache doesn't help here.

> 
> One solution might be that one does not cache the object itself, but a "CacheLine" that has a method to (lazy init) the object in question in a synchronized way, then one can make sure that the compute method always can return an object that never cause reentrance. Still then the (syncronized) getter method might need to be aware of reentrance but that then much smaller scoped.

Seems to be a good solution for me. We could use a FutureTask as 'cacheLine' and execute the runnable outside of the map. That should prevent concurrent-modification due to nested projects.

**Comment by mickaelistria** [comment]
So far so good with snapshots (but maybe #933 is just hiding it at the moment). Let's close and reopen if issue persists.

**Comment by pcdavid** [comment]
Thnanks!

**Comment by TIBCOeddie** [comment]
YES THANK YOU!!! I was about to report in with details on this... Look forward to a release soon with this change!
