### ISSUE TITLE
m2e catalog 1.15 proposes m2e connectors which are incompatible with m2e 2.x

### ISSUE THREAD

**Issue by kwin** [eclipse-m2e/m2e-core#925]
If I select the modello connector from https://download.eclipse.org/technology/m2e/discovery/directory-1.15.xml I run into 

```
Operation details
Cannot complete the install because one or more required items could not be found.
Software being installed: m2e connector for modello 0.16.0.201409152009 (org.sonatype.m2e.modello.feature.feature.group 0.16.0.201409152009)
Missing requirement: m2e connector for modello 0.16.0.201409152009 (org.sonatype.m2e.modello 0.16.0.201409152009) requires 'osgi.bundle; org.eclipse.m2e.jdt [1.4.0,2.0.0)' but it could not be found
Cannot satisfy dependency:
From: m2e connector for modello 0.16.0.201409152009 (org.sonatype.m2e.modello.feature.feature.group 0.16.0.201409152009)
To: org.eclipse.equinox.p2.iu; org.sonatype.m2e.modello [0.16.0.201409152009,0.16.0.201409152009]
``` 

Please provide a new version of the catalog which only lists extensions compatible with m2e 2.x

**Comment by kwin** [comment]
As https://github.com/sonatype/modello is read-only and hasn't received an update since 2014 there is very little chance that this extension will ever be compatible with m2e 2.x :-(

**Comment by mickaelistria** [comment]
Contributions to the maintenance of the m2e discovery catalog are highly welcome.

**Comment by kwin** [comment]
Is that maintained at https://github.com/takari/m2e-discovery-catalog? Is there a dedicated branch for m2e 2.x?

**Comment by fbricon** [comment]
yeah it's the proper repo, no there's no dedicated branch. I tested quickly yesterday and looks like 95% of the extensions are incompatible with 2.x
I'll try to spent some time to cleanup and push another catalog tomorrow (no promises)

**Comment by kwin** [comment]
The entry already has the necessary version metadata: https://github.com/takari/m2e-discovery-catalog/blob/bc6d2990238117f7cbf8c96579b1284fb23e7aaf/org.eclipse.m2e.discovery.oss/src/main/resources-filtered/connectors.xml#L141 but it seems that this is not evaluated currently.

**Comment by kwin** [comment]
> looks like 95% of the extensions are incompatible with 2.x

One more reason to provide more graceful API evolutions in the future, it will take years for them to be updated...

**Comment by mickaelistria** [comment]
Can we try to use https://github.com/eclipse-m2e/m2e-discovery-catalog instead? The less we rely on external repo, the more the community is capable to efficiently maintain those.

**Comment by laeubi** [comment]
> > looks like 95% of the extensions are incompatible with 2.x
> 
> One more reason to provide more graceful API evolutions in the future, it will take years for them to be updated...

m2e can't handle the burdon of unmaintained projects, most connector are not maintained for years using heavily outdated API and has no documentation what they actually do, provide or solve.

beside that the catalogue approach is (from my point of view) simply not very well suited for handling different versions, but the same here, only a few people occasionally help with maintain that...

The best would be to keep the old catlouge as-is and simply start a new one with items that are proven to work with m2e...

**Comment by fbricon** [comment]
> Can we try to use https://github.com/eclipse-m2e/m2e-discovery-catalog instead? The less we rely on external repo, the more the community is capable to efficiently maintain those.

I don't know why there's a copy of this catalog in the m2e repo. AFAIR it's always been maintained outside of the EF. I don't remember why but, if I had to guess, probably because @ifedorenko and @jvanzyl were concerned about repercussions from installing non-EF vetted projects, with potential license/IP issues.  

I'm not saying we should keep doing that because it's how it's always been done, but I'd like to understand the original reasons for the decision, see if concerns still applies, before making changes. @ifedorenko / @jvanzyl any comment on that?

**Comment by HannesWell** [comment]
> > > looks like 95% of the extensions are incompatible with 2.x
> > 
> > 
> > One more reason to provide more graceful API evolutions in the future, it will take years for them to be updated...
> 
> m2e can't handle the burdon of unmaintained projects, most connector are not maintained for years using heavily outdated API and has no documentation what they actually do, provide or solve.

Most of the necessary adjustments are probably not too complicated and yes I suspect that the main problem is that many connectors are unmaintained. To make transitions to new major version smoother in the future (I hope they won't happen regularly) we actually only have to options, maintain more connectors within m2e-core or at least the m2e org or make connectors more and more obsolete by embedding lifecycle-mappings (like in https://github.com/eclipse-tycho/tycho/pull/1105) and/or by using some kind of build context to notify the IDE about changes like it is possible with sisu-build context.
Currently discussed here: https://github.com/eclipse-m2e/m2e-core/discussions/876

> 
> beside that the catalogue approach is (from my point of view) simply not very well suited for handling different versions, but the same here, only a few people occasionally help with maintain that...

Agree. Ideally the connectors would already be checked for compatibility with the running m2e version. On the other hand it would be nice to be able to update the catalog for new versions of Maven plug-ins that can be made visible immediately and users don't have to wait for a new release of m2e.
Therefore maybe one big catalog that provides a connector (with a specific version or from a certain repo) that matches the plug-in version and is compatible to the current m2e version would be great.


> 
> The best would be to keep the old catlouge as-is and simply start a new one with items that are proven to work with m2e...

Sounds not to bad.
What ever approach we use in the future I think it would be good if all necessary resources are accessible for all M2E committers to make updates simpler for them and thus faster.
It has been mentioned multiple times and I created https://github.com/eclipse-m2e/m2e-core/issues/833 in the past dedicated to that.

**Comment by ifedorenko** [comment]
> I don't know why there's a copy of this catalog in the m2e repo. AFAIR it's always been maintained outside of the EF. I don't remember why but, if I had to guess, probably because @ifedorenko and @jvanzyl were concerned about repercussions from installing non-EF vetted projects, with potential license/IP issues.

IIRC, we wanted to publish new catalogue frequently and eventually allow self-publishing and this went against eclipse foundation release review policies. So the compromise was to publish the catalogue externally but keep catalogue URL on the foundation servers (which essentially gave the foundation ability take over the catalogue should they decide that was necessary)

**Comment by mickaelistria** [comment]
I don't think the reason still stands. Something like a catalogue is not really a release but a service (see for example how Marketplace client has mutable content and no release of MPC nor Marketplace itself). And even so, Eclipse release process has been tremendously simplified so release reviews are not necessary in most case, release can be done on the spot without any delay./?
Do you think of any other reason that would be an issue moving the catalogue to m2e project?

**Comment by kwin** [comment]
Instead of maintaining a dedicated catalog for m2e 2.x the implementation in m2e should rather evaluate the version metadata in the catalog and only ever show compatible extensions.

**Comment by kwin** [comment]
@mickaelistria Can you enable issue tracking on https://github.com/eclipse-m2e/m2e-discovery-catalog?

**Comment by HannesWell** [comment]
Btw. can somebody tell the difference between the two repos?
- https://github.com/takari/m2e-discovery-catalog
- https://github.com/eclipse-m2e/m2e-discovery-catalog

On the first look I have the impression one is a divergent fork of the other.

**Comment by mickaelistria** [comment]
@kwin sorry I don't have admin permissions on the repo.
@fbricon can you please enable issue on https://github.com/eclipse-m2e/m2e-discovery-catalog as requested above.

> Btw. can somebody tell the difference between the two repos?

So far, the takari one has been the actually used one; but there were attempts (even before GitHub) to get the catalog under m2e directly. The eclipse-m2e is this attempt, and hopefully the future official catalog.

**Comment by fbricon** [comment]
https://github.com/eclipse-m2e/m2e-discovery-catalog/issues have at it
