### ISSUE TITLE
DuplicateRealmException .mvn/extensions.xml recent versions

### ISSUE THREAD

**Issue by hazendaz** [eclipse-m2e/m2e-core#937]
Recent m2e no longer will allow imports of projects that are maven if .mvn/extensions.xml exists.  It shows up with no pom to choose from.  The logs state duplicate realm exception.  Simply renaming the extensions.xml to anything else allows it to succeed and work again.

org.codehaus.plexus.classworlds.realm.DuplicateRealmException: coreExtension>fr.jcgay.maven:maven-profiler:3.2

Further, this issue makes it a mixed bag trying to resolve dependency hierarchy.  It sometimes works but will eventually fail with same error.  Renaming in this situation also allows it to immediately work again.

It does not seem to matter on project content otherwise.  The issue can present itself with a parent pom project.  Since I say mybatis used as an example on another issue, going to use same as I'm the lead on the maven setup there. 

Sample to use
https://github.com/mybatis/parent

m2e version 2.0.5.20220912-1211 (has been occurring in every 2.x).

**Comment by laeubi** [comment]
I did:

1. checkout https://github.com/mybatis/parent
2. Import > Existing maven project
3. Choose the checkout location
4. Project imports successful

So anything else to do to reproduce the issue? I also tried Maven > Update Project what also works.

**Comment by laeubi** [comment]
This should be fixed now. Please try out the latest snapshot build, you can use this p2 repository:

https://download.eclipse.org/technology/m2e/snapshots/latest/
