### ISSUE TITLE
Automatically add configured toolchains

### ISSUE THREAD

**Issue by laeubi** [eclipse-m2e/m2e-core#939]
Currently one needs to configure JVMs in maven toolchains.xml and eclipse independently.

It would be good if m2e adds configured toolchains automatically to the list of JDT ones, at best these are just "readonly" items with a type = "Maven Toolchain":

![grafik](https://user-images.githubusercontent.com/1331477/192197949-a38e3d7d-7fb3-4fcb-acd1-0dc317eef92d.png)

The extension point to use would be `org.eclipse.jdt.launching.vmTypes`
Maven Modello reader is `org.apache.maven.toolchain.building.ToolchainsBuilder` and the actual items are XppDom items, so maybe it would be usefull to simply use a DomParser directly instead.

`org.eclipse.jdt.internal.debug.ui.jres.InstalledJREsBlock.VMLabelProvider` could be enhanced to support custom Label/Images

According to `org.eclipse.jdt.internal.debug.ui.jres.InstalledJREsBlock.enableButtons()` contributed VMs cant be removed, but copied and edited, we should check if there is something needed to update VMs in the toolchains or disable such features.

**Comment by fbricon** [comment]
When it comes to automatic JRE management, [JRE Discovery ](https://github.com/sidespin/jre-discovery)does the job for me. I thought about adding a toolchains configurator, but since toolchains.xml already points to managed JDKs, I didn't feel like moving forward. But it'd be doable.
 
https://fbricon.github.io/posts/Eclipse-automatically-detect-managed-JREs/

**Comment by laeubi** [comment]
That looks great, I still think it would be good to have toolchains.xml support because it also covers non managed setups and seems a natural addition to m2e and would work cross-platform without any effort, do not requires configuration and so on.

As you seem to have a lot of experience in that area, would you mind to possibly rethink adding this to m2e even though it won't give much more value in managed setups?

**Comment by fbricon** [comment]
Feel free to open a PR to add toolchain support in JRE Discovery.
You can still fork or somehow duplicate the discovery functionality into m2e, but that wouldn't be my choice.

**Comment by mickaelistria** [comment]
+1 to have m2e automatically adding toolchains as installed JRE in the IDE (when no installed JRE already points to the toolchain location), that is a natural addition.

**Comment by mickaelistria** [comment]
> It would be good if m2e adds configured toolchains automatically to the list of JDT ones, at best these are just "readonly" items with a type = "Maven Toolchain":

I don't think you need to both with a dedicated type, just processing the toolchains.xml file and adding the VM as standard install like it's suggested in https://github.com/eclipse-jdt/eclipse.jdt.debug/pull/231 would already give very good results.

**Comment by mickaelistria** [comment]
Done in https://github.com/eclipse-m2e/m2e-core/pull/1404

**Comment by mickaelistria** [comment]
Here is a demo of this feature in Eclipse IDE and VSCode-Java: https://drive.google.com/file/d/1Xo_M4_NnTgJNgLFSZ33-XBscBSqgI_TT/view?usp=sharing
