### ISSUE TITLE
m2e defaults to JavaSE-18 instead of default Installed JRE

### ISSUE THREAD

**Issue by shawnweeks** [eclipse-m2e/m2e-core#992]
### Versions
Eclipse: 2022-09
m2e: 2.0.4
MacOS: 12.6
OpenJDK: 17.0.4.1

If you checkout the project `git clone https://github.com/IBM/trino-db2.git` on a system with OpenJDK 17 installed and configured as the default installed JRE in Eclipse or something like VSCode with Red Hat Java Plugin installed m2e seems to be setting the build path to a non existing `JavaSE-18` and then complains about a Unbound classpath container. Even setting `maven.compiler.target` and `maven.compiler.source` in the pom in the above project doesn't make any difference. If you edit the project's build path in Eclipse and force it go to JavaSE-17 everything works as expected until you reload the maven project again at which point it goes back to looking for the non existing JavaSE-18

If I revert Maven Integration to m2e 1.20.1 everything goes back to normal and the project correctly use the the default installed JRE defined in Eclipse and does not attempt to set it to JavaSE-18

Updating to m2e 2.0.4 causes the behavior to come back

```
Description	Resource	Path	Location	Type
Unbound classpath container: 'JRE System Library [JavaSE-18]' in project 'trino-db2'	trino-db2		Build path	Build Path Problem
```

**Comment by shawnweeks** [comment]
The VSCode Plugin redhat.java-1.11.0 is using m2e 2.0.0 which also exhibits this behavior but reverting to 1.6.0 which uses m2e 1.18.2 also makes the issue go away.

**Comment by shawnweeks** [comment]
I suspect this is related to the same issue as https://github.com/eclipse-m2e/m2e-core/issues/842. It appears that m2e is defaulting to the max possible Java version instead of the version that's installed and marked default.

**Comment by kwin** [comment]
This is no longer an issue with m2e 2.1.1. It duplicates #842.  With m2e 2.1.1 JavaSE 17 is correctly selected as JRE System Library.

**Comment by HannesWell** [comment]
Thanks for checking.
Sounds like this is completed and can be closed.
Please reopen If that's wrong.
